Label and schema index log internal recovery
neo4j/neo4j pull request #10087
Opened 2017-09-18 14:00 UTC by burqen

Log report of crashed pointer cleanup of underlying GBPTree to label and schema index.

This logging was accidentally removed from label index at time when lucene label scan store was removed. This PR re-introduces it and also add recovery logging for native schema index.

2017-09-22 08:35 UTC, tinwelint requested changes
I'm very much in favor of never passing in explicit `Log` into anything, instead doing such by means of `Monitor`... always. NativeLabelScanStore does this and I do think that this should be the case here too. WDYT?

2017-09-22 08:48 UTC, burqen commented
@tinwelint We already had `log` in there for this guy

```
    @Override
    public InternalIndexState getInitialState( long indexId, IndexDescriptor descriptor )
    {
        try
        {
            NativeSchemaIndexHeaderReader headerReader = new NativeSchemaIndexHeaderReader();
            GBPTree.readHeader( pageCache, nativeIndexFileFromIndexId( indexId ), new ReadOnlyMetaNumberLayout(),
                    headerReader );
            switch ( headerReader.state )
            {
            case BYTE_FAILED:
                return InternalIndexState.FAILED;
            case BYTE_ONLINE:
                return InternalIndexState.ONLINE;
            case BYTE_POPULATING:
                return InternalIndexState.POPULATING;
            default:
                throw new IllegalStateException( "Unexpected initial state byte value " + headerReader.state );
            }
        }
        catch ( IOException e )
        {
            log.error( "Failed to open index:" + indexId + ", requesting re-population.", e );
            return InternalIndexState.POPULATING;
        }
    }
```

So I took that shortcut. You make a good point though. Let's do it with monitors instead.

2017-09-25 13:09 UTC, burqen commented
@tinwelint Updated schema index to use monitor for logging

2017-09-26 10:54 UTC, tinwelint approved these changes
Looks sharp!

2017-09-26 13:48 UTC, burqen commented
@tinwelint Updated with satisfied dependencies for consistency checker

2017-09-27 08:10 UTC, merged