Move Cypher expressions to own module
neo4j/neo4j pull request #10094
Opened 2017-09-19 11:21 UTC by fickludd

The cypher compiler is a very complex piece of machinery, which is hard to understand because it's divided into only a few modules, which depend heavily on one another. 

Here cypher expressions are isolated into their own module. The same expressions classes are used directly in the AST, and then kept around throughout compilation and into the logical plan. In 3.3 they lived in the `frontend` module, and were heavily entangled in semantic analysis. However, most users of expressions are not concerned with semantic analysis, and should therefore not have to care about changes to this specific part of the compilation process. With the PR, the expressions have their own module, which in turn only depends on the new leaf module `util`.

To achieve this split, I had to

1. Move cypher global helper classes into a new leaf `util` module
2. Untangle expressions, patterns and functions from semantic analysis
3. Perform the actual move, together with all associated import updates

For reviewing, I would recommend to checkout the branch, and focus on the two new modules, as well as the changes to semantic analysis. Before review, this PR needs to be rebased on `3.4` once more when all the `3.3` cypher modules have been updated to their `3.4` variants.

2017-09-27 14:01 UTC, fickludd commented
@henriknyman @thobe. Rebased and ready for you. If acceptable I would prefer to merge this soon, as rebasing all the imports is very annoying and time consuming. It would be nice to make necessary improvements in a follow up PR.

2017-09-27 21:48 UTC, thobe commented
Error in module `org.neo4j:neo4j-enterprise-kernel`: Could not find artifact `org.neo4j:neo4j-cypher-util-3.4` - _looks like you removed a module but not all references to it_.

2017-09-28 08:11 UTC, henriknyman reviewed
Review in progress...

2017-09-28 08:11 UTC, henriknyman commented on community/cypher/cypher-compiler-3.4/src/main/scala/org/neo4j/cypher/internal/compiler/v3_4/planner/logical/CardinalityCostModel.scala
> +  private val PROBE_SEARCH_COST: CostPerRow = 11.5
Is the cost model supposed to be updated in this PR?

2017-09-28 08:11 UTC, henriknyman commented on community/cypher/cypher-compiler-3.4/src/test/scala/org/neo4j/cypher/internal/compiler/v3_4/ast/rewriters/NamespacerTest.scala
> -  }
Are these tests not needed anymore?

2017-09-29 12:09 UTC, henriknyman commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_4/helpers.scala
> +package org.neo4j.cypher.internal.compatibility.v3_2
Is v3_2 intentional here?

2017-09-29 12:09 UTC, henriknyman commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_1/helpers.scala
> +          case v3_1Phase.SEMANTIC_CHECK => v3_3Phase.SEMANTIC_CHECK
Is this change on purpose or  should it be v3_4?

2017-09-29 12:09 UTC, henriknyman commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v2_3/ExecutionResultWrapper.scala
> +        case OUTGOING => expressions.SemanticDirection.OUTGOING
They could all be `expression.`... (not important)

2017-09-29 12:09 UTC, henriknyman commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_4/runtime/planDescription/LogicalPlan2PlanDescription.scala
> +      .addArgument(Version("CYPHER 3.3"))
Why 3.3 ?

2017-09-29 12:09 UTC, henriknyman commented on community/cypher/cypher/src/test/scala/org/neo4j/cypher/ExecutionEngineIT.scala
> +  test("by default when using cypher 3.3 some queries should default to COST") {
Why 3.3 in this file?

2017-09-29 12:09 UTC, henriknyman commented on community/cypher/cypher/src/test/scala/org/neo4j/cypher/QueryCachingTest.scala
> +          s"cacheHit: CYPHER 3.3 $query")
Why 3.3?

2017-09-29 12:09 UTC, henriknyman commented on community/cypher/cypher/src/test/scala/org/neo4j/cypher/internal/compatibility/v3_4/runtime/planDescription/LogicalPlan2PlanDescriptionTest.scala
> +        PlanDescriptionImpl(id, "NodeHashJoin", TwoChildren(lhsPD, rhsPD), Seq(KeyNames(Seq("a")), EstimatedRows(2345), Version("CYPHER 3.3"), Planner("COST"), PlannerImpl("IDP")), Set("a", "b"))
Why 3.3?

2017-09-29 12:09 UTC, henriknyman commented on community/cypher/frontend-3.4/src/main/scala/org/neo4j/cypher/internal/frontend/v3_4/ast/rewriters/Namespacer.scala
> -
Is this intentionally removed?

2017-09-29 12:09 UTC, henriknyman commented on community/cypher/frontend-3.4/src/test/scala/org/neo4j/cypher/internal/frontend/v3_4/ast/ExpressionTest.scala
> -
Are these tests not needed anymore?

2017-09-29 12:09 UTC, henriknyman commented on community/cypher/pom.xml
> +          <version>0.4.0</version>
1.0.0 was no good?

2017-09-29 12:09 UTC, henriknyman commented on community/cypher/pom.xml
> +          </jvmArgs>
Does this make compilation faster?

2017-09-29 12:09 UTC, henriknyman commented on enterprise/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/QueryPlanCompactionAcceptanceTest.scala
> +        |Compiler CYPHER 3.3
Why 3.3?

2017-09-29 12:09 UTC, henriknyman commented on enterprise/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/SemanticErrorAcceptanceTest.scala
> +      s"$mess (line 1, column 45 (offset: 44))")
The column number seem to be more correct now?

2017-09-29 12:09 UTC, henriknyman commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_4/runtime/compiled/codegen/CodeGenConfiguration.scala
> +  * @param packageName The name of the v3_3 the produced code should belong to
Should be v3_4?

2017-09-29 12:09 UTC, henriknyman commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_4/runtime/compiled/codegen/CodeGenConfiguration.scala
> +                                packageName: String = "org.neo4j.cypher.internal.compiler.v3_3.generated"
v3_4?

2017-09-29 12:09 UTC, henriknyman commented on enterprise/cypher/cypher/src/test/scala/org/neo4j/cypher/internal/compiled_runtime/spi/v3_4/GeneratedMethodStructureTest.scala
> +package org.neo4j.cypher.internal.compiled_runtime.spi.v3_3
This should be v3_4?

2017-09-29 12:09 UTC, henriknyman commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v2_3/ExecutionResultWrapper.scala
> +import org.neo4j.cypher.internal.v3_4.expressions.SemanticDirection
This file has some names called xxx3_3 that could be renamed to xxx3_4

2017-09-29 12:09 UTC, henriknyman commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_4/helpers.scala
> +import org.neo4j.cypher.internal.compiler.v3_4.{CypherCompilerConfiguration => CypherCompilerConfiguration3_3}
This file has some names called xxx3_3 that could be renamed to xxx3_4

2017-09-29 12:09 UTC, henriknyman commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_1/helpers.scala
> +import org.neo4j.cypher.internal.frontend.v3_4.phases.CompilationPhaseTracer.{CompilationPhase => v3_3Phase}
This file has some names called xxx3_3 that could be renamed to xxx3_4

2017-09-29 12:13 UTC, henriknyman commented on community/cypher/expressions-3.4/pom.xml
> +          </args>
Maybe check that this is in sync with updates of scala-maven-plugin in other pom-files?

2017-09-29 12:14 UTC, henriknyman commented on community/cypher/frontend-3.4/pom.xml
> +      </plugin>
Is this intentionally added here?

2017-09-29 12:15 UTC, henriknyman commented on community/cypher/pom.xml
> +        <version>3.2.0</version>
Are these changes intentional?

2017-09-29 12:16 UTC, henriknyman commented on community/cypher/aux-3.4/pom.xml
> +        <artifactId>scala-maven-plugin</artifactId>
Maybe verify that this is in sync with updates to scala-maven-plugin in other pom-files?

2017-09-29 12:18 UTC, henriknyman requested changes
I suspect that it suffers from some problematic rebase conflict resolution

2017-09-29 17:19 UTC, fickludd commented on community/cypher/frontend-3.4/src/test/scala/org/neo4j/cypher/internal/frontend/v3_4/ast/ExpressionTest.scala
> -
This was actually correct, tests were moved to `SemanticAnalysisToolingTest`

2017-09-29 17:22 UTC, fickludd commented on enterprise/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/SemanticErrorAcceptanceTest.scala
> +      s"$mess (line 1, column 45 (offset: 44))")
Yupp, I snook in a small improvement on the error message position, as that actually was easier to implement

2017-10-02 15:25 UTC, henriknyman reviewed
A lot of new folders have v3_3 in the path

2017-10-03 09:36 UTC, henriknyman approved these changes

2017-10-03 10:29 UTC, merged