Manage bloom indexed keys by procedure
neo4j/neo4j pull request #10188
Opened 2017-10-02 13:47 UTC by ragadeeshu

2017-10-02 14:26 UTC, chrisvest requested changes
Looks fine, except we need to protect the maps in the provider, now.

2017-10-02 14:26 UTC, chrisvest commented on enterprise/fulltext-addon/src/main/java/org/neo4j/kernel/api/impl/fulltext/FulltextProvider.java
> +            writableNodeIndices.remove( identifier ).close();
We need to protect these hashmaps from concurrent access.

2017-10-03 09:17 UTC, ragadeeshu commented
@chrisvest updated

2017-10-05 09:37 UTC, chrisvest approved these changes

2017-10-05 13:15 UTC, merged