Ability to concatenate arbitrary lists.
neo4j/neo4j pull request #10245
Opened 2017-10-10 12:33 UTC by sherfert

Previously, the semantic checking did not allow concatenating mixed typed lists (and scalars). This PR fixes that.

2017-10-10 14:36 UTC, craigtaverner requested changes
Approved except for scala code style deviations

2017-10-10 14:36 UTC, craigtaverner commented on community/cypher/frontend-3.3/src/main/scala/org/neo4j/cypher/internal/frontend/v3_3/symbols/TypeSpec.scala
> +  def covariant : TypeSpec =TypeSpec(ranges.map(_.covariant))
Whitespace

2017-10-10 14:36 UTC, craigtaverner commented on community/cypher/frontend-3.3/src/main/scala/org/neo4j/cypher/internal/frontend/v3_3/symbols/TypeSpec.scala
> +    if(coerced.nonEmpty)
formatting

2017-10-10 14:36 UTC, craigtaverner commented on community/cypher/frontend-3.3/src/main/scala/org/neo4j/cypher/internal/frontend/v3_3/ast/ArithmeticFunctions.scala
> +      if(lhsListTypes.nonEmpty && rhsListTypes.nonEmpty) {
formatting

2017-10-10 17:40 UTC, craigtaverner approved these changes

2017-10-11 13:09 UTC, craigtaverner requested changes
The original bug was reported on 3.2, but this PR is against 3.3. We should fix this in 3.2.

2017-10-12 10:19 UTC, sherfert commented
Retargeted to 3.2: https://github.com/neo4j/neo4j/pull/10270

2017-10-12 10:19 UTC, closed without merging