Removed name of slots and changed projection to produce LongSlots
neo4j/neo4j pull request #10275
Opened 2017-10-12 14:31 UTC by SaschaPeukert

2017-10-12 21:34 UTC, henriknyman submitted a review, later dismissed
Removing name from slots makes for a horrible debugging experience

2017-10-13 04:43 UTC, systay commented
We removed the name from slot because we now can have two different variables sharing the same slot. The name information is still available in the `PipelineInformation`.

2017-10-13 07:13 UTC, henriknyman commented
@systay I understand it was because of the multiple aliased names, but I still think we need to at least project this information in the implementation of  `PrimitiveExecutionContext.iterator` (that is used for debugging) or I strongly believe it will slow down development too much. Also currently there is no backward map from slots to names so the information is not easily available. 

We could either keep the name in the slot as a Set or Seq or add a separate map from slot to set of names. (Even keeping the first name would be better than not fixing this since it would work in >95% of cases).

2017-10-13 10:31 UTC, henriknyman commented on enterprise/cypher/physical-planning/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_4/runtime/PipelineInformation.scala
> +    new PipelineInformation(this.slots.clone(), numberOfLongs, numberOfReferences)
We are losing alias information here

2017-10-30 08:16 UTC, henriknyman commented
We still need to deduplicate aliased slots in some places. I have a WIP-commit for that which I will try to finish off. After that somebody else should review again since there are a lot of changes.

2017-10-30 08:56 UTC, systay requested changes
Nice changes! Could you please add a few tests to make sure the bugs you have fixed don't reappear in the future?

2017-11-01 12:22 UTC, closed without merging