Merge multiple IN predicates
neo4j/neo4j pull request #10277
Opened 2017-10-13 07:03 UTC by pontusmelke

For queries with multiple in on the same identifier separated by AND
we can merge into to one big list.

Examples:
```
MATCH (a) WHERE a.prop IN [1,2,3] AND a.prop IN [2,3,4] RETURN * =>
MATCH (a) WHERE a.prop IN [2,3]  RETURN *
```

```
MATCH (a) WHERE a.prop IN [1,2,3] AND a.prop IN [5,6,7] RETURN * =>
MATCH (a) WHERE FALSE RETURN *
```

2017-10-13 13:33 UTC, fickludd requested changes
Some leftovers and a question. Like the concept. Thought the implementation was a little hard to read, but maybe I'm just inexperienced with rewriters, or they are just hard to code.

2017-10-13 13:33 UTC, fickludd commented on community/cypher/frontend-3.4/src/main/scala/org/neo4j/cypher/internal/frontend/v3_4/ast/rewriters/mergeInPredicates.scala
> +// In(Property(Variable(a),PropertyKeyName(foo)),ListLiteral(List(StringLiteral(bar)))))))), Return(false,ReturnItems(true,List()),None,None,None,None,Set()))))
Ghostlines!

2017-10-13 13:33 UTC, fickludd commented on community/cypher/cypher-compiler-3.4/src/test/scala/org/neo4j/cypher/internal/compiler/v3_4/ast/rewriters/mergeInPredicatesTest.scala
> +      "MATCH (a) WHERE a.prop IN [2,3] OR a.prop IN [3,4] RETURN *")
Could we rewrite 
`WHERE a.prop IN [2,3] OR a.prop IN [3,4]` => `WHERE a.prop IN [2,3,4]`?

2017-10-13 19:06 UTC, pontusmelke commented
@fickludd 
- added support for `OR`, good idea.
- removed ghostly cruft
- Did very little to make the code more readable, not sure what to do actually. Open for suggestions.

2017-10-16 09:08 UTC, fickludd approved these changes

2017-10-16 09:10 UTC, fickludd commented
Very nice @pontusmelke! Does this rewrite happen after `a.prop = 2` `=>` `a.prop IN [2]`? That would increase it's value.

2017-10-16 11:20 UTC, pontusmelke commented
@fickludd No unfortunately we do auto-parametrization in between, this rewriter depends having the values there for us to use. However I am investigating if we could move rewriters around a little bit since I think we do it wrong on a couple of places. Consider that a later optimization though.

2017-10-16 14:26 UTC, merged