Turn off compiled runtime for multiple aggregations
neo4j/neo4j pull request #10358
Opened 2017-10-30 14:36 UTC by pontusmelke

The compiled runtime is not doing the right thing when having multiple
aggregations, e.g.
```
MATCH (a)-->(b)
RETURN a.prop, count(a.p1), count(b.p2)
```

This PR disables the compiled runtime from queries that contains more than one aggregation.

2017-10-31 14:15 UTC, craigtaverner requested changes

2017-10-31 14:15 UTC, craigtaverner commented on enterprise/cypher/cypher-compiled-runtime-3.2/src/main/scala/org/neo4j/cypher/internal/compiled_runtime/v3_2/codegen/LogicalPlanConverter.scala
> +    notValid && p.aggregationExpression.values.toList.treeCount {
I would have thought this should be `||` instead of `&&` so that either of the failing conditions can cause the compiled runtime to not be used.

2017-10-31 14:15 UTC, craigtaverner commented on enterprise/cypher/cypher-compiled-runtime-3.2/src/main/scala/org/neo4j/cypher/internal/compiled_runtime/v3_2/codegen/LogicalPlanConverter.scala
> +                                                     c -> ExpressionConverter
Was this reformatting necessary?

2017-11-01 07:14 UTC, pontusmelke commented
@craigtaverner Nice catch, fixed it and removed the unnecessary reformatting

2017-11-01 15:33 UTC, jexp commented
@pontusmelke do we really need to turn it off instead of fixing it?

2017-11-02 16:05 UTC, craigtaverner approved these changes

2017-11-03 08:44 UTC, merged