Remove the logical plan Argument
neo4j/neo4j pull request #10362
Opened 2017-10-31 09:43 UTC by systay

At run time, we do not differentiate between SingleRow and Argument. So,
our code can be simplified by just removing Argument and not have
special planner code for it

2017-10-31 09:44 UTC, systay commented
Moved the changes to the 3.4 branch

2017-10-31 14:20 UTC, craigtaverner approved these changes

2017-11-08 15:54 UTC, craigtaverner requested changes

2017-11-08 15:54 UTC, craigtaverner commented on enterprise/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/PatternExpressionImplementationAcceptanceTest.scala
> +        planDescription.find("SingleRow") shouldNot be(empty)
How can we test for SingleRow when plans never print this in the plan description?

2017-11-08 17:13 UTC, craigtaverner approved these changes

2017-11-09 15:36 UTC, merged