Added configurable cypher query replan threshold decay algorithms
neo4j/neo4j pull request #10489
Opened 2017-11-21 16:07 UTC by OliviaYtterbrink

2017-11-21 16:29 UTC, craigtaverner commented
One idea I had was to simplify the three new config settings into one.

This means changing:

* `unsupported.cypher.statistics_divergence_target=0.1` (slowly reduce the threshold down to 10% so that queries ultimately get replanned even with small database changes)
* `unsupported.cypher.target_replan_interval=7h` (take 7h to reduce the threshold down to 10%)
* `unsupported.cypher.replan_algorithm=inverse` (use an inverse function to model threshold decay)

Into:

* `unsupported.cypher.replan_algorithm=inverse(0.1,7h)` (take 7h to reduce the threshold down to 10% using 'inverse' function)

The advantage is that it is only one setting, the disadvantage is that the neo4j.conf settings system cannot be used to pre-filter valid options. We currently already have numerically invalid options (like threshold increase instead of decrease) result in no decay (revert to old behaviour), but it feels like we will have even less opportunity to have neo4j.conf parsing checks with this simpler single config.

2017-11-23 10:22 UTC, pontusmelke requested changes
Looks good, just a couple of minor things.

2017-11-23 10:22 UTC, pontusmelke commented on community/cypher/cypher-compiler-3.2/src/main/scala/org/neo4j/cypher/internal/compiler/v3_2/executionplan/ExecutionPlan.scala
> +  def isStale(lastTxId: () => Long, statistics: GraphStatistics): (Boolean, Int)
To me it is not obvious what this function returns now, the extra `int` is a bit confusing. Could we rewrite to something like:

```
def checkCache(lastTxId: () => Long, statistics: GraphStatistics): CacheData
```
where

```
case class CacheData(isStale:Boolean, ageInSeconds: Int)
```
(But better names please)

2017-11-23 10:22 UTC, pontusmelke commented on community/cypher/cypher-compiler-3.2/src/main/scala/org/neo4j/cypher/internal/compiler/v3_2/CacheAccessor.scala
> +          val stale = isStale(value)
`val (isStale, age) = isStale(value)`

2017-11-23 10:22 UTC, pontusmelke commented on community/cypher/cypher-compiler-3.2/src/main/scala/org/neo4j/cypher/internal/compiler/v3_2/executionplan/PlanFingerprint.scala
> +    initialThreshold * Math.pow(Math.E, exponent)
~`Math.pow(Math.E, exponent)`~ -> `Math.exp(exponent)`

2017-11-23 10:22 UTC, pontusmelke commented on community/cypher/cypher-compiler-3.2/src/main/scala/org/neo4j/cypher/internal/compiler/v3_2/spi/InstrumentedGraphStatistics.scala
> +case class GraphStatisticsSnapshot(statsValues: Map[StatisticsKey, Double] = Map.empty, timestamp: Date = new Date) {
I can't see where we use the timestamp?

2017-11-23 10:22 UTC, pontusmelke commented on community/cypher/cypher-compiler-3.2/src/main/scala/org/neo4j/cypher/internal/compiler/v3_2/executionplan/PlanFingerprint.scala
> +case class StatsDivergenceInverseDecayCalculator(initialThreshold: Double, targetThreshold: Double, initialMillis: Long, targetMillis: Long) extends StatsDivergenceCalculator {
Do we really need two different calculators? How would we tell an end-user when to use one or the other?

2017-11-23 10:22 UTC, pontusmelke commented on community/kernel/src/main/java/org/neo4j/graphdb/factory/GraphDatabaseSettings.java
> +                  "abs(a-b)/max(a,b). This means that a value of 0.75 requires the database to approximately " +
If you want this here I think you need to explain what `a` and `b` are (and they are not always cardinalities, could also be a selectivity)

2017-11-23 14:31 UTC, pontusmelke approved these changes

2017-11-24 15:42 UTC, merged