Diagnostics report tool, first iteration
neo4j/neo4j pull request #10642
Opened 2017-12-14 12:23 UTC by klaren

This intruduces `neo4j-admin report`

2017-12-14 12:47 UTC, tinwelint commented on community/dbms/src/main/java/org/neo4j/commandline/dbms/DiagnosticsReportCommandProvider.java
> +                "the '--list' flag. If no classifiers are passed, the default list of `logs configs` will be used." ;// TODO: default classifiers
Would be nice if the default list would be an accessible constant which this string would include, to not let them go out of sync in the future.

2017-12-14 12:49 UTC, tinwelint commented
And generally regarding errors, it may be nice having the ability to print stack traces... We all know how frustrating it is to try and figure out a cause by only seeing the error.toString()

2017-12-22 11:41 UTC, MishaDemianenko requested changes

2017-12-22 11:41 UTC, MishaDemianenko commented on community/dbms/src/main/java/org/neo4j/commandline/dbms/DiagnosticsReportCommand.java
> +    private static OptionalNamedArg destinationArgument =
a bit more fields can be final in this class

2017-12-22 11:41 UTC, MishaDemianenko commented on community/dbms/src/main/java/org/neo4j/commandline/dbms/DiagnosticsReportCommand.java
> +            try ( BufferedReader reader = new BufferedReader( fs.openAsReader( pidFile.toFile(), Charset.defaultCharset() ) ) )
lets extract pid reading into separate helper method

2017-12-22 11:41 UTC, MishaDemianenko commented on community/dbms/src/main/java/org/neo4j/commandline/dbms/DiagnosticsReportCommand.java
> +    public void execute( String[] stringArgs ) throws IncorrectUsage, CommandFailed
a lot of things is going on inside this method would be good to extract some parts out of it

2017-12-22 11:41 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/diagnostics/ProgressAwareInputStream.java
> +        int percent = (int) (totalRead * 100 / size);
i would add additional check to make sure we will never make it to more then 100 :)

2017-12-22 11:41 UTC, MishaDemianenko commented on community/dbms/src/main/java/org/neo4j/dbms/report/jmx/JmxDump.java
> +                ProgressAwareInputStream inStream = new ProgressAwareInputStream( in, size, monitor::percentChanged );
this stream needs to be closed

2017-12-22 11:41 UTC, MishaDemianenko commented on community/dbms/src/main/java/org/neo4j/dbms/report/jmx/JmxDump.java
> +        JMXConnector connect = JMXConnectorFactory.connect( url );
would be nice to close this connector in the end

2017-12-22 11:41 UTC, MishaDemianenko commented on community/dbms/src/test/java/org/neo4j/commandline/dbms/DiagnosticsReportCommandIT.java
> +        String processName = java.lang.management.ManagementFactory.getRuntimeMXBean().getName();
we need to check that this works on all vm's that we need to support

2017-12-22 11:41 UTC, MishaDemianenko commented on community/dbms/src/test/java/org/neo4j/commandline/dbms/DiagnosticsReportCommandTest.java
> +        System.setProperty( "user.dir", testDirectory.absolutePath().getAbsolutePath() );
we need to restore previous property value in tear down

2017-12-22 11:41 UTC, MishaDemianenko commented on community/dbms/pom.xml
> +  <profiles>
wdyt about moving this profiles to root pom instead?

2017-12-22 11:41 UTC, MishaDemianenko commented on community/dbms/pom.xml
> +  <!--<build>-->
something to cleanup

2017-12-22 11:41 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/diagnostics/DiagnosticsReporter.java
> +    private static class Mon implements DiagnosticsReporterProgressCallback
🚳

2017-12-22 11:41 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/diagnostics/DiagnosticsReportSources.java
> +            ProgressAwareInputStream inStream = new ProgressAwareInputStream( in, size, monitor::percentChanged );
this stream needs to be closed

2017-12-22 11:41 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/diagnostics/DiagnosticsReportSources.java
> +            Files.write( archiveDestination, message.getBytes( Charset.forName( "UTF8" ) ), StandardOpenOption.CREATE,
StandardCharsets.UTF_8

2017-12-22 11:42 UTC, MishaDemianenko commented
@klaren couple of comments also i think we need to think about moving it out of kernel as much as possible and maybe move all of the diagnostics inside dbms module into its own package

2018-01-03 06:47 UTC, klaren commented on community/dbms/pom.xml
> +  <profiles>
I feel horrible just including this, let's keep the exposure to a minimum.

2018-01-03 06:47 UTC, klaren commented on community/dbms/src/main/java/org/neo4j/dbms/report/jmx/JmxDump.java
> +        JMXConnector connect = JMXConnectorFactory.connect( url );
In the current state, this will always use RMI and that does not require a proper close call.

2018-01-03 06:49 UTC, klaren commented on community/dbms/src/main/java/org/neo4j/dbms/report/jmx/JmxDump.java
> +                ProgressAwareInputStream inStream = new ProgressAwareInputStream( in, size, monitor::percentChanged );
Nice catch!

2018-01-03 06:59 UTC, klaren commented
@MishaDemianenko I tried to reduce the code in kernel, the problem is
```java
import org.neo4j.kernel.configuration.Config;
```
that gives a cycle in the dependencies.

2018-01-03 07:02 UTC, klaren commented on community/dbms/src/test/java/org/neo4j/commandline/dbms/DiagnosticsReportCommandIT.java
> +        String processName = java.lang.management.ManagementFactory.getRuntimeMXBean().getName();
Yes, should probably change that assume to assert.

2018-01-05 12:36 UTC, MishaDemianenko requested changes
Couple of code comments.
Also even for first iterations we need to have a bit more test at least around code reporting code (progress is reported, report presented to user etc)
We need to ask about what kind of documentation needs to be updated and operability team should take a look for our entry script/naming/etc.

2018-01-05 12:36 UTC, MishaDemianenko commented on enterprise/causal-clustering/src/main/java/org/neo4j/causalclustering/diagnostics/ClusterDiagnosticsOfflineReportProvider.java
> +            if ( file.getName().equals( RAFT_LOG_DIRECTORY_NAME ) )
it can be a good idea to supply filename filter instead to 'fs.listFiles' as second argument

2018-01-05 12:36 UTC, MishaDemianenko commented on enterprise/causal-clustering/src/main/java/org/neo4j/causalclustering/diagnostics/ClusterDiagnosticsOfflineReportProvider.java
> +        String currentLevel = path + "/" + dir.getName();
File.separator instead of "/"?

2018-01-05 12:36 UTC, MishaDemianenko commented on community/dbms/src/main/java/org/neo4j/commandline/dbms/DiagnosticsReportCommand.java
> +            new OptionalCanonicalPath( "to", "/tmp/", "reports/", "Destination directory for reports" );
for some of the users `/tmp` can be a mysterious example, maybe we can change it to something more verbose/descriptive that also use platform base file.separator?

2018-01-05 12:36 UTC, MishaDemianenko commented on community/dbms/src/main/java/org/neo4j/commandline/dbms/DiagnosticsReportCommand.java
> +            if ( orphans.size() == 0 )
please use isEmpty instead

2018-01-05 12:36 UTC, MishaDemianenko commented on community/dbms/src/main/java/org/neo4j/commandline/dbms/DiagnosticsReportCommand.java
> +        // TODO: middle, and part warn the user if it's larger than a given threshold
lets convert those todos into cards

2018-01-05 12:36 UTC, MishaDemianenko commented on community/dbms/src/main/java/org/neo4j/commandline/dbms/DiagnosticsReportCommand.java
> +            reporter.dump( new HashSet<>( orphans ), reportFile );
maybe we can convert orphans to set directly where we initialize it?

2018-01-05 12:36 UTC, MishaDemianenko commented on community/dbms/src/main/java/org/neo4j/commandline/dbms/DiagnosticsReportCommand.java
> +        if ( s == null )
will `StringEscapeUtils.escapeCsv( s )` work instead?

2018-01-05 12:36 UTC, MishaDemianenko commented on community/dbms/src/main/java/org/neo4j/commandline/dbms/DiagnosticsReportCommand.java
> +    static String describeClassifier( String classifier )
would suggest asking our cs eng. about names for those classifiers if they think its understandable for them and for customers

2018-01-05 12:36 UTC, MishaDemianenko commented on community/dbms/src/main/java/org/neo4j/dbms/diagnostics/jmx/JmxDump.java
> +                ObjectName name = new ObjectName( "org.neo4j:instance=kernel#0,name=Reports" ); // TODO: instance #0 ??
todo

2018-01-05 12:36 UTC, MishaDemianenko commented on community/dbms/pom.xml
> +      <id>jigsaw</id>
we do not really need this profile right?

2018-01-05 12:36 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/diagnostics/DiagnosticsReporter.java
> +    // TODO:
todo

2018-01-05 12:50 UTC, klaren commented on community/dbms/src/main/java/org/neo4j/commandline/dbms/DiagnosticsReportCommand.java
> +        if ( s == null )
yes it will!

2018-01-07 16:18 UTC, MishaDemianenko approved these changes

2018-01-07 16:19 UTC, MishaDemianenko commented
@klaren approved, but please not failing test that fails because of the unpredictable order of classifiers.

2018-01-08 15:08 UTC, praveenag approved these changes
Approved once the changes requested are applied and merged with this PR

2018-01-09 09:32 UTC, merged