Update java 9 profile to build with target 9 instead of 8
neo4j/neo4j pull request #10685
Opened 2017-12-27 01:59 UTC by MishaDemianenko

Use unnamed modules for now; introduce separate property for
scala vm version since current version does not support have support
for -target:jvm-9
Use unnamed modules, export missed packages to unnamed modules.
Separate warm hugs to 'javax.xml.bind.DatatypeConverter' lovers.

2018-01-02 09:57 UTC, MishaDemianenko commented
Jersey so far does not have support for java 9. This PR, if it will be merged, should fix that:  https://github.com/jersey/jersey-1.x/pull/25

2018-01-03 05:59 UTC, klaren commented
Looks good. This might break user code that relies on the fact we bundle `jersey-multipart` though. Also, I believe that revapi still poses a problem with the execution time.

2018-02-26 10:10 UTC, MishaDemianenko commented
@klaren i do not think our jersey update will be resolved anytime soon, so i just switched back versions to 1.8 even for java 9 profile, but at least we will have automatic module names for what we have now

2018-02-28 09:48 UTC, klaren requested changes
It looks a bit incinsistent with both
```
org.neo4j.internal.cypher.*
```
and
```
org.neo4j.cypher.internal.*
```
as module names. I would prefer the first one to align it with `org.neo4j.internal.kernel.api`.

2018-02-28 09:48 UTC, klaren commented on community/server/src/test/java/org/neo4j/server/rest/transactional/ConcurrentTransactionAccessTest.java
> -import static javax.xml.bind.DatatypeConverter.parseLong;
:egg:

2018-02-28 13:03 UTC, klaren approved these changes
It matches root packages so it's fine.

2018-02-28 23:24 UTC, merged