Remove unnecessary set
neo4j/neo4j pull request #10745
Opened 2018-01-08 07:01 UTC by pontusmelke

There is no reason to store an extra copy of the removed nodes, instead
delegate to the tx state to do the check.

2018-01-09 14:04 UTC, fickludd requested changes
I'm slightly unsure about the `nodeLabelUnionScan` so would like to discuss that before merging. It seems to behave the same as `nodeLabelIntersectScan` to me, but maybe I'm misreading somehow. I guess we don't really have any way to benefit from scanning over multiple layers yet anyway, as the label scan store is on single label? So we could just slam `UnsupportedOperationException` on these methods until the kernel can provide a more effective implementation or someone want to use them in the runtime.

Otherwise great test coverage and nice implementation.

2018-01-09 14:04 UTC, fickludd commented on community/cypher/cypher-planner-3.4/src/main/scala/org/neo4j/cypher/internal/compiler/v3_4/planner/CantCompileQueryException.scala
> +  if (cause != null) cause.printStackTrace()
Whoops

2018-01-09 14:04 UTC, fickludd commented on community/kernel-api/src/test/java/org/neo4j/internal/kernel/api/TransactionStateTestBase.java
> +            tx.dataWrite().nodeAddLabel( node.node, node.labels[0] );
Did you mean to re-assign the same label to the node, or should it be created with no label?

2018-01-09 14:04 UTC, fickludd commented on community/kernel-api/src/test/java/org/neo4j/internal/kernel/api/TransactionStateTestBase.java
> +            tx.dataRead().nodeLabelUnionScan( cursor, node.labels );
Maybe I'm confused. I though the Union scan should return all nodes with a least one of the provided labels? In that we should still find node as it retains `:label1`.

2018-01-12 12:28 UTC, pontusmelke commented on community/kernel-api/src/test/java/org/neo4j/internal/kernel/api/TransactionStateTestBase.java
> +            tx.dataRead().nodeLabelUnionScan( cursor, node.labels );
No the confusion is on me. I disabled `nodeIntersectionScan` for now since it is tricky to combine with tx state and currently not used.

2018-01-15 14:34 UTC, fickludd approved these changes

2018-01-16 10:18 UTC, merged