Allow changing types of properties
neo4j/neo4j pull request #10761
Opened 2018-01-10 09:40 UTC by pontusmelke

Before applying a property update to the transaction state we do a check
to see if the value has actually been changed. However since by our
equality semantics a change of type not necessarily implies a change of
value, e.g. `intValue == tofloat(intvalue)` evaluates to `true`
(at least for integers small enough to fit into the mantissa of the
float), we run into problems when users want to force a type change via
for example,

```
MATCH (n) SET n.prop = tofloat(n.prop)

```

in cypher or via

```
n.setProperty( "prop", (double) n.getProperty("prop") );
```

in Core API.

2018-01-11 10:40 UTC, MishaDemianenko requested changes
One small thing from me

2018-01-11 10:40 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/StateHandlingStatementOperations.java
> +            if ( property.getClass() != existingProperty.getClass() || !property.equals( existingProperty ) )
instead of copypasting comment and update check in 2 places please extract helper method instead

2018-01-12 12:39 UTC, pontusmelke commented
@MishaDemianenko fixed

2018-01-12 13:40 UTC, MishaDemianenko approved these changes

2018-01-15 09:57 UTC, merged