Solve nested unwind bug in compiled runtime and add some feature tests.
neo4j/neo4j pull request #10825
Opened 2018-01-17 09:56 UTC by Lojjs

To be forward merged to 3.3 and 3.4

2018-01-17 15:54 UTC, sherfert commented on community/cypher/cypher/src/main/java/org/neo4j/cypher/internal/codegen/CompiledConversionUtils.java
> +            String[] singleStringArray = {(String) iterable};
You can use Stream.of( iterable ).iterator()

2018-01-19 10:22 UTC, craigtaverner requested changes

2018-01-19 10:22 UTC, craigtaverner commented on enterprise/cypher/acceptance-spec-suite/src/test/resources/cypher/features/UnwindAcceptance.feature
> +      WITH [['a', 'b'], ['c', 'd'], 'e'] AS nested
Should also work with mixed types

2018-01-19 10:22 UTC, craigtaverner commented on community/cypher/cypher/src/main/java/org/neo4j/cypher/internal/codegen/CompiledConversionUtils.java
> +        else if ( iterable instanceof String )
Is it necessary to have type specific checks here? Perhaps just `Stream.of(iterable)` in the `else` clause would be simpler? What does the interpreted runtime do in this case?

2018-01-22 07:42 UTC, sherfert commented on community/cypher/cypher/src/main/java/org/neo4j/cypher/internal/codegen/CompiledConversionUtils.java
> +        else if ( iterable instanceof String )
Usually the primitive streams are more performant. But then again, a stream with just one element won't be a bottleneck...

2018-01-22 07:45 UTC, Lojjs commented on enterprise/cypher/acceptance-spec-suite/src/test/resources/cypher/features/UnwindAcceptance.feature
> +      WITH [['a', 'b'], ['c', 'd'], 'e'] AS nested
Good point, I have added a new test for that.

2018-01-22 14:40 UTC, craigtaverner approved these changes

2018-01-22 14:52 UTC, merged