Launder clothes, not exceptions
neo4j/neo4j pull request #10853
Opened 2018-01-19 14:22 UTC by klaren

Removes `Exceptions.launderedExceptions()`
* It hides important logic, very hard to derive what exceptions are actually thrown.
* It facilitates catching `Throwable`, which should be avoided and painful if you have to do it.

Removes `Exceptions.withSuppressed()`
* `.addSuppressed()` can be used instead.

2018-01-24 15:29 UTC, MishaDemianenko requested changes
Couple of things here and there great otherwise

2018-01-24 15:29 UTC, MishaDemianenko commented on enterprise/ha/src/test/java/org/neo4j/kernel/impl/ha/ParallelLifecycle.java
> +                exception = combine( exception, e );
a bit of NPE's will happen inside of combine on the first exception

2018-01-24 15:29 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/helpers/RunCarefully.java
> +        List<Throwable> errors = new LinkedList<>();
please just use arraylist

2018-01-24 15:29 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/store/CommonAbstractStore.java
> +    void setStoreNotOk( RuntimeException cause )
not sure we need to restring this to only runtime ex, should we?

2018-01-24 15:29 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/entry/VersionAwareLogEntryReader.java
> +                    throw e;
should we just return here instead of outer catch block then?

2018-01-29 14:58 UTC, klaren commented on community/kernel/src/main/java/org/neo4j/kernel/impl/store/CommonAbstractStore.java
> +    void setStoreNotOk( RuntimeException cause )
If anyone needs that it's easy to refactor.

2018-01-29 14:58 UTC, klaren commented
@MishaDemianenko New commits :tada:

2018-01-30 10:35 UTC, klaren commented on community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/entry/VersionAwareLogEntryReader.java
> +                    throw e;
I think we leave it like this to minimize the number of exit points.

2018-01-30 16:08 UTC, MishaDemianenko approved these changes

2018-01-31 15:21 UTC, merged