Calculates correct max memory to use for caching
neo4j/neo4j pull request #10965
Opened 2018-02-06 14:57 UTC by tinwelint

2018-02-06 23:16 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/Configuration.java
>      }
Stray `main`.

2018-02-06 23:26 UTC, tinwelint commented
<blush>

Den 7 feb. 2018 00:16 skrev "Chris Vest" <notifications@github.com>:

> *@chrisvest* commented on this pull request.
> ------------------------------
>
> In community/kernel/src/main/java/org/neo4j/unsafe/impl/
> batchimport/Configuration.java
> <https://github.com/neo4j/neo4j/pull/10965#discussion_r166473791>:
>
> >          {
>              // Unable to detect amount of free memory, so rather max memory should be explicitly set
>              // in order to get best performance. However let's just go with a default of 2G in this case.
>              return gibiBytes( 2 );
>          }
>
>          double factor = percent / 100D;
> -        return round( (freePhysicalMemory - Runtime.getRuntime().maxMemory()) * factor );
> +        return round( (totalPhysicalMemory - Runtime.getRuntime().maxMemory()) * factor );
> +    }
> +
> +    public static void main( String[] args )
> +    {
> +
>      }
>
> Stray main.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/neo4j/neo4j/pull/10965#pullrequestreview-94541774>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AALbnDdtIZxYTunchstPF2jtukuWBPsQks5tSN1EgaJpZM4R7Lt8>
> .
>

2018-02-09 12:16 UTC, ragadeeshu requested changes

2018-02-09 12:16 UTC, ragadeeshu commented on yoyo
> + community/codegen/src/main/java/org/neo4j/codegen/Expression.java                                                                                     |   2 +-
This probably shouldn't be here?

2018-02-12 16:02 UTC, ragadeeshu approved these changes

2018-02-13 10:52 UTC, merged