Always attach CORS headers in REST
neo4j/neo4j pull request #11034
Opened 2018-02-16 13:04 UTC by lutovich

Previously CORS headers were only added to requests that passed auth. This made JS requests from browser unable to receive the actual error because CORS is not allowed with missing headers.

This PR moves the relevant filter to the top of the filter chain so that every response has CORS headers attached.

2018-02-16 13:10 UTC, jimwebber requested changes
I think those headers are capitalised to be a good citizen in the HTTP world. Otherwise this seems sane to me.

2018-02-16 13:10 UTC, jimwebber commented on community/server/src/main/java/org/neo4j/server/rest/web/CorsFilter.java
> +    private static final String ACCESS_CONTROL_REQUEST_METHOD = "access-control-request-method";
capitalise to Access-Control-Request-Method

2018-02-16 13:10 UTC, jimwebber commented on community/server/src/main/java/org/neo4j/server/rest/web/CorsFilter.java
> +    private static final String ACCESS_CONTROL_REQUEST_HEADERS = "access-control-request-headers";
Capitalise to Access-Control-Request-Headers

2018-02-20 16:16 UTC, ali-ince approved these changes
LGTM!

I'm aware that this filter was already part of the product as it is here, but I think it may be important to discuss the logic of setting `Access-Control-Allow-Origin` to `*`  without a way to limit the cross-origin requests originators. The same logic applies to `Access-Control-Request-Method` and `Access-Control-Allow-Methods`. WDYT?

2018-02-20 16:21 UTC, merged