Relationship properties in Kernel API
neo4j/neo4j pull request #11050
Opened 2018-02-19 15:03 UTC by pontusmelke

- Implement all property operations on relationships in the kernel API, which includes `relationshipGetProperty`, `relationshipSetProperty` and `relationshipRemoveProperty`.
- Update Core API to use kernel API for all methods in `RelationshipProxy`
- Update interpreted runtime to use kernel API for all property access on relationships (and some operations that had been overlooked in previous work)
- Update compiled runtime to use kernel API for all property access on relationships.

2018-02-20 12:23 UTC, fickludd requested changes
In general really good, well done on dragging this across all user and everywhere.

Some minor non-critical points, and there seems to be missing a locking tests for `relationshipDeleteProperty`.

2018-02-20 12:23 UTC, fickludd commented on community/kernel-api/src/test/java/org/neo4j/internal/kernel/api/RelationshipTransactionStateTestBase.java
> +    //start here
`//start here`?

2018-02-20 12:23 UTC, fickludd commented on community/kernel-api/src/test/java/org/neo4j/internal/kernel/api/ExplicitIndexCursorWritesTestBase.java
>      //TODO unignore when we support relationship creation.
Remove the TODO as well?

2018-02-20 12:23 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/core/RelationshipProxy.java
> +            throw new ConstraintViolationException( e.getMessage(), e );
This is strange, I don't think we can get constraint violation for relationships when setting a property? When removing I guess we could violate a existence constraint, but that's anyway not checked until commit. 

In general it feels like here are way more catch clauses than necessary...

2018-02-20 12:23 UTC, fickludd commented on community/cypher/interpreted-runtime/src/main/scala/org/neo4j/cypher/internal/runtime/interpreted/TransactionBoundQueryContext.scala
>        }
In the Kernel API relationshipDelete is idempotent I think, so we can remove the try-catch as well.

2018-02-20 12:23 UTC, fickludd commented on community/cypher/interpreted-runtime/src/main/scala/org/neo4j/cypher/internal/runtime/interpreted/TransactionBoundQueryContext.scala
> +        Some(fromRelationshipProxy(entityAccessor.newRelationshipProxy(id)))
Here I preferred the previous impl which cached the start/end/type of the relationship. That stuff is going to be in L1 cache anyway (given current store layout) so we might as well return it.

2018-02-20 12:23 UTC, fickludd commented on community/cypher/interpreted-runtime/src/main/scala/org/neo4j/cypher/internal/runtime/interpreted/TransactionBoundQueryContext.scala
> -        transactionalContext.statement.readOperations().relationshipVisit(id, NoopVisitor)
Now we can also remove the NoopVisitor!

2018-02-20 12:23 UTC, fickludd commented on community/cypher/interpreted-runtime/src/main/scala/org/neo4j/cypher/internal/runtime/interpreted/TransactionBoundQueryContext.scala
> +  private lazy val propertyCursor = allocateAndTracePropertyCursor()
I'm curious: does this have a measurable effect, or why did you do it?

2018-02-20 12:23 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/core/RelationshipProxy.java
> +        }
I don't think we need this catch - this is handled by the boolean return value.

2018-02-20 12:23 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/core/NodeProxy.java
> +        }
This should be handled by the `nodeDelete` return value, so we don't need this catch.

2018-02-21 13:28 UTC, pontusmelke commented on community/cypher/interpreted-runtime/src/main/scala/org/neo4j/cypher/internal/runtime/interpreted/TransactionBoundQueryContext.scala
> -        transactionalContext.statement.readOperations().relationshipVisit(id, NoopVisitor)
done

2018-02-21 18:48 UTC, fickludd approved these changes

2018-02-23 13:45 UTC, chrisvest approved these changes
Couple of comments, but overall it looks good.

2018-02-23 13:45 UTC, chrisvest commented on community/kernel-api/src/test/java/org/neo4j/internal/kernel/api/RelationshipTransactionStateTestBase.java
> +                assertEquals( property.propertyValue(), stringValue( "world" ) );
This relies on the order in which the properties comes back from the cursor. I think that's over-specifying.

2018-02-23 13:45 UTC, chrisvest commented on community/kernel-api/src/test/java/org/neo4j/internal/kernel/api/RelationshipTransactionStateTestBase.java
> +                assertEquals( property.propertyValue(), stringValue( "hello" ) );
Does this imply that the properties contained in the transaction state should always be siphoned out before the persistent state?

2018-02-23 13:45 UTC, chrisvest commented on community/kernel-api/src/test/java/org/neo4j/internal/kernel/api/RelationshipTransactionStateTestBase.java
> +    public void shouldSeeRemovedPropertyInTransaction() throws Exception
Or should _not_ see?

2018-02-23 13:45 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/kernel/impl/newapi/Operations.java
> +            //no existing value, we just add it
This comment look out of place.

2018-02-25 08:07 UTC, merged