Count store from kernel API
neo4j/neo4j pull request #11096
Opened 2018-02-25 08:19 UTC by pontusmelke

Move (or rather copy, but will be removed soon) count store operations to kernel api which allows us to get rid of all dependency on `ReadOperation` from the compiled runtime

2018-02-26 12:36 UTC, SaschaPeukert requested changes
Looks good! I only have two minor nit-picks

2018-02-26 12:36 UTC, SaschaPeukert commented on community/kernel/src/main/java/org/neo4j/kernel/impl/newapi/AllStoreHolder.java
> +                    count += counts.nodeCount( labelId, newDoubleLongRegister() ).readSecond();
Except for that ```readSecond()``` part, everything else is really good to read. Maybe renaming that method could help to better express what it does?

2018-02-26 12:36 UTC, SaschaPeukert commented on community/cypher/interpreted-runtime/src/main/scala/org/neo4j/cypher/internal/runtime/interpreted/TransactionBoundGraphStatistics.scala
> +  //TODD remove ReadOperations when schema ops are ported
Who is Todd? :-D

2018-02-26 13:37 UTC, pontusmelke commented on community/kernel/src/main/java/org/neo4j/kernel/impl/newapi/AllStoreHolder.java
> +                    count += counts.nodeCount( labelId, newDoubleLongRegister() ).readSecond();
This is the API of the underlying count store, don't want to change that API as part of this PR.

2018-02-26 13:38 UTC, pontusmelke commented on community/cypher/interpreted-runtime/src/main/scala/org/neo4j/cypher/internal/runtime/interpreted/TransactionBoundGraphStatistics.scala
> +  //TODD remove ReadOperations when schema ops are ported
oh yes TODD, I totally meant to write that :)

2018-02-27 08:20 UTC, SaschaPeukert approved these changes

2018-02-27 08:27 UTC, merged