Public static fields should also be final
neo4j/neo4j pull request #11158
Opened 2018-03-05 09:40 UTC by klaren

Also removed unnecessary boxing of booleans.

2018-03-05 11:31 UTC, chrisvest commented on community/command-line/src/main/java/org/neo4j/commandline/admin/AdminTool.java
> +    public static final String NEO4J_DEBUG = System.getenv().getOrDefault( "NEO4J_DEBUG", "" );
These are mutable for testing, and exploited in the blockdevice repo, I believe.

2018-03-05 11:33 UTC, chrisvest commented on community/command-line/src/main/java/org/neo4j/commandline/admin/AdminTool.java
> +    public static final String NEO4J_DEBUG = System.getenv().getOrDefault( "NEO4J_DEBUG", "" );
The comment just above also says so.

2018-03-05 12:06 UTC, klaren commented on community/command-line/src/main/java/org/neo4j/commandline/admin/AdminTool.java
> +    public static final String NEO4J_DEBUG = System.getenv().getOrDefault( "NEO4J_DEBUG", "" );
Well spotted. Although, why can't the affected tests instantiate `AdminTool` directly as all other tests do?

2018-03-05 12:16 UTC, chrisvest commented on community/command-line/src/main/java/org/neo4j/commandline/admin/AdminTool.java
> +    public static final String NEO4J_DEBUG = System.getenv().getOrDefault( "NEO4J_DEBUG", "" );
Maybe that wasn't possible at that time.

2018-03-06 10:20 UTC, MishaDemianenko requested changes

2018-03-06 10:20 UTC, MishaDemianenko commented on enterprise/com/src/main/java/org/neo4j/com/Client.java
> +                        Boolean.TRUE );
we should be able to just remove those true's from log messages in this and other classes that do the same thing

2018-03-06 10:20 UTC, MishaDemianenko commented on community/common/src/main/java/org/neo4j/function/Predicates.java
> +    public static final IntPredicate ALWAYS_TRUE_INT = v -> true;
please move this constant from the middle of the class to the top

2018-03-06 10:20 UTC, MishaDemianenko commented
Also, the thing that Chris mentioned if its not a problem anymore comment on top of those fields should be removed

2018-03-06 13:28 UTC, chrisvest commented
@MishaDemianenko I agree. Let's remove the comment, make those fields final, and fix up the blockdevice repo.

2018-03-06 13:57 UTC, klaren commented on community/command-line/src/main/java/org/neo4j/commandline/admin/AdminTool.java
> +    public static final String NEO4J_DEBUG = System.getenv().getOrDefault( "NEO4J_DEBUG", "" );
Should hopefully be possible now, I'll have a look at it.

2018-03-12 12:21 UTC, klaren commented
@MishaDemianenko addressed. I'm also looking into blockdevice to fix compilation errors.

2018-03-12 13:12 UTC, MishaDemianenko approved these changes

2018-03-13 13:04 UTC, merged