More changing to Kernel API for C
neo4j/neo4j pull request #11173
Opened 2018-03-06 13:36 UTC by pontusmelke

- Use Kernel API for `Node#getRelationshipTypes`
- Use Kernel API for intitalizing `RelationshipProxy`
- Use `type` everywhere instead of mixing `label` and `type`

2018-03-08 10:16 UTC, chrisvest requested changes
Please bring back set semantics of `Node.getRelationshipTypes`.

2018-03-08 10:16 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/kernel/impl/core/NodeProxy.java
> +            }
The previous implementation only returned each type once, but this one will return as many relationship types as the node has relationships.

2018-03-11 16:25 UTC, pontusmelke commented
@chrisvest It's back

2018-03-12 09:28 UTC, chrisvest approved these changes

2018-03-13 21:32 UTC, merged