Temporal indexing IV - range scans
neo4j/neo4j pull request #11181
Opened 2018-03-06 22:10 UTC by fickludd

Enable range scan functinality of all temporal index parts. 

Still missing test for some corner-cases!

Builds on other stuff, first commit is `Refactor range predicates to share base class`.

2018-03-07 21:01 UTC, fickludd commented
I know this is conflicting, but hoping to merge the underlying PR and then rebase on master. Still review-able while waiting.

2018-03-11 12:52 UTC, tinwelint requested changes
Nice simplifications with the range query refactoring!

Had a few comments. And on the testing side, what are the corner cases that are missing, and if known why are you not adding those in this PR?

2018-03-11 12:52 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/storageengine/api/txstate/ReadableTransactionState.java
>      PrimitiveLongReadableDiffSets indexUpdatesForRangeSeekByString( IndexDescriptor index,
Should this method also be removed?

2018-03-11 12:52 UTC, tinwelint commented on community/kernel-api/src/main/java/org/neo4j/internal/kernel/api/IndexQuery.java
> +            throw new IllegalArgumentException( "Cannot create GeometryRangePredicate without at specified CRS" );
`at` --> `a` ?

2018-03-11 12:52 UTC, tinwelint commented on community/kernel-api/src/main/java/org/neo4j/internal/kernel/api/IndexQuery.java
> +                if ( point.getCRS() == crs )
`==` assuming too much? Better with `.equals`?

2018-03-12 06:26 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/storageengine/api/txstate/ReadableTransactionState.java
>      PrimitiveLongReadableDiffSets indexUpdatesForRangeSeekByString( IndexDescriptor index,
Yes! Just forgot about it.

2018-03-12 06:29 UTC, fickludd commented
@tinwelint I put in the corner-case note in the description when I first created this PR, which was mostly for building. We since explored my suspected corner-cases, so that's just old stale suspicion.

2018-03-13 14:02 UTC, OliviaYtterbrink approved these changes
Just some minor points, but most of them are already fixed in the next PR

2018-03-13 14:02 UTC, OliviaYtterbrink commented on community/kernel-api/src/main/java/org/neo4j/internal/kernel/api/IndexQuery.java
> +                if ( point.getCRS().equals( crs ) )
This check is also done in `PointValue.withinRange`

2018-03-13 14:02 UTC, OliviaYtterbrink commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/schema/fusion/FusionIndexReader.java
> +            // TODO: support temporal range queries
this todo is outdated...

2018-03-13 14:02 UTC, OliviaYtterbrink commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/schema/fusion/FusionIndexReader.java
> +            // TODO: support temporal range queries
forgot to add support on this path...

2018-03-13 14:02 UTC, OliviaYtterbrink commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/schema/fusion/FusionIndexReader.java
> +        // TODO: support temporal range queries
this also missed being fixed...

2018-03-13 14:02 UTC, OliviaYtterbrink commented on community/kernel/src/main/java/org/neo4j/kernel/impl/newapi/Read.java
> +                    ValueGroup valueGroup = q.valueGroup();
do we really need to check the value group here, isn't it enough to check the `hasFullValuePrecision`?

2018-03-13 14:25 UTC, merged