Manage resource iterators explicitly
neo4j/neo4j pull request #11248
Opened 2018-03-14 08:45 UTC by andreikoval

Knowledge about iterators' inherent resources must not leak outside
relevant scope.  Responsibility of managing such resources also must be
explicit, not hidden as an implicit "instanceof" check in the totally
irrelevant part of code.

2018-03-14 13:38 UTC, burqen requested changes
Changes look good! However, we add one extra layer if wrapping to a lot of index calls. I'll start a benchmark run to see how this affect performance. Hold tight.

2018-03-15 07:11 UTC, burqen commented
Benchmarks look fine, approved!

2018-03-15 07:11 UTC, burqen submitted a review, later dismissed

2018-03-15 08:20 UTC, andreikoval commented
As discussed offline, benchmark ui was confusing and there's actually a regression. Alternative solution will be implemented.

2018-03-20 12:28 UTC, burqen approved these changes
This is so much cleaner, I really like this! Nice 👍
I'll approve this now, but please have a look at the small readability comments before merging.

2018-03-20 12:28 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/storageengine/api/txstate/ReadableRelationshipDiffSets.java
> +    RelationshipIterator augmentWithRemovals( RelationshipIterator source );
This guy is never used

2018-03-20 12:28 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/storageengine/api/txstate/ReadableRelationshipDiffSets.java
> +public interface ReadableRelationshipDiffSets<T> extends SuperReadableDiffSets<T>
Can we place `Empty` implementation at the bottom and the interesting stuff (the methods) above?

2018-03-20 12:30 UTC, burqen commented
The test failure is not related to this PR. A rebase should fix it.

2018-03-20 12:31 UTC, andreikoval commented
Cool, thanks! I'll fix those readability issues.

2018-03-21 15:01 UTC, merged