Don't make auth file globally readable
neo4j/neo4j pull request #11244
Opened 2018-03-13 20:24 UTC by jakewins

On systems with POSIX-style file permissions,
restrict permissions on auth file to `500`.

This introduces, as a side effect, a proposed
addition to FSA to set file permissions.

2018-03-13 20:24 UTC, jakewins commented
Main driver for this is the test in `FileRepositorySerializerTest`.

2018-03-27 09:50 UTC, tinwelint reviewed
I think it looks allright, although I'm not on a posix system. Perhaps someone else can take this for a spin and verify...

2018-04-03 18:38 UTC, jakewins commented
@MishaDemianenko WDYT?

2018-04-04 09:05 UTC, MishaDemianenko requested changes
It looks like desired can be achieved without introducing system dependent functionality, aslo if we introducing the possibility to set basic posix attributes we need to do the same for OS that does not support that.

2018-04-04 09:05 UTC, MishaDemianenko commented on community/io/src/main/java/org/neo4j/io/fs/DefaultFileSystemAbstraction.java
> +        Files.setPosixFilePermissions( fileName.toPath(), posixPerms );
as you mention in javadocs this will not gonna work on all supported operating systems

2018-04-04 09:05 UTC, MishaDemianenko commented on community/io/src/main/java/org/neo4j/io/fs/DelegateFileSystemAbstraction.java
> +        throw new UnsupportedOperationException( "This file system does not support file permissions." );
we should delegate to delegate file system instead since we do not know if permissions are supported there on this level

2018-04-04 09:05 UTC, MishaDemianenko commented on community/io/src/main/java/org/neo4j/io/fs/DelegateFileSystemAbstraction.java
> +        throw new UnsupportedOperationException( "This file system does not support file permissions." );
same here

2018-04-04 09:05 UTC, MishaDemianenko commented on community/io/src/main/java/org/neo4j/io/fs/FilePermission.java
> +public enum FilePermission
javadocs javadocs

2018-04-04 09:05 UTC, MishaDemianenko commented on community/security/src/main/java/org/neo4j/server/security/auth/FileRepositorySerializer.java
> +                fileSystem.setPermissions( tempFile, FilePermission.OWNER_READ, FilePermission.OWNER_WRITE );
since this is the only usage of new functionality this can be achieved by tempFile.setRedable / tempFile.setWritable method calls.

2018-04-04 09:05 UTC, MishaDemianenko commented on community/security/src/main/java/org/neo4j/server/security/auth/FileRepositorySerializer.java
> +            catch(UnsupportedOperationException e)
not really secure

2018-04-16 14:15 UTC, jakewins commented
@MishaDemianenko still need to retarget this for 3.5, but I changed approach a good bit and wanted your feedback. Now, instead of trying to surface POSIX-style `owner/group/all read/write/exec`, I replaced this with `AccessPolicy`, which tries to communicate intent, instead of specific flags. That way, the implementation can then set appropriate flags depending on the system, and we leave the door open to custom strategies.

I could have just surfaced setReadable/setWritable, but the intention here is that this would be a small beach-head towards better management of file permissions over all, so we can add more AccessPolicies over time.

2018-05-07 16:32 UTC, jakewins commented
retargeting for 3.5

2018-05-07 16:32 UTC, closed without merging