Increase timeout for DatabaseIndexIntegrationTest
neo4j/neo4j pull request #11263
Opened 2018-03-14 15:19 UTC by klaren

2018-03-19 11:29 UTC, MishaDemianenko requested changes

2018-03-19 11:29 UTC, MishaDemianenko commented on community/lucene-index/src/test/java/org/neo4j/kernel/api/impl/index/DatabaseIndexIntegrationTest.java
> +    public final VerboseTimeout timeout = VerboseTimeout.builder()
you need to include this rule into a chain of rules; also if we use this rule for timeouts we should not use separate per test timeouts

2018-03-22 10:43 UTC, MishaDemianenko commented
@klaren piu piu

2018-03-22 11:02 UTC, klaren commented
@MishaDemianenko pong pong

2018-03-22 11:10 UTC, MishaDemianenko approved these changes

2018-03-23 10:14 UTC, merged