Restore Fusion index to that of 3.3
neo4j/neo4j pull request #11275
Opened 2018-03-15 12:22 UTC by burqen

Disable
- Native string index
- Native Temporal index
- Native Spatial index

Also make Fusion index multiversionable for future adaptation.

2018-03-15 14:16 UTC, MishaDemianenko requested changes
Couple of macro comments, lets talk about those

2018-03-15 14:16 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/helpers/ArrayUtil.java
> +    public static int[] without( int[] source, int... toRemove )
please use ArrayUtils.removeAll instead

2018-03-15 14:16 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/schema/fusion/FusionIndexAccessor.java
> +                .filter( notNull() )
i think filtering out and guarding against nulls everywhere is a source of errors, what if instead we will have those instance as an empty instance of some sort?

2018-03-15 14:16 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/schema/fusion/FusionSelector00.java
> +public class FusionSelector00 implements FusionIndexProvider.Selector
java docs are not here at all right now (in all of the selectors)

2018-03-15 15:59 UTC, burqen commented
@MishaDemianenko Sorry for force pushing the fixes, but it was the easiest way to revert all of the null checks. This looks a lot better I think. Thanks for the feedback!

2018-03-15 16:41 UTC, MishaDemianenko requested changes
Thats indeed much better but still have some questions

2018-03-15 16:41 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/schema/fusion/FusionIndexBase.java
> +    static void validateSelectorInstances( Object[] instances, int... notNullIndex )
thats not really notNullIndex now

2018-03-15 16:41 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/schema/fusion/FusionIndexReader.java
> +        if ( instance != null )
thats no longer so right?

2018-03-15 16:41 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/schema/fusion/FusionIndexReader.java
> +        if ( instance != null )
and here?

2018-03-15 16:41 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/schema/fusion/FusionSelector00.java
> + * todo If spatial and temporal will live together with lucene-1.x, update this selector. Otherwise, remove it.
temporal

2018-03-15 17:42 UTC, MishaDemianenko approved these changes

2018-03-16 09:45 UTC, tinwelint commented
Closing and reopening when development has gotten further.

2018-03-16 09:45 UTC, closed without merging