Adapt temporal to spec changes
neo4j/neo4j pull request #11288
Opened 2018-03-16 10:34 UTC by sherfert

This PR encapsulates three small changes in the spec that need to be reflected in the implementation.
For once commits are nicely split and I recommend a commit-by-commit review.

2018-03-16 12:22 UTC, Lojjs requested changes
The changes seems to be fine and agree with the CIP but some test comments. Some unclear blacklists removals and one overlooked test. You seem to have some test failures due to changed accessors also, something you forgot to remove? And you have checkstyle error

2018-03-16 12:22 UTC, Lojjs commented on enterprise/cypher/acceptance-spec-suite/src/test/resources/blacklists/compatibility-23.txt
> -Feature "DurationBetweenAcceptance": Scenario "Should compute duration between two temporals in months"
The tests for months and days should maybe still be blacklisted?

2018-03-16 12:22 UTC, Lojjs commented on enterprise/cypher/acceptance-spec-suite/src/test/resources/blacklists/cost-compiled.txt
> -Feature "DurationBetweenAcceptance": Scenario "Should compute duration between two temporals in months"
The tests for months and days should maybe still be blacklisted?

2018-03-16 12:22 UTC, Lojjs commented on enterprise/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/TemporalAcceptanceTest.scala
> +      "timezone", "offset", "offsetMinutes", "epochSeconds", "epochMillis",
You can add `epochSecond` and `epochMillis` to the `time` test also. I think that was overlooked before.

2018-03-19 08:09 UTC, sherfert commented on enterprise/cypher/acceptance-spec-suite/src/test/resources/blacklists/compatibility-23.txt
> -Feature "DurationBetweenAcceptance": Scenario "Should compute duration between two temporals in months"
I don't know why they started working all of a sudden. But if I blacklist them, it fails (logically). Weird.

2018-03-19 08:19 UTC, Lojjs approved these changes

2018-03-19 12:40 UTC, merged