Allow import without diagnostic info to be closed
neo4j/neo4j pull request #11284
Opened 2018-03-15 17:42 UTC by MishaDemianenko

2018-03-15 19:02 UTC, tinwelint requested changes
A good fix, just wondering about the term used there...

2018-03-15 19:02 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/ImportLogic.java
> +        String additionalInformation = Objects.toString( state, "Data diagnostics is not available." );
The term `diagnostics` has more of a medical/repair/investigation meaning, hasn't it. `Data statistics` may look better imho.

2018-03-15 19:16 UTC, MishaDemianenko commented
@tinwelint updated

2018-03-16 09:45 UTC, tinwelint approved these changes

2018-03-16 10:14 UTC, merged