Remove causeless direct byte buffers usages.
neo4j/neo4j pull request #11293
Opened 2018-03-16 19:18 UTC by MishaDemianenko

Replace usages of direct byte buffers with their on heap twin.

2018-03-17 11:08 UTC, chrisvest commented on community/io/src/test/java/org/neo4j/io/pagecache/PageCacheTest.java
> +        ByteBuffer buffer = ByteBuffer.allocate( filePageSize );
No, these three tests are explicitly about copying to/from _direct_ byte buffers.

2018-03-17 11:08 UTC, chrisvest commented on enterprise/causal-clustering/src/main/java/org/neo4j/causalclustering/catchup/storecopy/FileSender.java
> +        this.byteBuffer = ByteBuffer.allocate( MAX_SIZE );
Might this not cause extra copying of the buffer contents when transferring data between network and storage?

2018-03-17 11:08 UTC, chrisvest commented on enterprise/com/src/main/java/org/neo4j/com/storecopy/StoreCopyServer.java
> +                ByteBuffer temporaryBuffer = ByteBuffer.allocate( (int) ByteUnit.mebiBytes( 1 ) );
Same deal as with `FileSender`.

2018-03-19 17:44 UTC, chrisvest requested changes

2018-03-19 17:44 UTC, chrisvest commented on community/io/src/test/java/org/neo4j/io/pagecache/PageCacheTest.java
> +        ByteBuffer buffer = ByteBuffer.allocate( filePageSize );
Also here.

2018-03-19 17:44 UTC, chrisvest commented on community/io/src/test/java/org/neo4j/io/pagecache/PageCacheTest.java
> +        ByteBuffer buf = ByteBuffer.allocate( filePageSize ).asReadOnlyBuffer();
And here.

2018-03-20 10:43 UTC, MishaDemianenko commented
@chrisvest  Since i can't tell based on any measurements that its not the case (since we do not have any so far) i will agree that using direct byte buffers for file/network read/write should be faster and will revert changes in those two places. Let it be the fight for later when will have some time to write benchmarks for those 2 places.

2018-03-20 10:50 UTC, chrisvest approved these changes

2018-03-20 14:24 UTC, merged