All version of cypher use Kernel API
neo4j/neo4j pull request #11291
Opened 2018-03-16 13:57 UTC by pontusmelke

Update all versions of Cypher to use the Kernel API. 

In the process some new stuff was added to the Kernel API:
- `nodeDetachDelete`
- `indexSize`
- `indexUniqueValuesSelectivity`
- methods for listing explicit indexes

Also remove some unused stuff but I am guessing there is more to delete.

2018-03-19 14:47 UTC, fickludd requested changes
This seems mostly correct to me, although I could quite keep concentrated though all the `QueryContext`s. Some things to fix, but mostly it feels very relieving to start removing code.

2018-03-19 14:47 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/newapi/Operations.java
> +                    count.increment();
If we are to keep the previous semantic, we should only increment `count` if `relationshipDelete` returns true.

2018-03-19 14:47 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/newapi/TwoPhaseNodeForRelationshipLocking.java
> +                    RelationshipSelections.allCursor( transaction.cursors(), nodes, null );
We could alternatively use a regular `RelationshipTraversalCursor` here, don't know what is preferable.

2018-03-19 14:47 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/newapi/TwoPhaseNodeForRelationshipLocking.java
> +                    RelationshipSelections.allCursor( transaction.cursors(), nodes, null );
_Actually_, I see now that we have been doing a lot of work twice here. Currently we traverse all relationships twice. But when we traverse all relationships the first time we could just collect the ids in a list. Then we lock. Now we only have to check that the first relationship is the same as before locking - if it is: delete all rels in the list, otherwise: start over.

2018-03-19 14:47 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/newapi/TwoPhaseNodeForRelationshipLocking.java
> +                    RelationshipSelections.allCursor( transaction.cursors(), nodes, null );
We don't have to change that now, I just had to note it down so we can cardify if you think this observation is correct.

2018-03-19 14:47 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/newapi/AllStoreHolder.java
> +        return explicitIndexStore.getAllRelationshipIndexNames();
Should probably have a `ktx.assertOpen` here for consistency.

2018-03-19 14:47 UTC, fickludd commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/spi/v2_3/TransactionBoundPlanContext.scala
> +    getOnlineIndex(tc.schemaRead.index(labelId, propertyKeyId))
This is so much nicer than before!

2018-03-19 14:47 UTC, fickludd commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/spi/v2_3/TransactionBoundQueryContext.scala
> +    if (!cursor.next())Iterator.empty
missing space

2018-03-19 14:47 UTC, fickludd commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/spi/v2_3/TransactionBoundQueryContext.scala
> +         IndexQuery.exact(index.labelId, index.propertyId))
Here we should query for the `value` rather than the propertyId :)

2018-03-19 14:47 UTC, fickludd commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/spi/v2_3/TransactionBoundQueryContext.scala
> +  def nodeGetDegree(node: Long, dir: SemanticDirection): Int ={
missing space (looks like a sad emoji?)

2018-03-19 14:47 UTC, fickludd commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/spi/v2_3/TransactionBoundQueryContext.scala
>          case _: api.exceptions.EntityNotFoundException => // node has been deleted by another transaction, oh well...
Do we really throw from `delete`? I think it should be idempotent. And same for `detachDelete` below.

2018-03-19 14:47 UTC, fickludd commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/spi/v2_3/TransactionBoundQueryContext.scala
>          case _: api.exceptions.EntityNotFoundException => // node has been deleted by another transaction, oh well...
Idempotent, no need for try-catch.

2018-03-19 14:47 UTC, fickludd commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/spi/v2_3/TransactionBoundQueryContext.scala
> +    pathFinder.findAllPaths(left, right).iterator().asScala
Whoopsie?

2018-03-19 14:47 UTC, fickludd commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/spi/v3_1/TransactionBoundQueryContext.scala
> +         IndexQuery.exact(index.labelId, index.propertyId))
`IndexQuery.exact` should get `propertyId` and `value` instead.

2018-03-19 14:47 UTC, fickludd commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/spi/v3_1/TransactionBoundQueryContext.scala
> +  override def nodeIsDense(node: Long): Boolean ={
spaace!

2018-03-19 14:47 UTC, fickludd commented on community/cypher/interpreted-runtime/src/main/scala/org/neo4j/cypher/internal/runtime/interpreted/TransactionBoundPlanContext.scala
> +      .filterNot(_.isUnique)
This should be `.filter(_.isUnique)`

2018-03-19 14:47 UTC, fickludd commented on community/cypher/interpreted-runtime/src/main/scala/org/neo4j/cypher/internal/runtime/interpreted/BeansAPIRelationshipIterator.scala
> -class BeansAPIRelationshipIterator(relationships: RelationshipIterator,
Yey, I didn't like this class.

2018-03-19 14:47 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/newapi/TwoPhaseNodeForRelationshipLocking.java
> +                throw new EntityNotFoundException( EntityType.NODE, nodeId );
Should we do this, or maybe `detachDelete` should be idempotent?

2018-03-19 14:47 UTC, fickludd commented on community/cypher/interpreted-runtime/src/main/scala/org/neo4j/cypher/internal/runtime/interpreted/TransactionBoundQueryContext.scala
> +    val predicates = indexReference.properties.zip(queries).map(p => IndexQuery.exact(p._1, p._2.value()))
I don't understand this line... how is `predicates` different from `queries`?

2018-03-20 07:56 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/newapi/DefaultRelationshipExplicitIndexCursor.java
> +        read.singleRelationship( reference, scanCursor );
Oh, so we don't keep the type, start-  and end-node information in the explicit relationship index - only the id?

2018-03-20 20:32 UTC, pontusmelke commented
@fickludd I think I've fixed all your concerns

2018-03-21 09:39 UTC, fickludd commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/spi/v2_3/TransactionBoundQueryContext.scala
> +          if (cursor.next() && reads().nodeExists(cursor.nodeReference())) proxySpi.newNodeProxy(cursor.nodeReference())
Is this implementation really sound? If there are 3 entries in the index and the middle one is deleted, we will only return the first one, while I argue that we should return the first and the last.

2018-03-21 15:37 UTC, fickludd approved these changes

2018-03-21 20:17 UTC, merged