Fixed getExecutionPlanDescription on compiled results
neo4j/neo4j pull request #11332
Opened 2018-03-21 15:32 UTC by SaschaPeukert

2018-03-21 16:23 UTC, sherfert commented on enterprise/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/ExecutionResultAcceptanceTest.scala
> +    Assert.assertEquals(description1, description2)
Why are we using JUnit asserts in scala?

2018-03-23 13:40 UTC, pontusmelke requested changes
Just some small things

2018-03-23 13:40 UTC, pontusmelke commented on enterprise/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/ExecutionResultAcceptanceTest.scala
> +    assert(description1.equals(description2))
We usually prefer

```
description1 should equal(description2)
```

2018-03-23 13:40 UTC, pontusmelke commented on enterprise/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/ExecutionResultAcceptanceTest.scala
> +    assert(description1.equals(description2))
same here use `a should equal(b)` instead

2018-03-23 13:40 UTC, pontusmelke commented on enterprise/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/ExecutionResultAcceptanceTest.scala
> +      assert("empty iterator".equals(result.toString)) // don't really care for the assertion, just consume the results
`result.hasNext should be false`

2018-03-28 13:20 UTC, merged