Limit number of retries when file channels closed by interruption
neo4j/neo4j pull request #11359
Opened 2018-03-22 15:59 UTC by andreikoval

https://trello.com/c/RCfC8KUn/3524-stackoverflowerror-in-jmh-on-database-shutdown

2018-04-03 10:02 UTC, chrisvest requested changes
Call `tryReopen` before throwing the exception, and throw a sensible variant of `IOException` instead of `UncheckedIOException`.

2018-04-03 10:19 UTC, chrisvest commented
@andreikoval As a last-ditch approach, we can let the `FilePageSwapperFactory.open` method also take a `JobScheduler`. Then, if a `PageSwapper` call gets interrupted too much, it can make one final attempt in a new separate thread started by the `JobScheduler`, and use uninterruptible waiting for its completion.

Expensive as sin, but that's apparently the music we have to face when writing failure resilient code that uses `java.nio`.

2018-04-03 12:01 UTC, andreikoval commented
I'm afraid that using `JobScheduler` or anything else in this case is just like beating a dead horse.

2018-04-04 15:45 UTC, chrisvest approved these changes

2018-04-04 19:43 UTC, merged