Fixes a CSV trim issue with fields containing only whitespace
neo4j/neo4j pull request #11383
Opened 2018-03-26 12:02 UTC by tinwelint

This could result in StringIndexOutOfBounds with negative values
for some fields containing nothing but whitespace characters.

2018-03-27 07:50 UTC, tinwelint commented
The failing test has failed lots of times before, so I can't see it being caused by these changes.

2018-03-27 11:28 UTC, ragadeeshu requested changes

2018-03-27 11:28 UTC, ragadeeshu commented on community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java
> +    private int rtrim()
This whole method could use some more comments. There are some, but for the most part, especially with the new addition, it is black magic.

2018-03-27 17:31 UTC, tinwelint commented
Added javadoc now to that method, please take a look

2018-03-28 07:59 UTC, ragadeeshu approved these changes

2018-03-28 08:39 UTC, andreikoval commented on community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java
> +        while ( index - 1 > seekStartPos && isWhitespace( buffer[index - 1 /*bufferPos has advanced*/ - 1 /*don't check the last read char (delim or EOF)*/] ) )
What about other space characters, like non-breaking space, tabs, etc?

2018-03-28 10:45 UTC, tinwelint commented on community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java
> +        while ( index - 1 > seekStartPos && isWhitespace( buffer[index - 1 /*bufferPos has advanced*/ - 1 /*don't check the last read char (delim or EOF)*/] ) )
Yeah, perhaps use Character#isWhitespace() instead. This method was introduced along with the previous fix which was released in Jan or so... so I'd say changing this should be OK and more of a fix than changing behaviour.

2018-03-29 08:24 UTC, tinwelint commented on community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java
> +        while ( index - 1 > seekStartPos && isWhitespace( buffer[index - 1 /*bufferPos has advanced*/ - 1 /*don't check the last read char (delim or EOF)*/] ) )
@andreikoval How about now?

2018-03-29 11:30 UTC, andreikoval commented on community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java
> +        while ( index - 1 > seekStartPos && isWhitespace( buffer[index - 1 /*bufferPos has advanced*/ - 1 /*don't check the last read char (delim or EOF)*/] ) )
Yep, I guess that is because `Character.isWhitespace()` includes line breaking spaces as well.

2018-03-30 08:52 UTC, tinwelint commented on community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java
> +        while ( index - 1 > seekStartPos && isWhitespace( buffer[index - 1 /*bufferPos has advanced*/ - 1 /*don't check the last read char (delim or EOF)*/] ) )
It was a test issue, really. Have a look now

2018-03-31 09:46 UTC, merged