Added other valid values for backup protocol flag
neo4j/neo4j pull request #11452
Opened 2018-04-04 08:23 UTC by phughk

Added example values for online backup client protocol flag

2018-04-04 10:16 UTC, martinfurmanski approved these changes

2018-04-12 13:31 UTC, praveenag requested changes

2018-04-12 13:31 UTC, praveenag commented on enterprise/backup/src/main/java/org/neo4j/backup/impl/OnlineBackupContextBuilder.java
> +                String.join( "|", Stream.of( SelectedBackupProtocol.values() ).map( SelectedBackupProtocol::getName ).sorted().collect( Collectors.toList() ) );
Could use [Collectors#joining](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#joining--) instead.

2018-04-12 13:31 UTC, praveenag commented on enterprise/backup/src/main/java/org/neo4j/backup/impl/SelectedBackupProtocol.java
> +    LEGACY( "common" ),
If we are calling it `common` why not make the enum to `Common` instead.

2018-04-12 13:31 UTC, praveenag commented on enterprise/backup/src/test/java/org/neo4j/backup/impl/BackupHelpOutput.java
> +        lines.add( "  --protocol=<any|catchup|common>          Preferred protocol to use for" );
Could this instead say `Preferred backup protocol`

2018-04-12 13:31 UTC, praveenag commented on enterprise/backup/src/test/java/org/neo4j/backup/impl/OnlineBackupCommandCcIT.java
> +                        "--proto=common") );
Shouldn't this say `--protocol` instead of `--proto`

2018-04-13 10:22 UTC, praveenag approved these changes

2018-04-16 07:25 UTC, merged