Skip index verification for not completed constraints during the consistency check
neo4j/neo4j pull request #11459
Opened 2018-04-04 16:53 UTC by MishaDemianenko

Constraints create using separate transactions and separate commands.
It can be the case that index command was already executed and the index is there
while actual constraint transaction is not yet/longer there.
This PR updates only consistency checker to ignore such indexes and
only warn about those instead of claim about store inconsistency.

2018-04-05 10:02 UTC, tinwelint requested changes
Looks good, just that inverted boolean method, that's all

2018-04-05 10:02 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/kernel/impl/store/record/IndexRule.java
> +    public boolean isNotValidatedIndexConstraint()
As with all boolean methods it's way nicer if they are positive in nature... easier to grok when read in conditions.

2018-04-05 10:14 UTC, MishaDemianenko commented
@tinwelint updated

2018-04-06 09:22 UTC, MishaDemianenko commented
@tinwelint ping ping

2018-04-07 19:51 UTC, tinwelint approved these changes
it still has a negative tone to it, i.e. `without`. It wasn't the name in particular, more that it should be flipped, true/false wise. But I won't bike-shed this, it pretty enough!

2018-04-08 10:38 UTC, merged