IPv6 support in backup client
neo4j/neo4j pull request #11615
Opened 2018-04-19 15:19 UTC by phughk

2018-05-24 14:13 UTC, martinfurmanski requested changes
A few questions regarding the content of the PR. Also missing an integration test for the stated functionality of running a backup using IPv6.

We already have some form of IPv6 support in the product afaik, see for example ClusterIpFamilyIT, so parsing of addresses should already exist. Can you reuse that instead?

2018-05-24 14:13 UTC, martinfurmanski commented on community/kernel/src/test/java/org/neo4j/kernel/impl/util/ConvertersTest.java
> +                Pair.of( "[1::2]:3:4", new OptionalHostnamePort( "1::2", 3, 4 ) ) );
Where does this port-range format as specified with a comma in-between come from? In the past I've only seen things like `1.2.3.4:6000-6010`.

2018-05-24 14:13 UTC, martinfurmanski commented on community/kernel/src/test/java/org/neo4j/kernel/impl/util/ConvertersTest.java
> +                Pair.of( "::/0", new OptionalHostnamePort( "::/0", null, null ) ),
Why are we testing address block notation? Where does the need for this come from?

2018-05-30 10:11 UTC, phughk commented
The existing ipv6 processing has been reused by calling HostnamePort from OptionalHostnamePort and then doing some processing on brackets.

2018-06-04 16:30 UTC, closed without merging