Increase the swapper id limit.
neo4j/neo4j pull request #11668
Opened 2018-04-27 12:36 UTC by chrisvest

This means that the page cache can now have roughly 2 million files mapped, instead of the 32.768 it could handle before.

This is important as we have more and more indexes that are backed by the page cache.

I'm not sure if we should target this to 3.4 or 3.4.1.

2018-04-27 18:26 UTC, InverseFalcon commented
Is there any chance to get this in for the next 3.3.x patch?

2018-05-03 16:40 UTC, MishaDemianenko approved these changes

2018-05-08 15:02 UTC, klaren requested changes
A few comments, otherwise this looks good!

2018-05-08 15:02 UTC, klaren commented on community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/PageList.java
> + * <tr><td>2</td><td>Page swapper id.</td></tr>
This should be updated to match the new layout, changing the first column to `Bits` would make things more clear.

2018-05-08 15:02 UTC, klaren commented on community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/PageList.java
> +    private static final long MASK_SHIFTED_SWAPPER_ID = 0b1_11111_11111_11111_11111;
Lot's of mixing between hex and binary, maybe we could stick with `(1L << x) - 1` so it's easy to know how many bits the mask contains without counting them.

2018-05-08 15:02 UTC, klaren commented on community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/PageList.java
> +    // The last word-line, with the file page id, swapper id, and usage counter, is called the page binding word.
What do you think about having `OFFSET_BINDING_WORD` or similar as a constant with a comment about what it contains instead of the other way around?

2018-05-09 11:23 UTC, chrisvest commented
@klaren Fixed.

2018-05-09 14:17 UTC, klaren approved these changes
:+1:

2018-05-16 12:16 UTC, merged