Increase swapper id limit and fix a MemoryManager bug around alignment handling.
neo4j/neo4j pull request #11674
Opened 2018-04-30 11:44 UTC by chrisvest

This is back-porting fixes from the #11668 PR, and should be null-merged into 3.4.

2018-05-03 16:56 UTC, MishaDemianenko requested changes
couple of minor comments

2018-05-03 16:56 UTC, MishaDemianenko commented on community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/PageList.java
> +        return (byte) (UnsafeUtil.getLongVolatile( offFilePageId( pageRef ) ) & 0x07);
would be really nice to get constant for mister 0x07

2018-05-03 16:56 UTC, MishaDemianenko commented on community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/PageList.java
> +            UnsafeUtil.compareAndSwapLong( null, address, v, (v & 0xFFFFFFFF_FFFFFFF8L) + usage );
and for mister xFFFFFFFF_FFFFFFF8L

2018-05-03 16:56 UTC, MishaDemianenko commented on community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/PageList.java
> +        long filePageId = UnsafeUtil.getLong( offFilePageId( pageRef ) ) >>> 24;
and for mister 24

2018-05-07 10:13 UTC, chrisvest commented
@MishaDemianenko 👍

2018-05-07 10:18 UTC, MishaDemianenko approved these changes

2018-05-16 13:31 UTC, merged