3.4 Change stepdown updates to be handled in RobustJobScheduler
neo4j/neo4j pull request #11691
Opened 2018-05-02 10:48 UTC by hugofirth

Potential fix for panic being caused by direct Raft<->Hazelcast communication. Updated stepdown handler to set local state on each core, which then gets read on each `refreshRoles` call inside `RobustJobScheduler`.

2018-05-02 14:22 UTC, andrewkerr9000 commented on enterprise/causal-clustering/src/main/java/org/neo4j/causalclustering/discovery/HazelcastCoreTopologyService.java
> +
As discussed, probably need to set stepDownInfo to Optional.empty.

2018-05-02 14:24 UTC, andrewkerr9000 commented on enterprise/causal-clustering/src/main/java/org/neo4j/causalclustering/discovery/HazelcastCoreTopologyService.java
> +
If it is unnecessary to casLeaders twice then
```
if( stepDownInfo.isPresent() )
{
...
}
else if ( leaderInfo.memberId() != null && ... )
{
...
}
```

2018-05-03 18:56 UTC, martinfurmanski requested changes

2018-05-03 18:56 UTC, martinfurmanski commented on enterprise/causal-clustering/src/main/java/org/neo4j/causalclustering/discovery/HazelcastCoreTopologyService.java
>          if ( leaderInfo.memberId() != null && leaderInfo.memberId().equals( myself ) )
It would be prudent to read leaderInfo into a local variable before access.

2018-05-03 18:56 UTC, martinfurmanski commented on enterprise/causal-clustering/src/main/java/org/neo4j/causalclustering/discovery/HazelcastCoreTopologyService.java
> +        stepDownInfo.ifPresent( s -> HazelcastClusterTopology.casLeaders( hazelcastInstance, s, localDBName ) );
Same for stepDownInfo.

2018-05-03 18:56 UTC, martinfurmanski commented on enterprise/causal-clustering/src/main/java/org/neo4j/causalclustering/discovery/HazelcastCoreTopologyService.java
> +
If stepDownInfo is cleared, then you have to use AtomicReference and CAS in the clearing.

2018-05-04 11:33 UTC, andrewkerr9000 commented
#11717 includes feedback comments

2018-05-07 10:24 UTC, martinfurmanski commented
Replaced by #11717

2018-05-07 10:24 UTC, closed without merging