Test module for random Value generation
neo4j/neo4j pull request #11727
Opened 2018-05-07 10:02 UTC by pontusmelke

https://github.com/neo4j/neo4j/pull/11707

2018-05-07 10:10 UTC, fickludd approved these changes

2018-05-07 10:10 UTC, fickludd commented on community/random-values/src/main/java/org/neo4j/values/Generator.java
> +     * Return a pseudorandom normally distributed float
In what range?

2018-05-07 12:03 UTC, tinwelint requested changes
I'm going to put my "Request changes" mark on this too, just as the last one just for the record. It's mostly about the RandomValues' relationship with RandomRule, which we talked about offline.

2018-05-08 06:48 UTC, pontusmelke commented
@tinwelint I have changed so that `RandomRule` and `RandomValues` get along better now.

@tinwelint @fickludd @SaschaPeukert I think I have adressed all of your comments from the old PR.

2018-05-08 07:36 UTC, tinwelint approved these changes
Looks awesome to me! Only had this comment that random-values dependencies should have scope=test, shouldn't they?

2018-05-08 07:36 UTC, tinwelint commented on community/index/pom.xml
> +      <version>${project.version}</version>
this is a test dependency, no?

2018-05-08 07:49 UTC, pontusmelke commented on community/index/pom.xml
> +      <version>${project.version}</version>
yes, nice catch!

2018-05-08 10:24 UTC, fickludd approved these changes
Awesome, let's merge this.

2018-05-11 18:35 UTC, merged