Clearer separation between kernel and storage
neo4j/neo4j pull request #11733
Opened 2018-05-07 15:05 UTC by tinwelint

This is a set of commits that moves towards more clearly defining
the cut-off point between kernel and storage.

Historically StorageEngine was introduced to act as a surface towards
kernel, something that would not have any physical implementation
details exposed. Kernel would use it and sprinkle in transaction
functionality around it. Over time and especially with the introduction
of the new kernel API and the work that ensued implementing it
the separation between kernel and storage got blurred and details
about the current record storage leaked through the storage surface.

This work removes those introduced leaks, improves on naming,
simplifies the StorageEngine surface, moves classes to where they belong 
and makes a bunch of classes and methods package-private, now that
they're in their correct places. All this by basically only moving 
existing code around.

Future changes that this PR enables, e.g:
- Reducing StorageEngine surface, since in some ways it still exposes
  duplicate ways of doing things, one for the old kernel API and another
  for the new one.
- Moving out StorageEngine from the kernel component
- Moving out RecordStorageEngine from the kernel component

2018-05-10 20:20 UTC, fickludd requested changes
I like a lot of what's going on here, but I don't think we should merge `StorageReader exposes new read interfaces` as it stands. Moving transaction state (and security concerns) into the store is a step in the wrong direction ihmo, and that commit will completely trash the git history. Also with the diffs being so complicated for that commit, I have no clue whether something was changed apart from moving methods around.

I think we should pick some other refactorings from that commit, and redo as smaller commits.

2018-05-10 20:20 UTC, fickludd commented on community/kernel/src/test/java/org/neo4j/kernel/impl/newapi/MockStore.java
> -public class MockStore extends Read implements TestRule
Wow... good riddance.

2018-05-10 20:58 UTC, tinwelint commented
@fickludd the thing here is that doing that change allows for tremendous removals of the old storage API (upcoming commit). I think doing the changes in this order is the best I can envision, because once the storage engine API has been reduced and aligned with the kernel API it's much easier to do other things.

Is your concern that it's too big, if so I could try to break it down.

2018-05-10 21:01 UTC, MishaDemianenko commented
please wait with that i started my walk over it....

2018-05-11 09:44 UTC, MishaDemianenko requested changes
In general, i kind of share Johan views that there are some good parts in this PR but i also do not think we should merge those interfaces in a current way.
 Also couple of  minor comments here and there

2018-05-11 09:44 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/KernelStatement.java
> +        this.storageReader.beginTransaction( transaction );
please rename it to initialise of some sort instead

2018-05-11 09:44 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/KernelStatement.java
> +            storageReader.beginStatement();
also looks like there is still a notion of statement in one way or another, should we remove this as well?

2018-05-11 09:44 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/KernelTransactionImplementation.java
> +        // TODO hmm shouldn't locks be an aspect of WRITE?
todo

2018-05-11 09:44 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/newapi/ReadOperations.java
> + * This class is designed to be generic, even for different {@link StorageEngine}.
javadoc should not describe non existing functionality

2018-05-11 09:44 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/newapi/ReadOperations.java
> + * In some golden future it would be very nice to make changes such that storage wouldn't need to care about transaction state.
and should not describe desires or future

2018-05-11 09:44 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/storageengine/impl/recordstorage/StoreNodeRelationshipCursor.java
> + * TODO this is public due to an out-of-context usage in BatchInserter
todo

2018-05-11 09:44 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/storageengine/impl/recordstorage/StorePropertyCursor.java
> + * TODO this is public due to an out-of-context usage in BatchInserter
todo

2018-05-11 09:44 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/storageengine/api/StorageEngine.java
> +     * The returned instance is intended to be used by one transaction at a time, although can and should be reused
This interface should not describe behavior of other components that have nothing to do with it

2018-05-11 09:44 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/storageengine/api/StorageReader.java
> +    void beginTransaction( TransactionalDependencies dependencies );
it looks really strange to see transaction/statement related methods in a StorageReader interface i do not think they should be here

2018-05-11 09:44 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/storageengine/api/StorageReader.java
> +public interface StorageReader extends AutoCloseable, Read, ExplicitIndexRead, SchemaRead, CursorFactory
also since its a cleanup its strange to see tons of methods that are never used that are still alive

2018-05-11 09:44 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/storageengine/api/TransactionalDependencies.java
> +public interface TransactionalDependencies extends TxStateHolder, AssertOpen
if this is only transactional dependencies why its implementing AssertOpen?

2018-05-11 09:44 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/storageengine/api/StorageReader.java
> +public interface StorageReader extends AutoCloseable, Read, ExplicitIndexRead, SchemaRead, CursorFactory
also i think its a step in the wrong direction to create a monster interface like StorageReader that will gonna do everything. This was exactly the driver for a couple of previous refactorings to split that work into separate functionality isolated classes which i think is a good thing, this brings us back.

2018-05-15 09:51 UTC, tinwelint commented
Too big, will be split some

2018-05-15 09:51 UTC, closed without merging