Revert "Check root cause for errors"
neo4j/neo4j pull request #11749
Opened 2018-05-09 08:26 UTC by henriknyman

This reverts commit f38aa5b488e72c39144c3658d63e932f53f7fa7f.

The reverted commit changed external behaviour in a way that information
from exceptions thrown from procedures or user-defined functions was lost.

2018-05-16 07:23 UTC, pontusmelke requested changes
Looks good, just a question regarding the error message

2018-05-16 07:23 UTC, pontusmelke commented on enterprise/security/src/test/java/org/neo4j/server/security/enterprise/auth/ProcedureInteractionTestBase.java
> +    static final String PROCEDURE_TIMEOUT_ERROR = "Procedure got: Transaction guard check failed";
Isn't this a slightly breaking change?

2018-05-17 17:50 UTC, henriknyman commented on enterprise/security/src/test/java/org/neo4j/server/security/enterprise/auth/ProcedureInteractionTestBase.java
> +    static final String PROCEDURE_TIMEOUT_ERROR = "Procedure got: Transaction guard check failed";
This is what was there before, so it is more like the result of fixing(/un-breaking) a breaking change by reverting it.

2018-05-18 11:21 UTC, pontusmelke commented on enterprise/security/src/test/java/org/neo4j/server/security/enterprise/auth/ProcedureInteractionTestBase.java
> +    static final String PROCEDURE_TIMEOUT_ERROR = "Procedure got: Transaction guard check failed";
👍

2018-05-18 11:21 UTC, pontusmelke approved these changes

2018-05-18 17:19 UTC, merged