Make buffer size configurable for `LOAD CSV`
neo4j/neo4j pull request #11801
Opened 2018-05-17 10:29 UTC by pontusmelke

If csv-file contains huge fields we will overflow the internal buffer and  throw an error without users able to do much. This PR adds a db configuration - `dbms.import.csv.buffer_size` - that allows the internal buffer to be increased.
Fixes #11687

changelog: Add db-setting: `dbms.import.csv.buffer_size` allowing for increasing the internal buffer in order to handle csv-files with huge fields.

2018-05-18 11:14 UTC, fickludd approved these changes
I think this solution is fine for a maintenance release, but in `3.5` I think we should rearchitect csv configuration to no be part of the operators, but rather live in `QueryState` or something. Or it should be handled directly by the csv loader so Cypher didn't need to know about this.

2018-05-18 11:22 UTC, tinwelint requested changes

2018-05-18 11:22 UTC, tinwelint commented on community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java
> +                            "no new-line characters. If you are running a `LOAD CSV query it may also be possible that " +
It's a bit of a hack to include this information in a component way below where LOAD CSV and that configuration option lives. It would be better to catch and repurpose this specific exception higher up, wouldn't it? You could introduce a specific subclass of IllegalStateException for this purpose, in the csv component and catch it in LOAD CSV land and add this piece of messaging to it.

2018-05-18 12:56 UTC, pontusmelke commented on community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java
> +                            "no new-line characters. If you are running a `LOAD CSV query it may also be possible that " +
I agree but maybe we shouldn't change the error message at all in a maintenance release?

2018-05-20 19:52 UTC, pontusmelke commented
Come to think about it I think the grown up thing to do is not to change the error message in a maintenance release. @tinwelint @fickludd wdyt?

2018-05-22 07:42 UTC, pontusmelke commented
@tinwelint you are still in `requested changes` mode, did I miss something?

2018-05-25 09:51 UTC, tinwelint approved these changes

2018-05-25 09:56 UTC, merged

2018-08-16 10:47 UTC, SageAgastya commented
Hi,
I'm facing this error on 3.1 neo4j community edition.
Is the setting `dbms.import.csv.buffer_size` available in 3.1?
Otherwise, Could you suggest me a solution to workaround on 3.1?

Cheers!
Phaneendra