3.5 use new runtime interface
neo4j/neo4j pull request #11856
Opened 2018-05-24 16:11 UTC by alexaverbuch

Builds on https://github.com/neo4j/neo4j/pull/11846

2018-05-28 21:27 UTC, henriknyman requested changes

2018-05-28 21:27 UTC, henriknyman commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/TemporaryRuntime.scala
> +  def googldiblopp(logicalPlan: LogicalPlanState, context: CONTEXT): ExecutionPlan
This is not a very descriptive name :)

2018-05-28 21:27 UTC, henriknyman commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/TemporaryRuntime.scala
> +trait TemporaryRuntime[-CONTEXT <: CommunityRuntimeContext] {
What does `Temporary` mean here?

2018-05-28 21:27 UTC, henriknyman commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/CompiledRuntime.scala
> +import org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.{Provider, ExecutionPlan => ExecutionPlan_V35}
Is this import rename necessary? If it is we may want to follow the existing convention of `v3_5` instead of `V35` to simplify finding it when doing future version branching.

2018-05-28 21:27 UTC, henriknyman commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/EnterpriseCompilerFactory.scala
>            new ParallelDispatcher(morselSize, numberOfThreads, executorService)
Maybe not in the scope of this PR, but wouldn't it make sense for dispatcher to be a lazy val?

2018-05-29 07:25 UTC, fickludd commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/EnterpriseCompilerFactory.scala
>            new ParallelDispatcher(morselSize, numberOfThreads, executorService)
I totally agree, I'll make a card.

2018-05-29 12:56 UTC, henriknyman approved these changes

2018-06-01 13:58 UTC, merged