3.5 create index procedure
neo4j/neo4j pull request #11879
Opened 2018-05-29 07:47 UTC by burqen

New PR from https://github.com/neo4j/neo4j/pull/11742

BuiltInProcedures
- db.createIndex
EnterpriseBuiltInProcedure
- db.createNodeKey
- db.createUniquePropertyConstraint

Procedures allow user to specify index provider upon index
and constraint creation. This is otherwise controlled by
dbms.index.default_schema_provider and to change this you
need to restart db.

Like other procedures interacting with schema indexes it takes
schema pattern ":Label( prop1, prop2,... )" as argument as well as
index provider name.
Allowed index provider names correspond to IndexProvider.Descriptor.name()
and allowed values for setting (dbms.index.default_schema_provider).

If label or property tokens are missing, they will be created.

**Why do we need this?**
We need a way to mitigate for the limitations in native string index
(4k length and limited support for contains and ends with).
When creating an index (or constraint) through Cypher the default
index provider is always used. The default provider is controlled with
db.index.default_schema_provider setting. To change this setting user
have to restart the db. This is sad.
Those procedures allow user to specify index provider per index creation
without having to do any db restart.
This gives user two different ways to create an index which is bad and
optimal way would be to have support for this in cypher language. For
3.4 release, that is not feasible and so falling back to procedures is
the way to go.

2018-05-30 06:26 UTC, ragadeeshu approved these changes
Simple, clean, small, at the very least

2018-05-30 06:49 UTC, burqen commented
(I'll squash commits on merge)

2018-06-01 10:02 UTC, andreikoval requested changes

2018-06-01 10:02 UTC, andreikoval commented on enterprise/neo4j-enterprise/src/test/java/org/neo4j/kernel/builtinprocs/EnterpriseCreateIndexProcedureIT.java
> +        try
There's a better way to do this: `E e = Assertions.assertThrows(E.class, () -> {...})`

2018-06-01 10:02 UTC, andreikoval commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/IndexProcedures.java
> +        String statusMessage = "index created";
Inline this

2018-06-01 10:02 UTC, andreikoval commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/IndexProcedures.java
> +            throw new ProcedureException( e.status(), e, "" );
Please replace empty string with a proper error message

2018-06-01 10:02 UTC, andreikoval commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/IndexProcedures.java
> +                throw new ProcedureException( e.status(), e, "" );
Please replace empty string with a proper error message

2018-06-01 10:02 UTC, andreikoval commented on community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/state/DefaultIndexProviderMap.java
> +    private String[] indexProviderNames()
There's no need in this method, using `indexProvidersByName.keySet()` will render exactly the same string representation.

2018-06-01 10:02 UTC, andreikoval commented on community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/state/DefaultIndexProviderMapTest.java
>          try
Since you already started improving the code, replace it with `assertThrows()` as well

2018-06-04 07:45 UTC, burqen commented
@andreikoval and @ragadeeshu Thank you for the feedback! Comments should be addressed now.

2018-06-04 08:56 UTC, andreikoval commented
👌

2018-06-04 08:57 UTC, andreikoval approved these changes

2018-06-11 13:42 UTC, closed without merging