Flatten create operators
neo4j/neo4j pull request #11900
Opened 2018-05-31 06:50 UTC by fickludd

Welcome to this full-stack cypher experience. 

This change greatly improves performance for queries of the type

 `CREATE (a1)-[:R]->(b2), (a2)-[:R]->(a3),...,(a3000)-[:R]->(a3001)`

Which would otherwise often give stack overflows in all kinds of
places. The implemented solution replaces the previous nested
CreateNode and CreateRelationship operators with one Create operator,
that in turn has two flat lists of CreateNode and CreateRelationship
commands.

To also help for queries of consecutive CREATE clauses, these are now flattened into one.

 `CREATE (a) CREATE (b)` => `CREATE (a),(b)`

I also took the opportunity to simplify the Create pipes, and reuse
some more interpreted functionality in slotted.

2018-05-31 13:30 UTC, pontusmelke commented
There are very many test failures, I will wait with reviewing until the number of failures drops to a more reasonable number :)

2018-05-31 18:21 UTC, fickludd commented
@pontusmelke I messed up CypherComparisonSupport. Should be fixed now.

2018-06-01 12:46 UTC, pontusmelke requested changes
This looks good, there are still some failing tests though.

2018-06-01 12:46 UTC, pontusmelke commented on community/cypher/cypher-planner-3.5/src/main/scala/org/neo4j/cypher/internal/compiler/v3_5/ast/convert/plannerQuery/ClauseConverters.scala
> +    // We need this locally to avoid creating node twice is they occur
This sentence is weird, `as they occur`?

2018-06-01 12:46 UTC, pontusmelke commented on community/cypher/cypher-planner-3.5/src/main/scala/org/neo4j/cypher/internal/compiler/v3_5/ast/convert/plannerQuery/StatementConverters.scala
> +//    clauses
we can remove this

2018-06-07 11:02 UTC, fickludd commented
Migrated to new repo.

2018-06-07 11:02 UTC, closed without merging