Expose ProcedureGuard to check tx termination and guards from within …
neo4j/neo4j pull request #7931
Opened 2016-09-13 15:01 UTC by boggle

…long running procedures

2016-09-15 09:16 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/guard/TimeoutGuard.java
> +    public void check( KernelTransactionImplementation transaction )
Please add `@Override` here

2016-09-15 09:18 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/factory/DataSourceModule.java
> +            return (TerminationGuard) () ->
please extract this class into separate class and put it into some procedure related package, most probably where `TerminationGuard` live

2016-09-15 09:21 UTC, MishaDemianenko requested changes
@boggle  Two small comments and also please note there is test failure atm. Review round complete

2016-09-16 18:56 UTC, boggle commented
This was green; just rebased but since it's weekend waiting for another build.

2016-09-17 11:23 UTC, merged