From comments to code
neo4j/neo4j pull request #7970
Opened 2016-09-19 14:37 UTC by mneedham

2016-09-20 15:15 UTC, martinfurmanski commented on enterprise/core-edge/src/main/java/org/neo4j/coreedge/core/state/snapshot/CoreStateDownloader.java
> +        tempStore.cleanDirectory();
This will not delete the temp directory itself.

2016-09-20 15:16 UTC, martinfurmanski commented on enterprise/core-edge/src/main/java/org/neo4j/coreedge/edge/EdgeStartupProcess.java
> +        tempStore.cleanDirectory();
This will not delete the temp directory itself.

2016-09-20 15:16 UTC, martinfurmanski requested changes
Can we have some unit tests?

2016-09-21 08:35 UTC, davidegrohmann commented
This will conflict with https://github.com/neo4j/neo4j/pull/7978/commits/0b20881db1b725e386126f57c260b8e5927dfc85

2016-09-26 11:59 UTC, davidegrohmann commented
@mneedham I am closing this since it has been subsumed by other changes.

2016-09-26 11:59 UTC, closed without merging