Proper namespace resolution
neo4j/neo4j pull request #7973
Opened 2016-09-20 07:20 UTC by pontusmelke

It should be possible to use the names of the built-in functions as long
as you put the function in a separate namespace. The lookup was erroneously
using only the name of the function when doing lookup which lead to that
user-defined functions were shadowed by the built-in function with the same name.

2016-09-20 16:34 UTC, Mats-SX commented on community/neo4j-harness/src/main/java/org/neo4j/harness/internal/AbstractInProcessServerBuilder.java
> +     * can addProcedure custom injectables that procedures need.
Is this change intentional?

2016-09-20 16:36 UTC, Mats-SX commented on community/neo4j-harness/src/test/java/org/neo4j/harness/JavaFunctionsTest.java
> +        try(ServerControls server = TestServerBuilders.newInProcessBuilder().withFunction( MyFunctions.class ).newServer())
Missing some padding whitespace, also in `try-with-resources` below

2016-09-20 16:39 UTC, Mats-SX commented on integrationtests/src/test/java/org/neo4j/procedure/UserFunctionIT.java
> +
This is the newline that breaks the PR build.

2016-09-20 16:41 UTC, Mats-SX commented on integrationtests/src/test/java/org/neo4j/procedure/UserFunctionIT.java
> +        Result res = db.execute( "RETURN org.neo4j.procedure.sum([1337, 2.718281828, 3.1415]) AS result");
Missing ending padding whitespace

2016-09-20 16:43 UTC, Mats-SX reviewed
Nice test improvements!

2016-09-20 17:45 UTC, boggle commented on integrationtests/src/test/java/org/neo4j/procedure/UserFunctionIT.java
> +        "| 'org.neo4j.procedure.sum'                           | 'org.neo4j.procedure.sum(numbers :: LIST? OF NUMBER?) :: (NUMBER?)'
This is useful but I have mixed feelings exposing a function with the same name (even in  a namespace) as a built in aggregate function. Especially given that we've said we want to look into how aggregate functions might be called on lists. Could we rename this to make it a bit different from ordinary `sum`?

2016-09-20 17:46 UTC, boggle requested changes

2016-09-20 18:02 UTC, jexp commented on integrationtests/src/test/java/org/neo4j/procedure/UserFunctionIT.java
> +        "| 'org.neo4j.procedure.sum'                           | 'org.neo4j.procedure.sum(numbers :: LIST? OF NUMBER?) :: (NUMBER?)'
Actually it's intentional, as users will have namespace functions where the simple function name clashes with built in ones. Which is fine as we have the namespace.

Actually that was the reason for this fix, the clash. And we will not force users to make up awkward names for common operations.

2016-09-20 18:03 UTC, jexp approved these changes
Thanks for the fix, looks good to me.

2016-09-20 19:23 UTC, pontusmelke commented on integrationtests/src/test/java/org/neo4j/procedure/UserFunctionIT.java
> +        "| 'org.neo4j.procedure.sum'                           | 'org.neo4j.procedure.sum(numbers :: LIST? OF NUMBER?) :: (NUMBER?)'
@boggle this is not a built-in-function it is a normal user-defined function added in this test class.

2016-09-20 19:29 UTC, pontusmelke commented on community/neo4j-harness/src/main/java/org/neo4j/harness/internal/AbstractInProcessServerBuilder.java
> +     * can addProcedure custom injectables that procedures need.
hmm...github now longer remove stuff that has been fixed, anyway fixed this.

2016-09-20 19:30 UTC, pontusmelke commented on community/neo4j-harness/src/test/java/org/neo4j/harness/JavaFunctionsTest.java
> +        try(ServerControls server = TestServerBuilders.newInProcessBuilder().withFunction( MyFunctions.class ).newServer())
fixed

2016-09-20 19:30 UTC, pontusmelke commented on integrationtests/src/test/java/org/neo4j/procedure/UserFunctionIT.java
> +
thanks! fixed

2016-09-20 19:30 UTC, pontusmelke commented on integrationtests/src/test/java/org/neo4j/procedure/UserFunctionIT.java
> +        Result res = db.execute( "RETURN org.neo4j.procedure.sum([1337, 2.718281828, 3.1415]) AS result");
fixed

2016-09-21 08:38 UTC, pontusmelke commented on integrationtests/src/test/java/org/neo4j/procedure/UserFunctionIT.java
> +        "| 'org.neo4j.procedure.sum'                           | 'org.neo4j.procedure.sum(numbers :: LIST? OF NUMBER?) :: (NUMBER?)'
@boggle I clarified it for you :)

2016-09-21 12:01 UTC, boggle commented on integrationtests/src/test/java/org/neo4j/procedure/UserFunctionIT.java
> +        "| 'org.neo4j.procedure.sum'                           | 'org.neo4j.procedure.sum(numbers :: LIST? OF NUMBER?) :: (NUMBER?)'
Thank you so much :) Less confusion for the win

2016-09-21 12:02 UTC, boggle approved these changes

2016-09-21 19:50 UTC, merged