Support `CALL` inside `FOREACH`
neo4j/neo4j pull request #8014
Opened 2016-09-23 11:43 UTC by Mats-SX

2016-09-23 12:13 UTC, systay commented on community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/ProcedureCallSupportAcceptanceTest.scala
> +  test("should work inside FOREACH") {
We should add tests for:
 * `CALL` inside `FOREACH` inside `FOREACH`
 * `CALL ... YIELD` inside `FOREACH`
 * A `CALL` that takes input params from the variable introduced in the `FOREACH`
 * `NULL` is another thing that usually exposes problems, but I don't know how to get that in here

2016-09-23 12:14 UTC, systay commented on community/cypher/frontend-3.1/src/main/scala/org/neo4j/cypher/internal/frontend/v3_1/ast/Clause.scala
> +  private def okInsideForeach(clause: Clause) = clause match {
Nice. very readable.

2016-09-23 12:14 UTC, systay requested changes

2016-11-03 09:33 UTC, Mats-SX commented
CLG decision: not supported.

2016-11-03 09:33 UTC, closed without merging