Foundational changes for Cypher chunking
neo4j/neo4j pull request #8018
Opened 2016-09-23 16:28 UTC by petraselmer

2016-10-03 23:09 UTC, jjaderberg requested changes
Very nice!

Two trifles indicated need fixing:
- no `[discrete]` styles in AsciiDoc
- file names for include directives must agree with what is generated

There is a third after that which at a glance looks like a renegade null character, but I haven't quite figured it out yet.

2016-10-03 23:09 UTC, jjaderberg commented on manual/cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/FunctionsTest.scala
> +      title = "size() - list",
I believe the title controls the file name. With a title of "size() - list" the file name becomes "size---list.asciidoc", which means the include directive for this content fails. If you run a `find manual/cypher/cypher-docs/ -name "*size*"` you should see the generated files. Mutatis mutandis also the other "size" and the two "length" items.

2016-10-03 23:09 UTC, jjaderberg commented on manual/cypher/cypher-docs/src/docs/dev/clause.asciidoc
> +[discrete]
I don't think the AsciiDoc processor knows `[discrete]` so it chokes. Can we make do without it?

2016-10-04 10:25 UTC, petraselmer commented
@jjaderberg thanks for the comments. I have addressed the two issues you raised.

2016-10-10 08:06 UTC, jjaderberg approved these changes

2016-10-10 08:08 UTC, merged