Fix NPE in dependecy resolver when datasource is null
neo4j/neo4j pull request #8060
Opened 2016-09-30 12:44 UTC by davidegrohmann

In some cases if you ask for resolving a dependency from the Neo store
data source when the latter is not available a NPE is thrown.  This
change will fix that behaviour by skipping the unavailable data source
from the list of possible dependency providers.

2016-10-03 11:20 UTC, MishaDemianenko requested changes

2016-10-03 11:20 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/factory/PlatformModule.java
> +                if ( dataSource == null /* if data source is unavailable */ )
It's hard to see from a change set why do you need this change, but from a change itself it looks like this is a workaround and it does not look like a safe and correct thing to do.
How/when datasource can be null? Test that cover/show that situation?

2016-10-05 08:59 UTC, davidegrohmann commented on community/kernel/src/main/java/org/neo4j/kernel/impl/factory/PlatformModule.java
> +                if ( dataSource == null /* if data source is unavailable */ )
Whenever you stop the database, which happens during storecopy for example.
I'll add a test.

2016-10-05 11:08 UTC, davidegrohmann commented
@MishaDemianenko added tests

2016-10-05 14:09 UTC, merged