Enforce write privileges for token writes
neo4j/neo4j pull request #8113
Opened 2016-10-07 14:43 UTC by Mats-SX

Cypher was recently changed to not perform token writes in read queries.
This commit adds a test that will fail if it would do so. It further enforces that
acquiring `TokenWriteOperations` requires the `AccessMode` to allow writes.

This PR adds a test for the change in #8100.

2016-10-10 11:27 UTC, lutovich requested changes
@Mats-SX change looks good to me. It is possible to prettify code a bit and extract an assertion method. More importantly, build has test failures related to the change.

2016-10-10 11:27 UTC, lutovich commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/KernelStatement.java
> +        if ( !transaction.mode().allowsWrites() )
Similar checks already exist in `#dataWriteOperations()` and `#schemaWriteOperations()`. I think it is worth to create a method like `assertWritesAllowed(String message)` at this point.

2016-10-10 13:32 UTC, Mats-SX commented
@lutovich Thanks for the review! We made this commit to address your comment: https://github.com/neo4j/neo4j/pull/8113/commits/c0c061de74e884838608f757a3db4934e0b67376

2016-10-11 11:51 UTC, lutovich approved these changes

2016-10-12 09:31 UTC, merged