Add testing of legacy Cypher HTTP endpoint
neo4j/neo4j pull request #8134
Opened 2016-10-11 09:31 UTC by Mats-SX

This works very much like the transactional REST/HTTP endpoint, so it inherits
and uses most of the pre-existing functionality, with some minor alterations in
the JSON input and output.

2016-10-12 11:52 UTC, OliviaYtterbrink commented on enterprise/server-enterprise/src/test/java/org/neo4j/server/rest/security/CypherRESTInteraction.java
> +    public String executeQuery( RESTSubject subject, String call, Map<String,Object> params,
Could rewrite this in the superclass and only extract the minor parts that are different.

2016-10-13 07:34 UTC, OliviaYtterbrink requested changes

2016-10-13 07:34 UTC, OliviaYtterbrink commented on enterprise/server-enterprise/src/test/java/org/neo4j/server/rest/security/CypherRESTAuthScenariosInteractionTest.java
> +    // TODO: This is removed in an upcoming PR, so it doesn't need to be fixed
Needs rebase due to merging of https://github.com/neo4j/neo4j/pull/8114

2016-10-13 08:23 UTC, Mats-SX commented on enterprise/server-enterprise/src/test/java/org/neo4j/server/rest/security/CypherRESTAuthScenariosInteractionTest.java
> +    // TODO: This is removed in an upcoming PR, so it doesn't need to be fixed
Rebased and removed.

2016-10-13 08:24 UTC, Mats-SX commented on enterprise/server-enterprise/src/test/java/org/neo4j/server/rest/security/CypherRESTInteraction.java
> +    public String executeQuery( RESTSubject subject, String call, Map<String,Object> params,
I did that, and also extracted all common code to an abstract super-class.

2016-10-13 11:25 UTC, OliviaYtterbrink approved these changes

2016-10-13 13:47 UTC, merged