Fixes a race condition creating input groups in importer
neo4j/neo4j pull request #8135
Opened 2016-10-11 10:03 UTC by tinwelint

Now that input may be processed in parallel, different groups of inputs
which have different groups may request to create new groups concurrently.
Groups class wasn't thread safe since there was previously no requirement
for it.

This commit makes Groups#getOrCreate call synchronized to handle concurrent
invocation. It's typically invoked quite rarely so the locking nature of it
is fine.

cl [tools] Fixes a race condition with ID groups in importer which would have some correct relationships considered invalid and logged into bad.log instead

2016-10-14 14:30 UTC, burqen requested changes
Behaviour change looks good.

I'm not entirely sure about why we need to add processors argument to any of the `Deserializers`. Is it only for test purposes? Seems unrelated to the problem that this PR is addressing.

Otherwise, small clean up comments.

2016-10-14 14:30 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/input/csv/InputGroupsDeserializer.java
> +        this.previousInputProcessors = processors;
Can remove initialisation from declaration if initialised here.

2016-10-14 14:30 UTC, burqen commented on community/kernel/src/test/java/org/neo4j/unsafe/impl/batchimport/input/csv/InputGroupsDeserializerTest.java
> +                            deserialization, decorator, validator, badCollector );
This is the same lamba used in `CsvInput#nodes()` and almost the same as `CsvInput#relationships()`.
I think readability would be improved by extracting them to concrete classes.

2016-10-14 14:30 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/input/csv/InputGroupsDeserializer.java
> +            Configuration config, IdType idType, int maxProcessors, int processors, DeserializerFactory<ENTITY> factory,
See over all comment about processors.

2016-10-14 14:30 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/input/csv/ParallelInputEntityDeserializer.java
> +            IdType idType, int maxProcessors, int processors, DeserializerFactory<ENTITY> factory,
See over all comment about processors.

2016-10-14 14:30 UTC, burqen commented on community/kernel/src/test/java/org/neo4j/unsafe/impl/batchimport/input/GroupsTest.java
> +    public void shouldHandleConcurrentGetOrCreate() throws Throwable
Nice

2016-10-15 15:50 UTC, tinwelint commented
@burqen the change simplified tests. The way these classes are used currently there's really no need to specify initial processor count, currently. At the same time this could be seen as a bug because an invocation on `processors(int)` would have no effect before the first call to `hasNext()`, of course we wouldn't need to add this constructor argument for this, we could have tests call `processors(int)` after construction (which they previously not quite couldn't as easily, with the first `hasNext()` thing), but since I was changing things around here and tests looked unnecessarily complicated I though I'd just add it.

2016-10-17 08:08 UTC, burqen approved these changes

2016-10-17 08:09 UTC, merged