Improve `neo4j-admin help` output.
neo4j/neo4j pull request #8160
Opened 2016-10-13 12:00 UTC by srbaker

2016-10-18 15:24 UTC, benbc requested changes

2016-10-18 15:24 UTC, benbc commented on community/command-line/src/main/java/org/neo4j/commandline/admin/AdminTool.java
> +        failure( e.getMessage() );
This is not going to work -- `failure()` calls `System.exit()`.

There is also another version of `badUsage()` where the order needs to change.

2016-10-18 15:24 UTC, benbc commented on community/command-line/src/test/java/org/neo4j/commandline/admin/HelpCommandTest.java
> +    public void showsGeneralHelpOutputWhenNoCommandIsProvided() {};
Bong!

2016-10-18 15:24 UTC, benbc commented on community/command-line/src/main/java/org/neo4j/commandline/admin/HelpCommand.java
> +        executeWithCommandLocator( CommandLocator.fromServiceLocator(), args );
Can't you inject the `CommandLocator` in the constructor?

2016-10-18 15:24 UTC, benbc commented on community/command-line/src/main/java/org/neo4j/commandline/admin/HelpCommand.java
>              return new HelpCommand( usage, outsideWorld::stdOutLine );
Is the `usage` parameter still used?

2016-10-18 16:43 UTC, srbaker commented on community/command-line/src/main/java/org/neo4j/commandline/admin/HelpCommand.java
>              return new HelpCommand( usage, outsideWorld::stdOutLine );
Yes, we use it for the default case of simply `neo4j-admin help`

2016-10-19 10:10 UTC, benbc reviewed
Please can you show before (maybe truncted) and after output in the PR description?

2016-10-19 10:10 UTC, benbc commented on community/command-line/src/main/java/org/neo4j/commandline/admin/AdminTool.java
> +        outsideWorld.stdErrLine( message );
But shouldn't this now go above the usage?

2016-10-19 10:10 UTC, benbc commented on community/command-line/src/main/java/org/neo4j/commandline/admin/HelpCommand.java
> +                this.output.accept( "" );
This case should exit non-zero, I think. That is, it needs to throw an exception. How about also arranging for it to print the valid list of commands?

2016-10-19 10:10 UTC, benbc commented on community/command-line/src/test/java/org/neo4j/commandline/admin/HelpCommandTest.java
> +    public void showsGeneralHelpOutputWhenNoCommandIsProvided() {};
This needs to go or be implemented.

2016-10-25 09:22 UTC, benbc approved these changes

2016-10-25 09:23 UTC, benbc commented
LGTM

2016-10-25 09:23 UTC, merged