Add AuthorizationExpired exception to plugin API
neo4j/neo4j pull request #8193
Opened 2016-10-18 09:56 UTC by henriknyman

Plugins that manages their own caching of authorization info that requires
a user to re-authenticate need the possibility to signal this back to the
client.
To the client this will surface in the same way as if authorization
expired in the internal cache of the ldap and plugin auth providers.

2016-10-19 08:12 UTC, Mats-SX requested changes
Unless there's a good reason, I'd like the exception to have its cause attached.

2016-10-19 08:12 UTC, Mats-SX commented on community/common/src/main/java/org/neo4j/kernel/api/exceptions/Status.java
> -    enum Security implements Status  // TODO: rework by the Security Team before these are updated
So I guess it's reworked now, then? ;)

2016-10-19 08:12 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/auth/plugin/PluginRealm.java
> +            org.neo4j.server.security.enterprise.auth.plugin.spi.AuthorizationInfo authorizationInfo;
Why does it have to contain the full qualified name here? Can we rename it to avoid this?

2016-10-19 08:12 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/auth/plugin/PluginRealm.java
> +                        "Plugin '" + getName() + "' authorization info expired: " + e.getMessage() );
I'm a fan of attaching cause exceptions. Is there a particular reason we do not want to do that here? (To clarify, I mean sending in the caught exception into the constructor of the thrown exception.)

2016-10-19 08:12 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/auth/plugin/api/AuthorizationExpired.java
> +    public AuthorizationExpired( String message )
Above comment about attaching cause exception would require a change here.

2016-10-19 08:12 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/auth/plugin/api/AuthorizationExpired.java
> + * the two separate interfaces <tt>AuthenticationPlugin</tt> and <tt>AuthorizationPlugin</tt>),
Can we have `@link`s for these two as well?

2016-10-19 21:49 UTC, henriknyman commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/auth/plugin/PluginRealm.java
> +            org.neo4j.server.security.enterprise.auth.plugin.spi.AuthorizationInfo authorizationInfo;
Apache Shiro also has AuthorizationInfo. We are using both in this class.

2016-10-19 21:55 UTC, henriknyman commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/auth/plugin/PluginRealm.java
> +                        "Plugin '" + getName() + "' authorization info expired: " + e.getMessage() );
The primary point of this exception is communicating a status to the client. Only the message and status code will reach the client. Nobody is looking at the stack trace so I don't see any point of attaching the cause.

2016-10-19 21:58 UTC, henriknyman commented on community/common/src/main/java/org/neo4j/kernel/api/exceptions/Status.java
> -    enum Security implements Status  // TODO: rework by the Security Team before these are updated
I think it is an old comment that is not that relevant anymore

2016-10-20 08:03 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/auth/plugin/PluginRealm.java
> +                        "Plugin '" + getName() + "' authorization info expired: " + e.getMessage() );
OK, fair enough.

2016-10-20 08:03 UTC, Mats-SX approved these changes

2016-10-20 10:53 UTC, merged