Update descriptions in `SecuritySettings`
neo4j/neo4j pull request #8228
Opened 2016-10-20 10:01 UTC by systay

`neo4j.conf` received some updates earlier, this PR updates the source code descriptions to match.

2016-10-20 11:01 UTC, fickludd commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "An important consequence of setting this to `true` that needs to be well understood, is that " +
I think "that needs to be well understood" is redundant and could be removed all together

2016-10-20 11:02 UTC, fickludd commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +    @Description( "Perform LDAP search for authorization info using a system account or the user's own account.\n\n" +
maybe:
"Perform LDAP search for authorization info using a system account as opposed to the user's own account.\n\n"

2016-10-20 11:04 UTC, fickludd commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "You need to specify the username and password with the next two settings below with his option. " +
instead of saying "the next two settings", these could be named

2016-10-20 11:06 UTC, fickludd commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "and you do not require full auditing capability")
codestyle?

2016-10-20 11:06 UTC, henriknyman commented on packaging/standalone/standalone-enterprise/src/main/distribution/text/enterprise/conf/neo4j.conf
> +#
I think according to the policy this should be here to show that the default value is empty

2016-10-20 11:08 UTC, fickludd commented on packaging/standalone/standalone-enterprise/src/main/distribution/text/enterprise/conf/neo4j.conf
> +# An important consequence of setting this to `true` that needs to be well understood, is that
Same "that needs to be well understood" comment as above

2016-10-20 11:08 UTC, fickludd commented
left some minor nitpicks, take or leave

2016-10-20 11:35 UTC, henriknyman commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "enabled. A common case is that this matches the last part of `dbms.security.ldap.user_dn_template`." )
This setting is now called `dbms.security.ldap.authentication.user_dn_template`

2016-10-20 11:36 UTC, henriknyman commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "and you do not require full auditing capability")
Also missing a space after the . on the first line of the description

2016-10-20 11:38 UTC, henriknyman commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "enabled. A common case is that this matches the last part of `dbms.security.ldap.user_dn_template`." )
This is also wrong in two places in the comments in neo4j.conf. Maybe you could fix it in this PR?

2016-10-20 11:41 UTC, henriknyman commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "enabled. A common case is that this matches the last part of `dbms.security.ldap.user_dn_template`." )
Also it is incorrect in the description for `dbms.security.ldap.authorization.system_username` above this

2016-10-20 14:58 UTC, craigtaverner commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +    @Description( "Perform LDAP search for authorization info using a system account or the user's own account.\n\n" +
Or: "Perform LDAP search for authorization info using a system account instead of the user's own account.\n\n"

2016-10-20 15:00 UTC, craigtaverner commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "set the protocol and port, e.g. `ldaps://ldap.example.com:636` " +
You do not need to set the port for LDAPS, it defaults to 636.

2016-10-20 15:01 UTC, craigtaverner commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
>              setting( "dbms.security.ldap.host", STRING, "localhost:389" );
You do not need to set the port, it defaults to 389 for LDAP and 636 for LDAPS.

2016-10-20 15:05 UTC, craigtaverner commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +    @Description( "Perform LDAP search for authorization info using a system account or the user's own account.\n\n" +
Or:
"Perform LDAP search for authorization info using a system account instead of the user's own account.\n\n"

2016-10-20 22:04 UTC, jjaderberg requested changes

2016-10-20 22:04 UTC, jjaderberg commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "set the protocol and port, e.g. `ldaps://ldap.example.com:636` " +
If the default is 636 why is the default setting value `localhost:389`?

2016-10-20 22:04 UTC, jjaderberg commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "set the protocol and port, e.g. `ldaps://ldap.example.com:636` " +
Even if 636 is the default value it is fine (safe) to use it in an example.

2016-10-20 22:04 UTC, jjaderberg commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
>              "The LDAP referral behavior when creating a connection. This is one of `follow`, `ignore` or `throw`.\n" +
Bulleted lists don't work in this context. The output will be a paragraph with some asterisks in it. It's out of scope of this PR to fix this, but worth noting that adding `* item` won't actually add items to a proper list.

2016-10-20 22:04 UTC, jjaderberg commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "group membership attributes on themselves in the directory.\n\n" +
"for the group membership attributes on themselves" => "for their own group memberships" or "for group memberships for their own user"

2016-10-20 22:04 UTC, jjaderberg commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "You need to specify the username and password with the next two settings below with his option. " +
If "the next two settings" means making assumptions on order in the resulting content then indeed the two settings need to be referenced. Other components may have settings that are inserted in between, or the principle of order and grouping may change.

2016-10-20 22:04 UTC, jjaderberg commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "Note that this account only needs read-only access to the relevant parts of the LDAP directory " +
Can we truthfully get away with "read access" to avoid the double "only"?

2016-10-20 22:04 UTC, jjaderberg commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "and does not need to have access rights to Neo4j or any other systems." )
"Neo4j, or any other"

2016-10-20 22:04 UTC, jjaderberg commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "E.g. group1=role1;group2=role2;group3=role3,role4,role5\n\n" +
Prefer "For example," over "E.g.,"

2016-10-20 22:04 UTC, jjaderberg commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "external auth providers (ldap or plugin). Setting the TTL to 0 will disable auth caching." )
capitalize LDAP

2016-10-20 22:04 UTC, jjaderberg commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "and you do not require full auditing capability")
Code style *ought* to be: "One sentence per line." when writing docs, even if the docs happen to be embedded in other code. Not holding my breath about that one, though.

2016-10-21 08:09 UTC, Mats-SX commented
Thanks for all the great feedback guys!

2016-10-21 11:24 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "and you do not require full auditing capability")
@jjaderberg Judging by the looks of the `@Description`s in `GraphDatabaseSettings`, that is _not_ current styling. It seems these are optimised for code readability, and to fit on 120 chars.

2016-10-21 11:28 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +    @Description( "Perform LDAP search for authorization info using a system account or the user's own account.\n\n" +
It took me a while to realise that @craigtaverner's suggestions were duplicate. I prefer that one here.

2016-10-21 11:30 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "You need to specify the username and password with the next two settings below with his option. " +
And both of you missed that it says `his` rather than `this` :D

2016-10-21 11:33 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "You need to specify the username and password with the next two settings below with his option. " +
I changed it to the following:

> You need to specify the username and password using the settings `dbms.security.ldap.authorization.system_username` and `dbms.security.ldap.authorization.system_password` with this option.

2016-10-21 11:43 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "set the protocol and port, e.g. `ldaps://ldap.example.com:636` " +
I guess it's default `389` because the default is to use `LDAP` non-secure, rather than `LDAPS`? Please confirm @craigtaverner @henriknyman 

@craigtaverner Does changing the text to the following satisfy your comment?

> To use LDAPS, set the protocol to `ldaps://ldap.example.com`. The default port for LDAPS is 636.

2016-10-21 11:44 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
>              setting( "dbms.security.ldap.host", STRING, "localhost:389" );
Are you suggesting we change the default value?

2016-10-21 11:47 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
>              "The LDAP referral behavior when creating a connection. This is one of `follow`, `ignore` or `throw`.\n" +
Would you advise to move it into a normal sentence without line breaks and asterisks then? It's easy to fix.

2016-10-21 11:50 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "group membership attributes on themselves in the directory.\n\n" +
I changed it to

> for their own group membership attributes in the directory

2016-10-21 11:51 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "Note that this account only needs read-only access to the relevant parts of the LDAP directory " +
I think so, yes.

2016-10-21 12:02 UTC, Mats-SX commented
The GitHub UI hides it, but there are two additional outstanding comments by @craigtaverner that I haven't yet addressed.

2016-10-21 17:37 UTC, henriknyman commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "and you do not require full auditing capability" )
Missing . at the end of sentence.

2016-10-21 17:37 UTC, henriknyman commented on packaging/standalone/standalone-enterprise/src/main/distribution/text/enterprise/conf/neo4j.conf
> +# The format of the setting is `<protocol>://<hostname>:<port>`, where hostname is the only required field.
This is a bit chatty now, maybe "(with protocol, hostname and port)" can go away since it is made redundant by this line.

2016-10-21 17:37 UTC, henriknyman commented on packaging/standalone/standalone-enterprise/src/main/distribution/text/enterprise/conf/neo4j.conf
> +# For example: `ldaps://ldap.example.com:4444`.
4444 is a bit strange example, or is it some kind of standard example? Otherwise 10389 could be more of a real world use case example

2016-10-21 17:37 UTC, henriknyman commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "         \"cn=Neo4j Administrator,cn=users,dc=example,dc=com\"  = admin" )
Is this formatting presented correctly in the manual? Otherwise maybe it is enough to have it in `neo4j.conf` only.

2016-10-21 17:37 UTC, henriknyman commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "The format of the setting is `<protocol>://<hostname>:<port>`, where hostname is the only " +
This is a bit chatty now, maybe "(with protocol, hostname and port)" can go away since it is made redundant by this line.

2016-10-24 08:37 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/configuration/SecuritySettings.java
> +                  "         \"cn=Neo4j Administrator,cn=users,dc=example,dc=com\"  = admin" )
I think it respects the newlines. I'd rather not have to redo this one again.

2016-10-24 08:38 UTC, Mats-SX commented on packaging/standalone/standalone-enterprise/src/main/distribution/text/enterprise/conf/neo4j.conf
> +# For example: `ldaps://ldap.example.com:4444`.
No we just picked a number at random. Changed it to 10389.

2016-10-24 08:54 UTC, Mats-SX commented
@jjaderberg Is this PR approved, or are there more changes that you'd like to see?

2016-10-25 07:00 UTC, jjaderberg approved these changes

2016-10-25 07:20 UTC, merged