Better document CALL ... YIELD ... (and WHERE ...)
neo4j/neo4j pull request #8237
Opened 2016-10-21 13:47 UTC by boggle

2016-10-21 14:27 UTC, Mats-SX requested changes
Nice docs. I'd like to see clearer definitions of standalone calls and void procedures.

2016-10-21 14:27 UTC, Mats-SX commented on manual/cypher/cypher-docs/src/docs/dev/ql/call/index.asciidoc
> +This may be done either explicitly, by listing them in parenthesis and separated by commas after the procedure name, or implicitly by using available query parameters as procedure call arguments.
I suggest changing 

>  by listing them in parenthesis and separated by commas after the procedure name

to

> using a comma-separated list wrapped in parentheses after the procedure name

2016-10-21 14:27 UTC, Mats-SX commented on manual/cypher/cypher-docs/src/docs/dev/ql/call/index.asciidoc
> +The latter form is only available when the whole query consists of a single `CALL` clause (i.e. in a standalone procedure call).
I suggest using this paragraph to clearly define `standalone procedure call`, perhaps:

> The latter form is available only in a so-called standalone call, when the whole query consists of a single `CALL` clause.

2016-10-21 14:27 UTC, Mats-SX commented on manual/cypher/cypher-docs/src/docs/dev/ql/call/index.asciidoc
> +All new variables bound by a procedure call are added to the set of variables already bound in the current scope.
All -> Any

2016-10-21 14:27 UTC, Mats-SX commented on manual/cypher/cypher-docs/src/docs/dev/ql/call/index.asciidoc
> +In this case, all result fields are yielded as newly bound variables from the procedure call to the user or for further processing by the remaining query.
This is in the context of a standalone procedure call, so there is no remaining query to speak of.

2016-10-21 14:27 UTC, Mats-SX commented on manual/cypher/cypher-docs/src/docs/dev/ql/call/index.asciidoc
> +Calling a `VOID` procedures may only have a side effect and will not produce any result records and thus does neither allow nor require the use of `YIELD`.
`VOID` procedure has not yet been defined here. See above comment about defining them.

2016-10-21 14:27 UTC, Mats-SX commented on manual/cypher/cypher-docs/src/docs/dev/ql/call/index.asciidoc
> +Most procedures return a stream of records with a fixed set of result fields, similar to how running a Cypher query returns a stream of records, too.
I suggest defining `VOID` procedures here, perhaps:

> Procedures that do not declare any result fields are called `VOID` procedures.

2016-10-21 14:27 UTC, Mats-SX commented on manual/cypher/cypher-docs/src/docs/dev/ql/call/index.asciidoc
> +Calling a `VOID` procedures may only have a side effect and will not produce any result records and thus does neither allow nor require the use of `YIELD`.
I suggest changing this to 

> Calling a `VOID` procedure may have side effects, but will not produce any result records and thus does neither allow nor require the use of `YIELD`.

2016-10-21 14:27 UTC, Mats-SX commented on manual/cypher/cypher-docs/src/docs/dev/ql/call/index.asciidoc
> +The following examples show how to pass arguments to and how to yield result fields from a procedure call.
May omit the second `how to`.

2016-10-21 14:27 UTC, Mats-SX commented on manual/cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/CallTest.scala
> +      text = "This calls the built-in procedure 'db.labels' to count all in-use labels in the database that contain the word 'User'",
I suggest replacing apostrophes (') with backticks (`).

2016-10-24 09:37 UTC, petraselmer commented on manual/cypher/cypher-docs/src/docs/dev/ql/call/index.asciidoc
> +Most procedures return a stream of records with a fixed set of result fields, similar to how running a Cypher query returns a stream of records, too.
I would leave out the ", too" text (doesn't add anything)

2016-10-24 09:41 UTC, petraselmer commented on manual/cypher/cypher-docs/src/docs/dev/ql/call/index.asciidoc
> +The `YIELD` sub clause is used to explicitly select which of these result fields are returned as newly bound variables from the procedure call to the user or for further processing by the remaining q
"sub clause" -> "sub-clause" throughout

2016-10-24 09:41 UTC, petraselmer commented on manual/cypher/cypher-docs/src/docs/dev/ql/call/index.asciidoc
> +The `YIELD` sub clause is used to explicitly select which of these result fields are returned as newly bound variables from the procedure call to the user or for further processing by the remaining q
"newly bound" -> "newly-bound"

2016-10-24 09:43 UTC, petraselmer commented on manual/cypher/cypher-docs/src/docs/dev/ql/call/index.asciidoc
> +It is an error if a procedure call tries to rebind an already bound variable (i.e. a procedure call cannot shadow a variable that is already bound in the current scope).
"an already bound" -> "a previously bound" (all instances)

2016-10-24 09:44 UTC, petraselmer commented on manual/cypher/cypher-docs/src/docs/dev/ql/call/index.asciidoc
> +Inside a larger query, the records returned from a procedure call with explicit `YIELD` may be further filtered using a `WHERE` sub clause followed by a predicate (similar to `WITH ... WHERE ...`).
"with explicit `YIELD`" -> "with an explicit `YIELD`"

2016-10-24 09:45 UTC, petraselmer commented on manual/cypher/cypher-docs/src/docs/dev/ql/call/index.asciidoc
> +In a standalone procedure call only, `YIELD` may be omitted.
"In a standalone procedure call only, `YIELD` may be omitted."
->
"`YIELD` may be omitted in a standalone procedure call."

2016-10-24 09:47 UTC, petraselmer commented on manual/cypher/cypher-docs/src/docs/dev/ql/call/index.asciidoc
> +Calling a `VOID` procedures may only have a side effect and will not produce any result records and thus does neither allow nor require the use of `YIELD`.
I concur with @Mats-SX 's comment, but with the further additional change:
"thus does neither allow nor require the use of `YIELD`"
->
"thus neither allows nor requires the use of YIELD"

2016-10-24 10:07 UTC, petraselmer commented
@boggle please let me know once you have addressed the various comments etc. I will then undertake to get this content into the relevant repo, and close this PR.

2016-10-25 08:06 UTC, boggle commented
@petraselmer I updated the PR; could please you take this on and get the test and the manual content to the right place?

2016-10-25 18:08 UTC, petraselmer commented
Closing, as superseded by https://github.com/neo4j/neo4j-documentation/pull/1

2016-10-25 18:08 UTC, closed without merging