Fix so that dump logical prints everything without a regex
neo4j/neo4j pull request #8251
Opened 2016-10-25 09:41 UTC by martinfurmanski

2016-10-28 09:31 UTC, burqen requested changes
Looks good! Small format comment.

2016-10-28 09:31 UTC, burqen commented on tools/src/main/java/org/neo4j/tools/dump/DumpLogicalLog.java
> +            try ( IOCursor<LogEntry[]> cursor = new FilteringIOCursor<>( transactionCursor, new TransactionRegexCriteria( regex, timeZone ) ) )
Format, line too long. And while on it, line 127 could use a line break as well.

2016-10-31 09:29 UTC, burqen commented
@martinfurmanski Friendly ping about review being finished.

2016-11-08 09:55 UTC, martinfurmanski commented
@burqen Friendly ping about PR ready to merge.

2016-11-08 12:36 UTC, burqen approved these changes

2016-11-08 12:36 UTC, merged