Fail on missing configured auth plugin
neo4j/neo4j pull request #8290
Opened 2016-11-01 10:58 UTC by fickludd

If plugin authentication of authorization is enabled, but no respective auth plugin is found during service loading, the server will fail to start and give an appropriate error message.

2016-11-01 13:56 UTC, henriknyman requested changes

2016-11-01 13:56 UTC, henriknyman commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/auth/EnterpriseSecurityModule.java
> +        if ( missingAuthenticationRealm || missingAuthorizingRealm )
This is too strict. Since both settings are derived from `auth_providers` I think this will prevent you from combining auth providers.

2016-11-01 14:02 UTC, fickludd commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/auth/EnterpriseSecurityModule.java
> +        if ( missingAuthenticationRealm || missingAuthorizingRealm )
no, because this only fails if you explicitly put plugin_authentication_enabled=true, but no plugin authentication realm was loaded.

2016-11-01 14:04 UTC, henriknyman commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/auth/EnterpriseSecurityModule.java
> +        if ( missingAuthenticationRealm || missingAuthorizingRealm )
But plugin authentication enabled is a derived setting, so it will have a value of true if you configured a plugin auth provider

2016-11-03 08:49 UTC, Mats-SX commented on community/kernel/src/main/java/org/neo4j/kernel/impl/factory/EditionModule.java
> +                catch ( Exception e )
If we're being general, why not `Throwable`?

2016-11-03 08:49 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/auth/EnterpriseSecurityModule.java
> +        // Load plugin realms if a plugin provider in configured
Typo in comment: `in` -> `is`

2016-11-03 08:49 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/auth/EnterpriseSecurityModule.java
> +        if ( configuredRealms.stream().anyMatch( ( r ) -> r.startsWith( SecuritySettings.PLUGIN_REALM_NAME_PREFIX ) ) )
Parentheses around `r` in lambda superfluous.

2016-11-03 08:49 UTC, Mats-SX commented on enterprise/security/src/main/java/org/neo4j/server/security/enterprise/auth/plugin/PluginRealm.java
> +        return authPlugin != null || authenticationPlugin !=null;
Bad style: missing space

2016-11-22 10:31 UTC, Mats-SX commented
Is this PR abandoned? @fickludd

2016-11-22 12:23 UTC, closed without merging