Ephemeral file system file buffer allocation simplification
neo4j/neo4j pull request #8302
Opened 2016-11-03 10:49 UTC by MishaDemianenko

Update ephemeral file system to use 1KB buffer for new file by default.
In case if file data size over exceed available buffer capacity it will be doubled till enough space will be available.

2016-11-07 08:56 UTC, MishaDemianenko commented
@burqen fixed and retarget to 3.2

2016-11-07 09:44 UTC, chrisvest commented on community/io/src/test/java/org/neo4j/graphdb/mockfs/EphemeralFileSystemAbstraction.java
> -            while ( capacity( sizeIndex ) < totalAmount )
The comment is now out of date. It might not be a bad idea to restrict the doubling a bit.

2016-11-07 10:47 UTC, burqen commented on community/io/src/test/java/org/neo4j/graphdb/mockfs/EphemeralFileSystemAbstraction.java
> -            while ( capacity( sizeIndex ) < totalAmount )
Do you think about any specific scenario for when continue doubling in size would be a bad idea?
I think it is a reasonable trade off for simple code.

2016-11-07 10:49 UTC, burqen requested changes
@MishaDemianenko Review round finished. Let's wait for outcome from doubling-in-size-thread.

2016-11-07 13:30 UTC, MishaDemianenko commented on community/io/src/test/java/org/neo4j/graphdb/mockfs/EphemeralFileSystemAbstraction.java
> -            while ( capacity( sizeIndex ) < totalAmount )
@chrisvest you thinking about having some maximum size that if we reach that we just throw an exception?

2016-11-07 15:38 UTC, MishaDemianenko commented on community/io/src/test/java/org/neo4j/graphdb/mockfs/EphemeralFileSystemAbstraction.java
> -            while ( capacity( sizeIndex ) < totalAmount )
@chrisvest add some basic check and updated obsolete comment

2016-11-09 10:27 UTC, burqen approved these changes

2016-11-09 10:27 UTC, burqen commented
@MishaDemianenko I'm happy with this change. How about you @chrisvest ?

2016-11-09 10:36 UTC, chrisvest commented
@burqen Yeah, looks good.

2016-11-09 10:40 UTC, merged