Produce a warning when dbms.pagecache.memory.size is not configured
neo4j/neo4j pull request #8308
Opened 2016-11-04 10:57 UTC by chrisvest

2016-11-07 13:20 UTC, MishaDemianenko requested changes
Couple of comments

2016-11-07 13:20 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/graphdb/factory/GraphDatabaseSettings.java
>                    "Neo4j, and is heuristically set to 50% of RAM minus the max Java heap size." )
Now with default value as null with evaluation in a factory it's not clear from here what is a default value and where it's get calculated. 
As soon as you moved default value calculation from here to ConfiguringPageCacheFactory that makes that settings special in terms how we calculate default value and make it less clear.

2016-11-07 13:20 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/Configuration.java
> +            String defaultPageCacheMemory = ConfiguringPageCacheFactory.defaultHeuristicPageCacheMemory();
i also do not really like new way of evaluation of default value using `ConfiguringPageCacheFactory` and applying Bytes function to get the correct value, lets talk about it

2016-11-10 13:40 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/Configuration.java
> +            String defaultPageCacheMemory = ConfiguringPageCacheFactory.defaultHeuristicPageCacheMemory();
I can make it return a `long` for bytes. No big deal.

2016-11-10 13:54 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/graphdb/factory/GraphDatabaseSettings.java
>                    "Neo4j, and is heuristically set to 50% of RAM minus the max Java heap size." )
I'll update the text and make the default case more vague, so as to distance the setting from how the computation of the default page cache memory is implemented. This makes the documentation of the setting, only be about the setting.

2016-11-10 13:55 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/graphdb/factory/GraphDatabaseSettings.java
>                    "Neo4j, and is heuristically set to 50% of RAM minus the max Java heap size." )
The new computation is becoming too complicated to concisely explain anyway.

2016-11-10 13:56 UTC, chrisvest commented
@MishaDemianenko Please have another look.

2016-11-14 09:35 UTC, MishaDemianenko approved these changes

2016-11-14 10:16 UTC, merged

2016-11-14 10:33 UTC, benbc commented
@chrisvest I think this needs a changelog as it is effectively a change in the surface (we no longer support the default calculation).

2016-11-14 10:55 UTC, chrisvest commented
Thank you, @benbc. I have updated the description accordingly.