Add a close() method to the PageSwapperFactory interface
neo4j/neo4j pull request #8325
Opened 2016-11-08 10:51 UTC by chrisvest

This allows the page swapper factories to initialise internal resources in
`configure`, and release them in `close`.

This is useful for our block device integration.

2016-11-08 11:13 UTC, chrisvest commented
Note that there's a blockdevice PR that needs to be merged alongside this one.
/cc @burqen @magnusvejlstrup

2016-11-09 12:55 UTC, burqen requested changes
I have two inline comments and one general one:

There are some tests where we use `PageSwapperFactory` without a `PageCache` and in those cases we do not close it. This is not a problem with current implementation but looking at the code from an outside perspective I would expect an object with a close method to be closed after use and that it would be the responsibility of the user to do so.
My suggestion would be to take care of the cases where we do not close the `PageSwapperFactory`.

2016-11-09 12:55 UTC, burqen commented on community/io/src/main/java/org/neo4j/io/pagecache/PageSwapperFactory.java
> +    void close();
Would be nice with some javadoc for this method and some documentation on the lifecycle of a `PageSwapperFactory`.

2016-11-09 12:55 UTC, burqen commented on community/io/src/test/java/org/neo4j/adversaries/pagecache/AdversarialPageCache.java
> -        adversary.injectFailure( FileNotFoundException.class, IOException.class, SecurityException.class );
Should we not inject `IllegalStateException` since we updated PageCache.close to throw that?

2016-11-09 13:39 UTC, chrisvest commented
@burqen There you go.

2016-11-09 13:45 UTC, burqen commented
@chrisvest Nice! Still wondering about not closing the swapper when we use it without the PageCache.

2016-11-09 13:54 UTC, chrisvest commented
@burqen I don't think that ever happens outside of tests, but now that you mention it, it should happen in those tests.

2016-11-09 13:55 UTC, burqen commented
@chrisvest You mean _not_ closing the Swapper in those tests is actually what we _want_ to do? I don't see why that would be.

2016-11-09 14:12 UTC, chrisvest commented
@burqen Done.

2016-11-09 15:12 UTC, burqen commented
@chrisvest In `ConfiguringPageCacheFactory` we create a swapper in constructor. This swapper will only be added to a PageCache instance if we call `createPageCache()`, otherwise swapper will remain open.

Any ideas?

2016-11-09 15:22 UTC, burqen commented
After offline discussion with @chrisvest we reached this conclusion:

This is a transitional change and will be re-implemented soon. Therefore we are fine with the technical dept added in `ConfiguringPageCacheFactory`.

2016-11-09 15:22 UTC, merged