Certificates files elaboration in docs
neo4j/neo4j pull request #8337
Opened 2016-11-10 11:03 UTC by tiemevanveen

This was missing, took me while to find it in the changelogs..

2016-11-10 11:04 UTC, tiemevanveen commented
Same in `BoltKernelExtension.java` btw

2016-12-13 13:57 UTC, zhenlineo commented
Sorry to come back to your PR so late. Do you also mind to sign [CLA](https://neo4j.com/developer/cla/) so that we could merge you PR?

2016-12-13 15:33 UTC, tiemevanveen commented
Haha just for adding: "Certificates files must be named neo4j.cert and neo4j.key" ?

Done. See my email.

2016-12-13 15:45 UTC, zhenlineo commented
Thanks a lot. You are also welcome to add more of course!
We will merge the PR after it passes all tests later.
Thanks again for fixing the docs.

2016-12-19 10:33 UTC, jjaderberg requested changes

2016-12-19 10:33 UTC, jjaderberg commented on community/server/src/main/java/org/neo4j/server/configuration/ServerSettings.java
> +    Setting<File>
Where did the field name `certificates_directory` go?

2016-12-19 10:33 UTC, jjaderberg commented on community/server/src/main/java/org/neo4j/server/configuration/ServerSettings.java
> +    @Description( "Directory for storing certificates to be used by Neo4j for TLS connections. Certificates files must be named neo4j.cert and neo4j.key" )
`Certificates files` => `Certificate files`
Files and paths with italics (surrounded by underscore):
`neo4j.cert` => `_neo4j.cert_`
`neo4j.key` => `_neo4j.key_`

2016-12-19 14:07 UTC, tiemevanveen commented
@jjaderberg whoops.. dunno what went wrong there. Fixed

2016-12-19 14:08 UTC, tiemevanveen commented
You want me to retarget to 3.2 btw?

2016-12-20 10:40 UTC, jjaderberg approved these changes

2016-12-20 10:44 UTC, merged