DumpLogicalLog can dump transactions relevant to cc report
neo4j/neo4j pull request #8346
Opened 2016-11-11 09:43 UTC by tinwelint

after a consisistency checker has run a report is made, potentially including
incosistencies. DumpLogicalLog can be given a --ccfilter which should
point to such a report file. DumpLogicalLog will then only include transactions
which touches any of the records in the cc report and mark the records it
matched with a `<----` arrow to easier navigate.

2016-11-14 10:54 UTC, MishaDemianenko requested changes
Couple of comments, otherwise really nice idea!

2016-11-14 10:54 UTC, MishaDemianenko commented on tools/src/main/java/org/neo4j/tools/dump/DumpLogicalLog.java
> +    private static Function<LogEntry,String> parseSerializer( Args arguments, Predicate<LogEntry[]> filter,
`arguments` not used here

2016-11-14 10:54 UTC, MishaDemianenko commented on tools/src/main/java/org/neo4j/tools/dump/InconsistencyReportReader.java
> +            else if ( state == 1 || state == 2 )
state == 1 is impossible here

2016-11-14 10:54 UTC, MishaDemianenko commented on tools/src/main/java/org/neo4j/tools/dump/InconsistencyReportReader.java
> +                String entityType = entityType( line );
entity type load and propagation (line 84- 89) can be extracted since exactly the same code used in next brach

2016-11-14 15:18 UTC, tinwelint commented
@MishaDemianenko made some changes

2016-11-18 08:47 UTC, MishaDemianenko approved these changes

2016-11-18 12:29 UTC, merged