Fix bug on close in NeoStores
neo4j/neo4j pull request #8388
Opened 2016-11-17 11:08 UTC by davidegrohmann

If any store does not close cleanly but throws an exception, the
subsequents stores in store array are not gonna be closed.  This will
make the page cache to fail when shutdown due to still store files
mapped in it.  This change will make sure we attempt to close all the
stores even if exceptions are thrown.

2016-11-17 12:22 UTC, tinwelint commented
It's difficult to see the actual changes since 90% is checkstyle. For future commits, would it be possible to keep that separate?

2016-11-17 12:22 UTC, tinwelint commented on community/kernel/src/test/java/org/neo4j/kernel/impl/store/NeoStoresTest.java
> +            counts.rotate( nextTxId );
should you have a `fail(...)` here?

2016-11-17 13:05 UTC, chrisvest requested changes
The fix itself looks good, but the test can be improved and I think some of the stylistic changes can be improved as well.

2016-11-17 13:05 UTC, chrisvest commented on community/kernel/src/test/java/org/neo4j/kernel/impl/store/NeoStoresTest.java
> +            RuleChain.outerRule( exception ).around( pageCacheRule ).around( fs ).around( dir ).around( dsRule );
I think the file system rule should be around the page cache rule, so we don't close the file system before we close the files.

2016-11-17 13:05 UTC, chrisvest commented on community/kernel/src/test/java/org/neo4j/kernel/impl/store/NeoStoresTest.java
> +                        Position.LOG_VERSION, 12 ) );
Not a fan of breaking at the dot so far in. Can you break at the start of the parameter list instead?

2016-11-17 13:05 UTC, chrisvest commented on community/kernel/src/test/java/org/neo4j/kernel/impl/store/NeoStoresTest.java
> +                    0 );
For cases such as this, I'd also prefer breaking at the start of the parameter list, or introduce a static import for the constant.

2016-11-17 13:05 UTC, chrisvest commented on community/kernel/src/test/java/org/neo4j/kernel/impl/store/NeoStoresTest.java
> +            neoStore.close();
You also need a fail here, since you'd skip the asserts and checks in the catch clause if close doesn't throw.

2016-11-17 13:05 UTC, chrisvest commented on community/kernel/src/test/java/org/neo4j/kernel/impl/store/NeoStoresTest.java
> +                Cursor<NodeItem> nodeCursor = statement.getStoreStatement().acquireSingleNodeCursor( node ) )
This extra indentation looks like a mistake. Resource declarations look better when they are aligned in a try-with-resources statement.

2016-11-17 13:05 UTC, chrisvest commented on community/kernel/src/test/java/org/neo4j/kernel/impl/store/NeoStoresTest.java
> +                .put( property.propertyKeyId(), Pair.of( property, propertyRecordId ) );
Here I'd prefer to either break before `props`, or at the start of the parameter list.

2016-11-17 13:05 UTC, chrisvest commented on community/kernel/src/test/java/org/neo4j/kernel/impl/store/NeoStoresTest.java
> +                Cursor<NodeItem> nodeCursor = statement.getStoreStatement().acquireSingleNodeCursor( node ) )
This one got indented as well.

2016-11-17 13:05 UTC, chrisvest commented on community/kernel/src/test/java/org/neo4j/kernel/impl/store/NeoStoresTest.java
> +                Cursor<NodeItem> nodeCursor = statement.getStoreStatement().acquireSingleNodeCursor( node ) )
Another extra two-space indent.

2016-11-17 13:05 UTC, chrisvest commented on community/kernel/src/test/java/org/neo4j/kernel/impl/store/NeoStoresTest.java
> +                Cursor<NodeItem> nodeCursor = statement.getStoreStatement().acquireSingleNodeCursor( nodeId ) )
And another one.

2016-11-17 13:27 UTC, davidegrohmann commented on community/kernel/src/test/java/org/neo4j/kernel/impl/store/NeoStoresTest.java
> +            counts.rotate( nextTxId );
we can add that

2016-11-17 13:28 UTC, davidegrohmann commented on community/kernel/src/test/java/org/neo4j/kernel/impl/store/NeoStoresTest.java
> +            RuleChain.outerRule( exception ).around( pageCacheRule ).around( fs ).around( dir ).around( dsRule );
that's only formatting

2016-11-17 13:29 UTC, davidegrohmann commented
@chrisvest @tinwelint I'll revert the formatting mess

2016-11-17 13:34 UTC, davidegrohmann commented on community/kernel/src/test/java/org/neo4j/kernel/impl/store/NeoStoresTest.java
> +            neoStore.close();
done

2016-11-17 13:34 UTC, davidegrohmann commented on community/kernel/src/test/java/org/neo4j/kernel/impl/store/NeoStoresTest.java
> +            counts.rotate( nextTxId );
done

2016-11-17 13:38 UTC, davidegrohmann commented
@chrisvest @tinwelint reverted the formatting changes, many comments were on code I didn't touch at all.

2016-11-18 12:32 UTC, davidegrohmann commented
@chrisvest @tinwelint any news on this PR?

2016-11-18 12:34 UTC, chrisvest approved these changes
Looks good.

2016-11-18 13:59 UTC, merged