Value validation for indexed properties.
neo4j/neo4j pull request #8404
Opened 2016-11-18 21:50 UTC by MishaDemianenko

Introduce validation of property values for legacy and schema indexes.
Create validators for empty/null/allowable cases. Perform validation during property updated and index population.

2016-11-21 20:52 UTC, lutovich commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/IndexSimpleValueValidator.java
> +            IndexValueLengthValidator.INSTANCE.validate( ((String) value).getBytes() );
`getBytes()` here and in `IndexValueValidator` will cause decoding of chars and copying them in a newly allocated byte array. is this ok performance wise? maybe we can calculate bytes length manually?

2016-11-21 23:08 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/IndexSimpleValueValidator.java
> +            IndexValueLengthValidator.INSTANCE.validate( ((String) value).getBytes() );
you are obviously right, those guys where just automagically moved from LuceneDocumentStructure to a specific validator, maybe it's time to clean that as well even if that is not the goal of this pr...

2016-11-22 08:52 UTC, tinwelint commented on community/lucene-index/src/main/java/org/neo4j/index/impl/lucene/legacy/LuceneLegacyIndex.java
> +    protected void assertValidValue( Object value )
Looks like this methods isn't actually needed anymore, or it could at least still remain private static, couldn't it?

2016-11-22 08:53 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/IndexSimpleValueValidator.java
> +            IndexValueLengthValidator.INSTANCE.validate( ((String) value).getBytes() );
So schema indexes already did this, right? Then it's "OK" to add this slight extra garbage to legacy indexes as well imho

2016-11-22 09:42 UTC, tinwelint commented
@MishaDemianenko looks like it needs rebase

2016-11-22 09:43 UTC, tinwelint commented
In general I think this looks OK

2016-11-22 09:52 UTC, lutovich commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/IndexSimpleValueValidator.java
> +            IndexValueLengthValidator.INSTANCE.validate( ((String) value).getBytes() );
Never mind me. This validation has already been present for schema indexes just deeper in the call stack.

2016-11-22 09:52 UTC, MishaDemianenko commented on community/lucene-index/src/main/java/org/neo4j/index/impl/lucene/legacy/LuceneLegacyIndex.java
> +    protected void assertValidValue( Object value )
yeah that was sneaked experimentation, cleaned up

2016-11-22 09:54 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/IndexSimpleValueValidator.java
> +            IndexValueLengthValidator.INSTANCE.validate( ((String) value).getBytes() );
ok, that was the case for schema indexes before and we definitely can take a look into that in future if that will be required, i think for now it should be fine

2016-11-22 09:54 UTC, MishaDemianenko commented
@tinwelint cleaned up and rebased

2016-11-22 10:15 UTC, burqen requested changes
Small comments on test coverage. Looks good otherwise.

2016-11-22 10:15 UTC, burqen commented on community/kernel/src/test/java/org/neo4j/kernel/impl/api/IndexSimpleValueValidatorTest.java
> +        getValidator().validate( RandomStringUtils.randomAlphabetic( 450 ) );
Would be nice with a test for exactly `MAX_TERM_LENGTH` as well.

2016-11-22 10:15 UTC, burqen commented on community/kernel/src/test/java/org/neo4j/kernel/impl/api/IndexValueLengthValidatorTest.java
> +        INSTANCE.validate( RandomUtils.nextBytes( 13234 ) );
Test array of `MAX_TERM_LENGTH` here as well.

2016-11-22 10:15 UTC, burqen commented on community/kernel/src/test/java/org/neo4j/kernel/impl/api/IndexValueValidatorTest.java
> +        getValidator().validate( RandomUtils.nextBytes( 4556 ) );
Again, `MAX_TERM_LENGTH`

2016-11-22 10:22 UTC, burqen commented
@MishaDemianenko This would be a candidate for changelog 👍

2016-11-22 15:35 UTC, MishaDemianenko commented
@burqen additional tests added for all things except IndexValueValidatorTest since you can directly ask for those number of bytes for array since those will be encoded by array encoder. We can pretend and guess border line but i do not think we need to do that.
And change log label added and message provided

2016-11-22 15:39 UTC, burqen commented
@MishaDemianenko Looks good! Approved by me once green.

2016-11-22 15:39 UTC, burqen approved these changes

2016-11-23 09:58 UTC, burqen commented
@MishaDemianenko triggered another run for Linux build.
The muted test that failed, is that not related?

2016-11-23 22:33 UTC, MishaDemianenko commented
@burqen ok, rebased and old failure gone now it's failing with new 3.2 non related failures

2016-11-25 08:06 UTC, merged