Adds PageCursor#clear()
neo4j/neo4j pull request #8459
Opened 2016-11-30 12:22 UTC by tinwelint

which sets all bytes in the page to 0. Useful when reusing pages which have had
previous data in them. Clearing makes reused pages look like completely new ones.

2016-11-30 12:59 UTC, chrisvest requested changes

2016-11-30 12:59 UTC, chrisvest commented on community/io/src/test/java/org/neo4j/io/pagecache/PageCacheTest.java
> +            }
This test is racy without a `shouldRetry`.

2016-11-30 12:59 UTC, chrisvest commented on community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/MuninnPageCursor.java
> +    public void clear()
I'd prefer to call it `zapPage` or something like that, to avoid confusing it with `ByteBuffer.clear()`.

2016-11-30 12:59 UTC, chrisvest commented on community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/MuninnPageCursor.java
> +            offset = 0;
Why do you need to reset the offset as well? It sounds unrelated.

2016-11-30 12:59 UTC, chrisvest commented on community/io/src/test/java/org/neo4j/io/pagecache/impl/ByteBufferPage.java
> +        buffer.position( 0 );
No, just call `setMemory()` on `address()` and remove that `ZEROS` constant.

2016-11-30 12:59 UTC, chrisvest commented on community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/MuninnPageCursor.java
> +            outOfBounds = true;
I'm not seeing a test for this case.

2016-11-30 21:37 UTC, tinwelint commented on community/io/src/test/java/org/neo4j/io/pagecache/PageCacheTest.java
> +            }
oops

2016-11-30 21:38 UTC, tinwelint commented on community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/MuninnPageCursor.java
> +    public void clear()
sure, why not

2016-11-30 21:38 UTC, tinwelint commented on community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/MuninnPageCursor.java
> +            outOfBounds = true;
There is, comment it out and you'll see at least one test failing

2016-11-30 21:39 UTC, tinwelint commented on community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/MuninnPageCursor.java
> +            offset = 0;
It felt relevant, perhaps it isn't. For the driving use case it isn't necessary, but zapping it really feels like a `reset --hard`, so to speak, which sort of implies offset reset as well. Doesn't matter to me.

2016-11-30 21:40 UTC, tinwelint commented on community/io/src/test/java/org/neo4j/io/pagecache/impl/ByteBufferPage.java
> +        buffer.position( 0 );
Oh, so it's _always_ going to be a direct buffer?

2016-12-01 09:58 UTC, chrisvest commented on community/io/src/test/java/org/neo4j/io/pagecache/impl/ByteBufferPage.java
> +        buffer.position( 0 );
Yes, the constructor is checking this.

2016-12-02 08:13 UTC, burqen commented on community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/MuninnPageCursor.java
> +    public void clear()
How about `clean`?

2016-12-02 09:51 UTC, burqen commented
@chrisvest Comments addressed

2016-12-02 10:12 UTC, chrisvest approved these changes

2016-12-02 13:57 UTC, chrisvest commented
@burqen @tinwelint You forgot to implement this new method for `org.neo4j.index.gbptree.TestPageCursor`.

2016-12-02 14:38 UTC, burqen commented
@chrisvest Yeah, that was... embarrassing.

2016-12-03 21:17 UTC, merged