GBPTree recovery
neo4j/neo4j pull request #8481
Opened 2016-12-06 15:03 UTC by tinwelint

Changes to allow for recovery of a GBPTree.

There are two sub-parts related to recovery:

- Tree state (e.g. tree root id, generation etc.) comes in two pages, at least one of which will always be stable and consistent. An equivalent of GSPP, but for the tree itself.
- Checkpoint algorithm, creating consistent durable state of the tree between generations. Designed to be integrated with neo4j's checkpointing.

as well as various minor changes to allow tree to recover after a crash.

2016-12-08 10:22 UTC, ragadeeshu commented on community/index/src/main/java/org/neo4j/index/gbptree/Generation.java
> + * long: [S,S,S,S,U,U,U,U]
Might want to clarify what S and U  is here, unsigned ints representing generation?

2016-12-08 15:59 UTC, tinwelint commented on community/index/src/main/java/org/neo4j/index/gbptree/Generation.java
> + * long: [S,S,S,S,U,U,U,U]
Stands for **S**table and **U**nstable as the above comment mentions, you think it needs clarification?

2016-12-09 06:50 UTC, ragadeeshu commented on community/index/src/main/java/org/neo4j/index/gbptree/Generation.java
> + * long: [S,S,S,S,U,U,U,U]
Logic for composing and decomposing stable/unstable generation number (uint) to/from a single {@code long}.

2016-12-11 17:25 UTC, MishaDemianenko requested changes
Couple of comments,  packages for public-private api are still not clear

2016-12-11 17:25 UTC, MishaDemianenko commented on community/common/src/test/java/org/neo4j/test/rule/RandomRule.java
> +                    seed = methodSeed.value();
now It can be unfortunate that your specificSeed is ignored, maybe we can combine two way of specification of specific seed into one?

2016-12-11 17:25 UTC, MishaDemianenko commented on community/index/src/main/java/org/neo4j/index/gbptree/ConsistencyChecker.java
> +        cursor.setOffset( offset );
we should check that we did not have any error during reading all the pointer from cursor and retry it in case we have before we start any interpretation of results especially throwing exceptions

2016-12-11 17:25 UTC, MishaDemianenko commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +            // TODO use cursor.clear() when available
should be already there right?

2016-12-11 17:25 UTC, MishaDemianenko commented on community/index/src/main/java/org/neo4j/index/gbptree/TreeState.java
> +    static TreeState read( PageCursor cursor )
we should check that we did not have any errors while reading from cursor before returning TreeState

2016-12-11 17:25 UTC, MishaDemianenko commented on community/index/src/main/java/org/neo4j/index/gbptree/TreeStatePair.java
> +    private static TreeState selectNewestValidStateOrNull( Pair<TreeState,TreeState> states )
Shouldn't method return Optional<TreeState>?

2016-12-11 17:25 UTC, MishaDemianenko commented on community/index/src/main/java/org/neo4j/index/gbptree/TreeStatePair.java
> +        if ( stateA.isValid() != stateB.isValid() )
this looks like a code that should be in a TreeStateComparator class?

2016-12-11 17:25 UTC, MishaDemianenko commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +        if ( !writerTaken.compareAndSet( false, true ) )
now when we have a lock do we really need this guard?

2016-12-11 17:25 UTC, MishaDemianenko commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +        writerCheckpointMutex.lock();
looks like it's not only writer checkpointer mutex :)

2016-12-11 17:25 UTC, MishaDemianenko commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +        pagedFile.flushAndForce( ioLimiter );
why we doing this twice? (before (is it safe to do so?) and after the lock)

2016-12-11 17:25 UTC, MishaDemianenko commented on community/index/src/test/java/org/neo4j/index/gbptree/GBPTreeRecoveryTest.java
> +    private final File directory = new File( "/somewhere" );
please still use test directory to generate directory for your test, to guard from future modification like: oh i think we should use default fs here! push!

2016-12-11 17:25 UTC, MishaDemianenko commented on community/index/src/test/java/org/neo4j/index/gbptree/GBPTreeRecoveryTest.java
> +    private EphemeralFileSystemAbstraction fs = new EphemeralFileSystemAbstraction();
please use corresponding rule

2016-12-11 17:25 UTC, MishaDemianenko commented on community/index/src/main/java/org/neo4j/index/gbptree/GenSafePointer.java
>      // unsigned int
Can we rename this class to GenerationalPointer. GenSafe bring a feeling of char greediness when readability is the only victim.

2016-12-11 19:45 UTC, tinwelint commented on community/index/src/test/java/org/neo4j/index/gbptree/GBPTreeRecoveryTest.java
> +    private final File directory = new File( "/somewhere" );
Oh, right, a very good point!

2016-12-11 19:46 UTC, tinwelint commented on community/index/src/test/java/org/neo4j/index/gbptree/GBPTreeRecoveryTest.java
> +    private EphemeralFileSystemAbstraction fs = new EphemeralFileSystemAbstraction();
Then we have to move that rule to neo4j-common, no biggie

2016-12-11 19:48 UTC, tinwelint commented on community/index/src/main/java/org/neo4j/index/gbptree/GenSafePointer.java
>      // unsigned int
I don't quite understand. It's not just about this class, GSP is a core concept/term so it's a much bigger rename if that is to be done. We have an action point for taking a naming approach around gen vs generation and the likes later on.

2016-12-11 19:50 UTC, tinwelint commented
API/impl package will be a separate action later on, when there's no conflicting future development in another branch, not in this PR.

2016-12-11 20:00 UTC, chrisvest commented on community/index/src/test/java/org/neo4j/index/gbptree/GBPTreeRecoveryTest.java
> +    private EphemeralFileSystemAbstraction fs = new EphemeralFileSystemAbstraction();
A better home would be `neo4j-io`.

2016-12-11 20:10 UTC, tinwelint commented on community/common/src/test/java/org/neo4j/test/rule/RandomRule.java
> +                    seed = methodSeed.value();
👍

2016-12-11 20:12 UTC, tinwelint commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +            // TODO use cursor.clear() when available
This code has moved as part of free-list work and changed to use `zapPage()` so will ignore in this PR.

2016-12-11 20:13 UTC, tinwelint commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +        pagedFile.flushAndForce( ioLimiter );
Instead of explaining here I'll add comments to each line in `checkpoint()` method to make that clear.

2016-12-11 20:30 UTC, tinwelint commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +        if ( !writerTaken.compareAndSet( false, true ) )
`writerTaken` is a slightly different thing than the lock. We want an attempt to acquire multiple concurrent writers to fail, not to block and succeed when other writer as done. This to be certain that assumptions about users of this tree are correct.

2016-12-11 20:30 UTC, tinwelint commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +        writerCheckpointMutex.lock();
Yeah, being a little too safe here, it's not required here.

2016-12-11 20:39 UTC, MishaDemianenko commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +            // TODO use cursor.clear() when available
ok

2016-12-11 20:39 UTC, MishaDemianenko commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +        pagedFile.flushAndForce( ioLimiter );
sure sounds good

2016-12-11 20:40 UTC, MishaDemianenko commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +        if ( !writerTaken.compareAndSet( false, true ) )
ok

2016-12-11 20:41 UTC, MishaDemianenko commented on community/index/src/main/java/org/neo4j/index/gbptree/GenSafePointer.java
>      // unsigned int
sure, it's absolutely out of scope of this pr and if you have a note about that, it covers this comment

2016-12-11 20:43 UTC, tinwelint commented on community/index/src/main/java/org/neo4j/index/gbptree/TreeState.java
> +    static TreeState read( PageCursor cursor )
Yup correct, I believe GBPTree#read/writeState() should be changed to do that

2016-12-11 20:54 UTC, tinwelint commented on community/index/src/main/java/org/neo4j/index/gbptree/TreeStatePair.java
> +    private static TreeState selectNewestValidStateOrNull( Pair<TreeState,TreeState> states )
As a private method this becomes more of a matter of taste imho, not quite a "should". But with that said, Optional the calling methods a bit more readable and shorter.

2016-12-11 20:55 UTC, tinwelint commented on community/index/src/main/java/org/neo4j/index/gbptree/TreeStatePair.java
> +        if ( stateA.isValid() != stateB.isValid() )
What would be gained by doing that?

2016-12-11 21:26 UTC, tinwelint commented on community/index/src/main/java/org/neo4j/index/gbptree/ConsistencyChecker.java
> +        cursor.setOffset( offset );
The structure as a whole of this class as well as TreePrinter needs to be redesigned to better be able to properly read from page cursor. Although this is a test utility and works for what it does for the moment. Actually, I'll move them to src/test for the time being.

2016-12-12 10:08 UTC, MishaDemianenko approved these changes

2016-12-13 13:57 UTC, chrisvest reviewed
Looks good overall. I like that this was broken out into many small commits. I had a few comments, though.

2016-12-13 13:57 UTC, chrisvest commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +        }
The reason you are using the write page lock here is because you don't want to deal with retry right? You are okay with this causing the page to be marked as dirty?

2016-12-13 13:57 UTC, chrisvest commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +            monitor.checkpointCompleted();
I think we can allow ourselves to use `IOLimiter.unlimited()` within this critical section, since it ought to complete as quickly as possible, in order to not interfere with our write throughput.

2016-12-13 13:57 UTC, chrisvest commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +            }
If we somehow don't succeed, then we'll never release the `writerCheckpointMutex`. Is that intentional? I'd block all future writers, and check pointing.

2016-12-13 13:57 UTC, chrisvest commented on community/index/src/test/java/org/neo4j/index/gbptree/InternalTreeLogicTest.java
> +        // when and key to remove exists in internal
`when and` what?

2016-12-13 13:57 UTC, chrisvest commented on community/index/src/main/java/org/neo4j/index/Hit.java
> +     * because value instances can be immutable and change within a result set to be overwritten with the next hit.
These two descriptions are hard to parse. Are KEY and VALUE supposed to be containers of immutable objects, or what exactly is mutating?

2016-12-13 13:57 UTC, chrisvest commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
>              pagedFile.flushAndForce( ioLimiter );
To minimise the amount of time in this critical section, use `IOLimiter.unlimited()`.

2016-12-13 13:57 UTC, chrisvest commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
>              pagedFile.flushAndForce( ioLimiter );
Or the `flushAndForce()` method that doesn't take an `IOLimiter`.

2016-12-13 13:57 UTC, chrisvest commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
>              pagedFile.flushAndForce( ioLimiter );
Same as above.

2016-12-13 13:57 UTC, chrisvest commented on community/index/src/test/java/org/neo4j/index/gbptree/ThrowingRunnable.java
> +        return new Runnable()
Lambda?

2016-12-13 13:58 UTC, chrisvest commented
@burqen @tinwelint Look through my "hidden" comments as well. GitHub incorrectly thinks they've been addressed.

2016-12-13 15:13 UTC, tinwelint commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +            }
I think it'll call `releaseWriter` if it doesn't succeed and `releaseWriter` will unlock the mutex, won't it?

2016-12-13 15:13 UTC, tinwelint commented on community/index/src/test/java/org/neo4j/index/gbptree/InternalTreeLogicTest.java
> +        // when and key to remove exists in internal
Probably a comment moved up from a lower part of the test and just put a when in front. Removing it.

2016-12-13 15:13 UTC, tinwelint commented on community/index/src/test/java/org/neo4j/index/gbptree/ThrowingRunnable.java
> +        return new Runnable()
Yes

2016-12-13 15:13 UTC, tinwelint commented on community/index/src/main/java/org/neo4j/index/Hit.java
> +     * because value instances can be immutable and change within a result set to be overwritten with the next hit.
Typo: immutable --> mutable

2016-12-13 15:14 UTC, tinwelint commented
@chrisvest hopefully I found your hidden comments as well. Fixed the issues you highlighted and commented on the one about `releaseWriter`. Do you agree with that comment?

2016-12-14 02:48 UTC, chrisvest commented on community/index/src/main/java/org/neo4j/index/gbptree/GBPTree.java
> +            }
Correct, I misread the code.

2016-12-14 07:39 UTC, merged