Increased use of NodeIndexSeek to wider range of cases
neo4j/neo4j pull request #8500
Opened 2016-12-12 14:51 UTC by eebus

* Equality predicates on expressions of map literals and variables of map type
* Index Nested Loop joins even when incoming horizon contained a query plan

2016-12-12 15:00 UTC, eebus commented
![](https://github.trello.services/images/mini-trello-icon.png) [GH# 8463 USING INDEX causes error even though property value comparisons are now supported](https://trello.com/c/BGwoyjGi/53-gh-8463-using-index-causes-error-even-though-property-value-comparisons-are-now-supported)

2016-12-12 15:00 UTC, eebus commented
![](https://github.trello.services/images/mini-trello-icon.png) [Allow NodeIndexSeek on predicates that involve other node properties](https://trello.com/c/CDVPYF3Q/58-allow-nodeindexseek-on-predicates-that-involve-other-node-properties)

2016-12-12 18:41 UTC, systay requested changes

2016-12-12 18:41 UTC, systay commented on community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/IndexNestedLoopJoinAcceptanceTest.scala
> +  test("should use index on literal value") {
This test and the next two tests has nothing to do with NestedIndexLoopJoins

2016-12-12 18:41 UTC, systay commented on community/cypher/frontend-3.1/src/main/scala/org/neo4j/cypher/internal/frontend/v3_1/ast/Clause.scala
> +//      case _: Property => false
This line should be removed, right?

2016-12-13 16:05 UTC, eebus commented
![](https://github.trello.services/images/mini-trello-icon.png) [[3.0.3] No index hints possible with values from LOAD CSV row](https://trello.com/c/Y0tov1LD/70-3-0-3-no-index-hints-possible-with-values-from-load-csv-row)

2016-12-15 14:09 UTC, Mats-SX commented on community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/IndexNestedLoopJoinAcceptanceTest.scala
> +        | WHERE f.id={id: 123}.id
Hah! Nice.

2016-12-15 14:09 UTC, Mats-SX commented on community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/SemanticErrorAcceptanceTest.scala
> +      "match (n:Person) using index n:Person(name) where n.name = 'a' OR n.name = 'b' return n",
Why was this changed? Are we now supporting queries on the form that was replaced here?

2016-12-15 14:09 UTC, Mats-SX commented on community/cypher/frontend-3.1/src/main/scala/org/neo4j/cypher/internal/frontend/v3_1/ast/Clause.scala
> -      case _: Property => false
Is this the only actual change??

2016-12-15 15:15 UTC, eebus commented on community/cypher/frontend-3.1/src/main/scala/org/neo4j/cypher/internal/frontend/v3_1/ast/Clause.scala
> -      case _: Property => false
This and the change in the file cartesianProductsOrValueJoins.scala

2016-12-15 15:31 UTC, craigtaverner commented on community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/SemanticErrorAcceptanceTest.scala
> +      "match (n:Person) using index n:Person(name) where n.name = 'a' OR n.name = 'b' return n",
Correct. We support 'Nested Index Loop Joins' for this case. But the error can be generated for other cases, so this test for error message needed a different query to generate that error.

2016-12-16 08:29 UTC, systay approved these changes

2016-12-16 08:31 UTC, systay commented on community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/IndexNestedLoopJoinAcceptanceTest.scala
> +        | WHERE f.id={id: 123}.id
Nice test, but does it really belong here? This is not handled by the NIJ component, right?

2016-12-16 08:32 UTC, systay commented on community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/LoadCsvAcceptanceTest.scala
> +      assertStats(result, propertiesWritten = 6)
Should we not also test that the index was actually used?

2016-12-16 08:40 UTC, eebus commented on community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/IndexNestedLoopJoinAcceptanceTest.scala
> +        | WHERE f.id={id: 123}.id
Agree

2016-12-16 09:03 UTC, eebus commented on community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/LoadCsvAcceptanceTest.scala
> +      assertStats(result, propertiesWritten = 6)
Yes

2016-12-21 08:10 UTC, merged