Kernel transaction state handling update
neo4j/neo4j pull request #8532
Opened 2016-12-20 15:12 UTC by MishaDemianenko

Introduce transaction status that encapsulate all the possible transaction state and transitions around them.
Give much more clear understanding in what state transaction is now and what are possible transitions.

Now transaction can be in one of the states: OPEN, CLOSING, CLOSED and SHUTDOWN.
Also transaction can be terminated while it's OPEN or CLOSING.
Typical transaction lifecycle is: OPEN (transaction initialized and user work with it) -> CLOSING (transaction close in progress) -> CLOSED (transaction closed).

SHUTDOWN status used only in case when we shutdown database and transaction can be marked as SHUTDOWN only in case if it's OPEN.
SHUTDOWN transactions can't be closed/committed.

2017-01-11 12:57 UTC, tinwelint commented
Not sure about the tools compilation issue, perhaps a rebase would help, although it probably doesn't matter since this PR doesn't touch those things

2017-01-11 14:55 UTC, MishaDemianenko commented
@tinwelint that was because PR was based on 3.2 version with broken ha robustness, rebased and now it should be fine

2017-01-12 08:41 UTC, tinwelint commented
Failed on unrelated flaky test, it's fine

2017-01-12 08:52 UTC, tinwelint requested changes
Just a few comments. I like the nature of TransactionStatus and that it gets rid of many volatile variables and a lock!

2017-01-12 08:52 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/KernelTransactionImplementation.java
> +                        "Transaction terminated since database is shutting down." );
I wonder if this message is correct. A transaction is shut down in KTI#dispose(), which may be called for various reasons, one of them shutting down the database.

2017-01-12 08:52 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/KernelTransactionImplementation.java
> +                        "Transaction is already closing. Repeated execution of transactions are not allowed." );
I wonder if this message is correct. Above we've checked `transactionStatus.closing()`, which at this point must be false, so this transaction isn't in the process of closing.

Also status is set as `TransactionTerminated`, can we be sure of that?

2017-01-12 08:52 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/KernelTransactionImplementation.java
> +        public boolean closing()
Looks like `closing()` and `shutdown()` have a lot in common, everything except some parameters, no

2017-01-12 16:16 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/KernelTransactionImplementation.java
> +                        "Transaction terminated since database is shutting down." );
message updated

2017-01-12 16:16 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/KernelTransactionImplementation.java
> +                        "Transaction is already closing. Repeated execution of transactions are not allowed." );
restore old IllegalStateException for this case

2017-01-12 16:17 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/KernelTransactionImplementation.java
> +        public boolean closing()
yep, method extracted

2017-01-12 16:17 UTC, MishaDemianenko commented
@tinwelint updated

2017-01-13 10:45 UTC, merged