Move PageCacheRule into IO module our of kernel
neo4j/neo4j pull request #8563
Opened 2016-12-30 15:08 UTC by MishaDemianenko

Move PageCacheRule into io module to be accessible for all users that does not require kernel module.
Split existing PageCacheRule into base PageCacheRule that is moved to io module and ConfigurablePageCacheRule that allow additional configuration by supplier configuration.

2017-01-02 15:57 UTC, burqen requested changes
Looks good! Some small comments.
... well other than the build failures... that are possible to recreate locally

2017-01-02 15:57 UTC, burqen commented on community/common/src/test/java/org/neo4j/test/rule/ExternalResource.java
> + * A better version of {@link org.junit.rules.ExternalResource} that properly handles exceptions in {@link #after(boolean)}.
Line break

2017-01-02 15:57 UTC, burqen commented on tools/src/main/java/org/neo4j/tools/dump/DumpCountsStore.java
> +                Collections.emptyList() );
To much line break

2017-01-02 15:57 UTC, burqen commented on community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/StandalonePageCacheFactory.java
> +
The private constructor for `StandalonePageCacheFactory` was lost when `ConfigurableStandalonePageCacheFactory` needed to extended it. I think it should be added again.

2017-01-03 07:46 UTC, burqen commented
@MishaDemianenko Ready to merge once green.

2017-01-03 08:21 UTC, burqen approved these changes

2017-01-03 10:03 UTC, MishaDemianenko commented
@burqen there was a problem with incorrect cache page size in newly extracted rule and that was causing new rule to be so much slower then default one. That explains why some of the tests have problems with new rule but not with old one. Now that should be fixed and all of them should work.
That change is part of last commit feel free to take a look :)

2017-01-04 08:01 UTC, burqen commented
@MishaDemianenko Fix looks good. There is a compilation failure in `ha-robustness` though.

2017-01-04 08:53 UTC, MishaDemianenko commented
@burqen lets merge it then and i will take a look into ha-robustness to make it work then?

2017-01-04 13:23 UTC, merged