Added a way to override default values in config for docs
neo4j/neo4j pull request #8604
Opened 2017-01-11 15:40 UTC by spacecowboy

Some settings are calculated at runtime and depend on the current
machine. This is problematic for documentation which uses the default
values and prints them in the manual. This change adds an Annotation
which can specify what to  put in the manual if the actual default
value is not suitable.

Also added the necessary plumbing to access the information in the
annotations via the Config class.

2017-01-17 09:44 UTC, praveenag approved these changes

2017-01-20 13:22 UTC, jjaderberg requested changes
This is a nice way to handle defaults that can't be documented. Can we expose whether a setting is deprecated and what its valid values restrictions are in a similar way?

2017-01-20 13:22 UTC, jjaderberg commented on community/configuration/src/main/java/org/neo4j/configuration/ConfigOptions.java
> +import javax.swing.text.html.Option;
Over-zealous IDE? Both new imports are unused.

2017-01-20 13:22 UTC, jjaderberg commented on community/kernel/src/main/java/org/neo4j/kernel/configuration/ConnectorValidator.java
> +import java.util.Collections;
unused

2017-02-02 16:22 UTC, spacecowboy commented
@jjaderberg corrected the unused imports. I will do the deprecated work separately

2017-02-03 08:41 UTC, jjaderberg approved these changes

2017-02-03 08:41 UTC, merged