NativeLabelScanStore works with consistency checker
neo4j/neo4j pull request #8610
Opened 2017-01-12 13:02 UTC by tinwelint

Which means reducing LabelScanStore (and friends) interface and to some extent consistency checker to consistency check label scan store slightly differently.

2017-01-12 13:21 UTC, tinwelint commented
Hmm, not all builds were run on this one

2017-01-12 14:43 UTC, chrisvest commented
@tinwelint That's a new feature of our PR builds; to only run tests deemed relevant by some dependency analysis.

2017-01-12 14:48 UTC, MishaDemianenko commented
@chrisvest test and builds are different things 🦄  😋

2017-01-12 14:52 UTC, tinwelint commented
@chrisvest @MishaDemianenko I know, but to run no tests at all.... doooon't think so. Actually there was a hickup in CI where other PRs didn't run properly either. Triggered them manually, now the `Run Linux Tests` is there, which is wasn't at all before

2017-01-12 14:59 UTC, tinwelint commented on community/lucene-index/src/main/java/org/neo4j/kernel/api/impl/labelscan/LuceneLabelScanStore.java
> +        return allNodeLabelRanges().maxCount() == 0;
Hmm wait, the `allNodeLabelRanges()` should be in a try-with-resource, will fix that

2017-01-13 15:18 UTC, tinwelint commented
Failed on unrelated flaky test, it's fine.

2017-01-17 18:20 UTC, MishaDemianenko requested changes
Couple of mostly minor comments, otherwise looks really good!

2017-01-17 18:20 UTC, MishaDemianenko commented on community/consistency-check/src/main/java/org/neo4j/consistency/ConsistencyCheckService.java
> +            IndexStoreView indexStoreView = new NeoStoreIndexStoreView( LockService.NO_LOCK_SERVICE, neoStores );
it looks like we do not need IndexStoreView and operationalMode anymore here?

2017-01-17 18:20 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/helpers/progress/ProgressMonitorFactory.java
> +        public ProgressListener progressForUnknownPart( String part )
that progress will be completely invisible on a output correct?

2017-01-17 18:20 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/labelscan/LabelScanValue.java
> +    LabelScanValue( long bits )
it looks like we do not really need to have this constructor it's used only internally in this class

2017-01-17 18:20 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/labelscan/NativeAllEntriesLabelScanReader.java
> +        void setdRange( long idRange, long[][] labels, int slots )
`setdRange` have or missing `I` or additional `d`

2017-01-17 18:20 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/labelscan/NativeAllEntriesLabelScanReader.java
> +                for ( RawCursor<Hit<LabelScanKey,LabelScanValue>,IOException> cursor : cursors )
hm...is it really safe to share cursors between iterator and reader? next call to iterator will gonna have influence on the first one?

2017-01-17 18:20 UTC, MishaDemianenko commented on community/kernel/src/test/java/org/neo4j/kernel/impl/index/labelscan/NativeAllEntriesLabelScanReaderTest.java
> +    private static long count( Labels[] data )
this method is not used

2017-01-17 18:20 UTC, MishaDemianenko commented on community/primitive-collections/src/main/java/org/neo4j/collection/primitive/PrimitiveIntCollections.java
> +    public static int[] dedup( int[] values )
surprisingly OperationsFacade have method that is almost duplicate of this one

2017-01-17 18:20 UTC, MishaDemianenko commented on community/primitive-collections/src/main/java/org/neo4j/collection/primitive/PrimitiveIntCollections.java
> +            for ( int j = 0; j < unique; j++ )
i think we can make second index start from i to remove duplicates?

2017-01-17 18:20 UTC, MishaDemianenko commented on community/primitive-collections/src/main/java/org/neo4j/collection/primitive/PrimitiveIntCollections.java
> +    public static int[] dedup( int[] values )
also please give it a full name `deduplicate` or `unique` or soemthing else :)

2017-01-17 18:20 UTC, MishaDemianenko commented on community/primitive-collections/src/main/java/org/neo4j/collection/primitive/PrimitiveIntCollections.java
> +    public static int[] dedup( int[] values )
this and next comment are also applicable for PrimitiveLongCollections

2017-01-18 08:39 UTC, tinwelint commented on community/consistency-check/src/main/java/org/neo4j/consistency/ConsistencyCheckService.java
> +            IndexStoreView indexStoreView = new NeoStoreIndexStoreView( LockService.NO_LOCK_SERVICE, neoStores );
Actually this is a mistake, the IndexStoreView should be used as the dependency into the kernel extensions. However it's not reasonable that CC should be able build the label scan store from store on startup to check consistency of it later, but that's apparently how the code did. I don't think we have a single test which starts a CC on a store w/o label scan store though.

I can restore the old behaviour, i.e. using those dependencies again.

2017-01-18 08:42 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/helpers/progress/ProgressMonitorFactory.java
> +        public ProgressListener progressForUnknownPart( String part )
Yes, we'll have to see if we can do better later on, OK

2017-01-18 09:27 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/labelscan/NativeAllEntriesLabelScanReader.java
> +                for ( RawCursor<Hit<LabelScanKey,LabelScanValue>,IOException> cursor : cursors )
Don't think cursors are shared. Iterator is responsible for moving cursors (those that are on the current range) forwards and cram their range data into a NodeLabelRange, which is returned out from the iterator.

Although this comment reminded me about a fix we did after this PR branch, which is that the NodeLabelRange instances can be processed by multiple threads once they leave the iterator, so changed ReusableNodeLabelRange to not be reused, instead creating new instances every time.

2017-01-18 09:28 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/labelscan/NativeAllEntriesLabelScanReader.java
> +        void setdRange( long idRange, long[][] labels, int slots )
Gone now, see comment above.

2017-01-18 09:29 UTC, tinwelint commented on community/primitive-collections/src/main/java/org/neo4j/collection/primitive/PrimitiveIntCollections.java
> +    public static int[] dedup( int[] values )
Oh, then that was duplicated from NodeItemHelper, which this `dedup` method was moved from. Will deduplicate that method as well :)

2017-01-18 09:35 UTC, tinwelint commented on community/primitive-collections/src/main/java/org/neo4j/collection/primitive/PrimitiveIntCollections.java
> +            for ( int j = 0; j < unique; j++ )
It goes the other way around, doesn't it, from 0 to `unique` which starts at 0 and grows.

2017-01-18 14:18 UTC, MishaDemianenko commented
@tinwelint it's ready for second round right?

2017-01-18 17:35 UTC, tinwelint commented
@MishaDemianenko yup, sorry didn't mention that

2017-01-19 10:13 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/labelscan/NativeAllEntriesLabelScanReader.java
> +                for ( RawCursor<Hit<LabelScanKey,LabelScanValue>,IOException> cursor : cursors )
ok

2017-01-19 10:14 UTC, MishaDemianenko approved these changes

2017-01-19 10:14 UTC, merged