Allow all ASCII characters between '!' and '~' except ':' and ',' for usernames
neo4j/neo4j pull request #8652
Opened 2017-01-19 14:21 UTC by eebus

2017-01-20 15:48 UTC, fickludd requested changes

2017-01-20 15:48 UTC, fickludd commented on community/security/src/test/java/org/neo4j/server/security/auth/FileUserRepositoryTest.java
> +                "Username ',' contains illegal characters. Use simple ascii characters and numbers." );
"... Use simple ascii characters and numbers." <- this part of the error message should maybe be changed?

2017-01-20 15:48 UTC, fickludd commented on community/security/src/test/java/org/neo4j/server/security/auth/FileUserRepositoryTest.java
> +                "Username 'withå' contains illegal characters. Use simple ascii characters and numbers." );
Eh, why do we not allow 'å' btw... we could take UTF-8 alpha-numerics + a nice number of separators. Nice for internationalization. But maybe in the next iteration.

2017-01-20 15:48 UTC, fickludd commented on enterprise/security/src/test/java/org/neo4j/server/security/enterprise/auth/AuthProceduresInteractionTestBase.java
> +                "Username ':åss!' contains illegal characters." );
I think it slightly better if the usernames here and in the assert above are exactly the same, as the difference is supposed to be in valid vs. invalid password. We test the different illegal characters in the `FileUserRepositoryTest`.

2017-01-20 15:48 UTC, fickludd commented on community/security/src/test/java/org/neo4j/server/security/auth/FileUserRepositoryTest.java
> +                "Username 'withå' contains illegal characters. Use simple ascii characters and numbers." );
actually, let's leave that for now.

2017-01-23 10:04 UTC, eebus commented
Opening new PR against 3.1

2017-01-23 10:04 UTC, closed without merging