Remove ability to configure page size.
neo4j/neo4j pull request #8741
Opened 2017-02-01 10:19 UTC by ragadeeshu

Also adds a way to specify it via the PageCahceRule, so that it can be used for
testing.

2017-02-01 10:57 UTC, chrisvest requested changes
I'd like greater separation of product and testing features.

2017-02-01 10:57 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/kernel/impl/pagecache/ConfiguringPageCacheFactory.java
> +    private static final int pageSize = getInteger( ConfiguringPageCacheFactory.class, "pageSize", 8192 );
`static finals` should be in the top of the class.

2017-02-01 10:57 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/kernel/impl/pagecache/ConfiguringPageCacheFactory.java
>      }
I'd do this juggling in a `TestConfiguringPageCacheFactory` that extends and overrides the original `ConfiguringPageCacheFactory`. The `PageCacheRule` can then use that when configuring its page cache.

2017-02-01 12:54 UTC, ragadeeshu commented
@chrisvest Like this?

2017-02-01 15:27 UTC, chrisvest approved these changes

2017-02-01 15:27 UTC, chrisvest commented
Yep.

2017-02-02 14:10 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/store/BatchingNeoStores.java
> +                pagecache_memory.name(), valueOf( config.pageCacheMemory() ) ),
Just noticed the `config` object still has its `pageSize()` method. Can that be removed?

2017-02-02 15:32 UTC, ragadeeshu commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/store/BatchingNeoStores.java
> +                pagecache_memory.name(), valueOf( config.pageCacheMemory() ) ),
Nice catch, will look into it.

2017-02-03 12:43 UTC, ragadeeshu commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/store/BatchingNeoStores.java
> +                pagecache_memory.name(), valueOf( config.pageCacheMemory() ) ),
@chrisvest removed

2017-02-03 13:02 UTC, merged