Extend GraphDatabaseService for procedures to start transactions in new threads
neo4j/neo4j pull request #8770
Opened 2017-02-06 13:42 UTC by OliviaYtterbrink

This was previously not allowed since it meant that procedure authors could bypass security. Now all new transactions will be limited with the same access level as the procedure.

2017-02-07 14:37 UTC, fickludd approved these changes

2017-02-15 13:46 UTC, craigtaverner requested changes
Perhaps worth reviewing just how apoc creates threads and transactions and make a test that mimics that? Hopefully the existing tests are close enough, but if not, we could add more.

2017-02-15 13:46 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/impl/factory/DataSourceModule.java
>          // Register injected private API components: useful to have available in procedures to access the kernel etc.
This comment should move as well, I assume

2017-02-15 13:46 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/impl/proc/ProcedureGDBFacadeSPI.java
>      public KernelTransaction beginTransaction( KernelTransaction.Type type, SecurityContext securityContext, long timeout )
Should we really provide an API to create transactions with alternative security context?

2017-02-15 13:46 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/impl/proc/ProcedureGDBFacadeSPI.java
> +            KernelTransaction kernelTx = sourceModule.kernelAPI.get().newTransaction( type, this.securityContext, timeout );
Perhaps this makes it safe? Using this.securityContext. What about also renaming the method parameter to 'ignoredSecurityContext' to make the code look a bit safer?

2017-02-15 13:46 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/OperationsFacade.java
>              ctx.put( Context.KERNEL_TRANSACTION, tx );
Since ProcedureGDBFacadeSPI has a currentTransaction method, do we need the kernel transaction in the context also?

2017-02-15 13:46 UTC, craigtaverner commented on integrationtests/src/test/java/org/neo4j/procedure/ProcedureIT.java
>          Runnable doIt = () -> {
Perhaps rename the procedure, now that it is actually supported. Perhaps `createNodeInNewTransaction()`?

2017-02-15 14:59 UTC, OliviaYtterbrink commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/OperationsFacade.java
>              ctx.put( Context.KERNEL_TRANSACTION, tx );
`currentTransaction` is only available inside GraphDatabaseFacade. Builtin procedures that need access to kernel transaction depend on it being in the context.

2017-02-17 15:34 UTC, craigtaverner approved these changes

2017-02-17 15:35 UTC, merged