Unflake TestBranchedData
neo4j/neo4j pull request #8776
Opened 2017-02-07 11:53 UTC by tinwelint

Problem being that after a role switch there were 3 big transactions w/ indexing and everything
taking place which, on some JVMs, caused full GC pauses on up to 2s. This was a problem because
the heartbeat timeout in ClusterManager is 2s and so the cluster would go into an unstable state
and try to switch role right when the transaction would commit, causing the test to fail.

This commit changes this test so that it no longer performs these big transactions.
There were no apparent reason for those transactions being so big, potentially it could be
(as the comment in the test suggests) that it wanted the lucene index files to change underneath.
Although there were no checking of those files, rather it would most likely use the suggested
file changes to verify that a branch + store-copy was actually performed.

Now instead the test installs a monitor to assert that a store-copy is performed on the
correct instances after the repair has been done.

2017-02-08 13:20 UTC, burqen requested changes
Changes look good. 1.5 comments

2017-02-08 13:20 UTC, burqen commented on enterprise/ha/src/main/java/org/neo4j/kernel/ha/cluster/SwitchToSlave.java
>      public interface Monitor
Nice docs and defaults. Anonymous `SwitchToSlave.Monitor` in `HighAvailabilityMemberStateMachineTest`  can be updated to not override with no-op methods.

2017-02-08 13:20 UTC, burqen commented on enterprise/ha/src/test/java/org/neo4j/ha/TestBranchedData.java
>      private void retryOnTransactionFailure( ThrowingAction<Exception> transaction ) throws Exception
We could use the new `RetryHandler` here. Outside PR scope though, so feel free to ignore.

2017-02-08 13:27 UTC, tinwelint commented on enterprise/ha/src/test/java/org/neo4j/ha/TestBranchedData.java
>      private void retryOnTransactionFailure( ThrowingAction<Exception> transaction ) throws Exception
Ah yes we could, that thought may have flown through my head, but was ignored before it exited!

2017-02-08 13:27 UTC, tinwelint commented on enterprise/ha/src/main/java/org/neo4j/kernel/ha/cluster/SwitchToSlave.java
>      public interface Monitor
Good catch

2017-02-08 16:38 UTC, tinwelint commented
@burqen comments fixed

2017-02-09 07:29 UTC, burqen approved these changes

2017-02-09 07:29 UTC, merged