More consistent DynamicIndexStoreViewIT test time
neo4j/neo4j pull request #8781
Opened 2017-02-07 15:14 UTC by tinwelint

This test takes a couple of seconds to run normally, but now and then takes
up to minutes or hours!

Problem was that there was a race where five threads were created, threads which
busy-looped on making transactions revolving nodes and properties.
Such transactions acquire the schema read lock. The main test thread would,
after starting these other threads, go on to creating an index, a transaction
which needs to acquire the schema write lock. If those other threads had started
before the main thread would have came as far as acquiring the schema write lock
the test would get itself into a situation where the main thread could face
starvation and be waiting for an unknown amount of time since the other threads
would constantly acquire the schema read lock, overlapping with each other
and basically never let the main thread create the index.

This commit starts the other threads, but let them wait for a count down latch
and let them loose as soon as the index has been created, letting them race
with the population of that index. Number of concurrent updates fed into the
index populator has been verified to be the same as before this change.

2017-02-08 12:59 UTC, burqen requested changes
Looks good. One small comment.

2017-02-08 12:59 UTC, burqen commented on community/neo4j/src/test/java/schema/DynamicIndexStoreViewIT.java
> +                Populator populator = new Populator( database, counter, startSignal );
A `ThreadPool` to manage `populators` would be nice, even though slightly outside scope of this PR.

2017-02-08 15:57 UTC, tinwelint commented on community/neo4j/src/test/java/schema/DynamicIndexStoreViewIT.java
> +                Populator populator = new Populator( database, counter, startSignal );
Sure, could do it while I'm here anyway

2017-02-08 16:38 UTC, tinwelint commented
@burqen fixed

2017-02-09 07:26 UTC, burqen approved these changes

2017-02-09 07:26 UTC, merged