Added a MarkForTermination, to terminate procedures
neo4j/neo4j pull request #8831
Opened 2017-02-16 10:10 UTC by eebus

changelog: Added a `MarkForTermination`, to terminate procedures that will allow procedures to terminate the transaction with out having access to the `KernelTransaction` API.

2017-02-21 11:33 UTC, fickludd requested changes
Some comments.

2017-02-21 11:33 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/proc/ProcedureTransactionProvider.java
> +
OMG checkstyle!

2017-02-21 11:33 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/procedure/ProcedureTransaction.java
> +     * rolled back.
This can only be called from the owning thread?

2017-02-21 11:33 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/procedure/ProcedureTransaction.java
> +     * Calling this method on an already closed transaction has no effect.
Very nice doc!

2017-02-21 11:33 UTC, fickludd commented on integrationtests/src/test/java/org/neo4j/procedure/ProcedureIT.java
> +        Result result = db.execute( "CALL org.neo4j.procedure.failure" );
I think calling the procedure `failingPersonCount` would make this test much easier to read. Took a little time to realize why a node was needed!

2017-02-21 11:33 UTC, fickludd commented on integrationtests/src/test/java/org/neo4j/procedure/ProcedureIT.java
> -        public KernelTransaction ktx;
Now we are no longer using any unsafe component here... should we reflect that somehow in the test? It feels nice in general!

2017-02-21 13:00 UTC, eebus commented on integrationtests/src/test/java/org/neo4j/procedure/ProcedureIT.java
> -        public KernelTransaction ktx;
Right will remove line 1148

2017-02-24 11:25 UTC, fickludd approved these changes

2017-02-24 11:27 UTC, merged