Add entry point for `CompositeIndexQuery`
neo4j/neo4j pull request #8847
Opened 2017-02-17 14:35 UTC by ragadeeshu

2017-02-20 15:46 UTC, craigtaverner requested changes

2017-02-20 15:46 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/api/ReadOperations.java
> +    PrimitiveLongIterator nodesGetFromCompositeIndexSeek( NewIndexDescriptor index, CompositeIndexQuery query )
Do we need this? It looks superceded by the indexQuery method above, which covers composite indexes also.

2017-02-20 15:46 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/ConstraintEnforcingEntityOperations.java
> +        return entityReadOperations.nodesGetFromCompositeIndexSeek( state, index, query );
Looks like this could be removed, once indexQuery() supports multiple predicates

2017-02-20 16:08 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/kernel/api/ReadOperations.java
> +    PrimitiveLongIterator nodesGetFromCompositeIndexSeek( NewIndexDescriptor index, CompositeIndexQuery query )
No we do not need that. We'll remove it when we get to adding composite index support to `indexQuery`.

2017-02-20 16:08 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/ConstraintEnforcingEntityOperations.java
> +        return entityReadOperations.nodesGetFromCompositeIndexSeek( state, index, query );
Yep!

2017-02-21 13:01 UTC, craigtaverner commented on community/kernel/src/test/java/org/neo4j/kernel/api/index/NonUniqueIndexAccessorCompatibility.java
> +    @Test
Will we remove these older tests and the older API once the new stuff is well tested?

2017-02-21 13:07 UTC, chrisvest commented on community/kernel/src/test/java/org/neo4j/kernel/api/index/NonUniqueIndexAccessorCompatibility.java
> +    @Test
That's what I was thinking.

2017-02-22 11:09 UTC, chrisvest commented
@craigtaverner Please take a look at this. I think we should get this and #8854 merged in, before embarking on building out full support for composite index querying in the kernel.

2017-02-22 11:31 UTC, ragadeeshu reviewed
Some minor comments

2017-02-22 11:31 UTC, ragadeeshu commented on community/common/src/main/java/org/neo4j/kernel/api/exceptions/Status.java
> +                "The request did not contain the properties required by the index." ),
Should this text be changed perhaps?

2017-02-22 11:31 UTC, ragadeeshu commented on community/kernel/src/main/java/org/neo4j/kernel/api/ReadOperations.java
> +    PrimitiveLongIterator indexQuery( NewIndexDescriptor index, IndexQuery... predicates ) throws IndexNotFoundKernelException;
Some kind of javadoc?

2017-02-22 11:31 UTC, ragadeeshu commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/StateHandlingStatementOperations.java
> +        IndexQuery predicate = predicates[0];
Do we validate that the propertyID of the IndexQuery matches the indexdescriptor?

2017-02-22 11:37 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/StateHandlingStatementOperations.java
> +        IndexQuery predicate = predicates[0];
No, we don't.

2017-02-22 15:59 UTC, craigtaverner commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/spi/v2_3/TransactionBoundQueryContext.scala
> +          readOps.indexQuery(index, IndexQuery.range(index.property, null, false, limit.endPoint, limit.isInclusive))
Would it be easier to read if we had methods `rangeFrom(...)` and `rangeTo(...)` instead of passing null values to `range(...)`?

2017-02-22 15:59 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/api/schema_new/IndexQuery.java
> +public abstract class IndexQuery
Since we want javadoc for the ReadOperations.indexQuery, so should we have javadoc here.

2017-02-22 15:59 UTC, craigtaverner commented on community/kernel/src/test/java/org/neo4j/kernel/api/index/NonUniqueIndexAccessorCompatibility.java
> +        assertThat( query( IndexQuery.exists( 1 ) ), equalTo( asList( 1L, 2L, 3L ) ) );
exists is statically imported.

2017-02-22 16:00 UTC, craigtaverner approved these changes

2017-02-23 08:37 UTC, chrisvest commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/spi/v2_3/TransactionBoundQueryContext.scala
> +          readOps.indexQuery(index, IndexQuery.range(index.property, null, false, limit.endPoint, limit.isInclusive))
Maybe that would be nice to have, but it's not a very common occurrence, and it increases the surface area that needs to be tested, so I don't want to do this now.

2017-02-23 09:14 UTC, merged