Ability to set unlimited bad tolerance in import tool
neo4j/neo4j pull request #8967
Opened 2017-03-07 15:19 UTC by tinwelint

by using --bad-tolerance -

2017-03-07 16:49 UTC, spacecowboy commented
Nice, then I didn't have to do it all myself (see https://github.com/neo4j/neo4j/pull/8968)

But why did you pick `-` as the infinity value? I think that might be confusing. A naked dash is typically used to indicate that stdin should be read.

for example:
http://unix.stackexchange.com/questions/41828/what-does-dash-at-the-end-of-a-command-mean

which means some users could be confused by `neo4j-import --bad-tolerance -`

2017-03-07 17:41 UTC, tinwelint commented
@spacecowboy right you are, what would be better?

2017-03-07 21:49 UTC, spacecowboy commented
@tinwelint `-1` comes to mind, it also matches what the constant is. otherwise, a string matching a positive action like `true` perhaps

2017-03-10 09:24 UTC, tinwelint commented
Good idea, I'd say `true` in that case. `-1` feels like a developer thing, not a user thing to me.

2017-03-13 15:57 UTC, burqen commented
@tinwelint Can we have some labels on this guy please.

2017-03-13 16:59 UTC, tinwelint commented
@spacecowboy did you already merge related stuff to this commit?

2017-03-14 08:28 UTC, spacecowboy commented
@tinwelint I have made the almost equivalent changes for `neo4j-admin` on 3.2. It contains a subset of your commit and should not conflict (git will complain about a conflict but the code should be identical).

Ref: https://github.com/neo4j/neo4j/pull/8968

2017-03-15 15:51 UTC, MishaDemianenko requested changes
One usability and minor comment, good otherwise

2017-03-15 15:51 UTC, MishaDemianenko commented on community/import-tool/src/main/java/org/neo4j/tooling/ImportTool.java
> +    private static final String UNLIMITED = "-";
As @spacecowboy already mentioned that would be much more understandable to use `-1` as representation of unlimited value

2017-03-15 15:51 UTC, MishaDemianenko commented on community/import-tool/src/test/java/org/neo4j/tooling/ImportToolTest.java
> +        List<String> nodeIds = new ArrayList<>();
will `Collections.nCopies( 10_000, "A" )` do the trick instead?

2017-03-17 14:20 UTC, tinwelint commented on community/import-tool/src/main/java/org/neo4j/tooling/ImportTool.java
> +    private static final String UNLIMITED = "-";
I do think -1 isn't particularly user friendly, is it? I'd vote for `true`, as discussed above

2017-03-17 14:44 UTC, MishaDemianenko commented on community/import-tool/src/main/java/org/neo4j/tooling/ImportTool.java
> +    private static final String UNLIMITED = "-";
do you mean `neo4j-import --bad-tolerance -unlimited=true` or smt else?

2017-03-17 15:00 UTC, tinwelint commented on community/import-tool/src/main/java/org/neo4j/tooling/ImportTool.java
> +    private static final String UNLIMITED = "-";
`--bad-tolerance=true`

I think `--bad-tolerance=-1` is so developer:y

2017-03-17 15:03 UTC, MishaDemianenko approved these changes

2017-03-17 20:55 UTC, merged