Update QueryLoggerIT queries log file check.
neo4j/neo4j pull request #8972
Opened 2017-03-07 22:46 UTC by MishaDemianenko

2017-03-08 09:19 UTC, spacecowboy requested changes
This no longer actually tests rotation.

The test needs to fail if there is no `query.log.N` file(s). It's fine to only check for one rotated file but you need to check for it.

2017-03-08 09:22 UTC, MishaDemianenko commented
@spacecowboy can i check that i have multiple query log files instead?

2017-03-08 09:30 UTC, spacecowboy commented
@MishaDemianenko yes. the problem in windows was that a new file could not be created because it's a rename operation and the file was still open. So if you just check that there are more than one file present with name `query.log*` that should be fine.

2017-03-08 10:46 UTC, MishaDemianenko commented
@spacecowboy updated

2017-03-08 11:46 UTC, spacecowboy commented on enterprise/query-logging/src/test/java/org/neo4j/kernel/impl/query/QueryLoggerIT.java
> +        assertTrue( "Expected log file to have at least one log entry", loggedQueries.size() >= 1 );
Hmm. Do we miss any log statements due to the rotation here? Wouldn't they all end up in the buffer and then sent to the new log file? In that case could assert that `loggedQueries.size() == 100` (the number of queries sent).

2017-03-08 11:46 UTC, spacecowboy approved these changes

2017-03-13 11:03 UTC, MishaDemianenko commented
ping @ragadeeshu

2017-03-13 13:02 UTC, MishaDemianenko commented
@ragadeeshu updated with additional check

2017-03-13 15:16 UTC, merged