Composite uniqueness constraint enforcement on nodeSetProperty
neo4j/neo4j pull request #8984
Opened 2017-03-09 10:05 UTC by fickludd

Enforce composite uniqueness constrains on nodeSetProperty. 

This PR introduces the new class `NodeSchemaMatcher` that finds indexes or constraints that are valid for a node. This class is now used to find the relevant uniqueness constraints when setting a property, and the relevant indexes to update in the TxState.

Composite uniqueness constraints were already enforced on nodeAddLabel, but this PR adds some tests to verify this behaviour.

2017-03-09 14:15 UTC, craigtaverner requested changes

2017-03-09 14:15 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/ConstraintEnforcingEntityOperations.java
> +    private Iterator<ConstraintDescriptor> getConstraintsForProperty( KernelStatement state, int propertyId )
At first I interpreted this method name as implying constraints matching exactly one property, but I can see now that it matches all constraints that involve at least the one property. I wonder if another method name might reduce the chance of this misunderstanding?

2017-03-09 14:15 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/ConstraintEnforcingEntityOperations.java
>                  nMatched++;
Would it be safer/easier to check if values does not contain null at the end, instead of tracking nMatched?

2017-03-09 14:15 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/state/IndexTxStateUpdater.java
> +                    if ( values != null )
This check leads me to expect that `getOrderedPropertyValues` will return null if the node does not have all the properties required by the index, but no such check seemed to exist in the `getOrderedPropertyValues` method.

2017-03-09 14:15 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/state/IndexTxStateUpdater.java
> +            }
Feels like we should have a check for any nulls in values array, and return null array, since calling code seems to rely on that, right?

2017-03-09 14:16 UTC, craigtaverner approved these changes

2017-03-10 14:13 UTC, chrisvest approved these changes
It looks okay to me. Just a few questions.

2017-03-10 14:13 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/ConstraintEnforcingEntityOperations.java
> +            DefinedProperty specialProperty )
`specialProperty` is not a very clarifying name, and it's hard to track the consequences of this value around the code.

Could you add some comments to help future selves? Is there a better name we could use for it?

2017-03-10 14:13 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/schema/NodeSchemaMatcher.java
> +        this.readOps = readOps;
You are avoiding the security access checks and statement.assertOpen checks by grabbing this as a field up front?

2017-03-10 15:16 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/schema/NodeSchemaMatcher.java
> +        this.readOps = readOps;
I didn't think much about that, as far as I can tell this follows the same path as before this PR. If that is broken we should look at it more and fix in separate PR.

2017-03-11 13:18 UTC, merged