Add page cache hit metric into query profile report
neo4j/neo4j pull request #8987
Opened 2017-03-09 14:24 UTC by MishaDemianenko

Using newly introduced page cache hit metric it should be much more easier
to see how particular query use data that are already in page cache.
Each page cache `hit` indicate that data from cache was used and there was no page fault
when particular price of data request was served.
Now when hit metric added into query execution profile statistic we have possibility to
investigate how particular query utilize page cache.

2017-03-10 13:36 UTC, systay requested changes
Looks good, except for the introduction of a kernel dependency in the SPI

2017-03-10 13:36 UTC, systay commented on community/cypher/cypher-compiler-3.2/src/main/scala/org/neo4j/cypher/internal/compiler/v3_2/spi/QueryContext.scala
> +import org.neo4j.io.pagecache.tracing.cursor.PageCursorTracer
We should not introduce any new store dependencies here. Instead, create a trait in the compiler module, and implement it in the compatibility package. There you can have your kernel dependencies.

2017-03-10 13:36 UTC, systay commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/spi/v3_2/TransactionBoundQueryContext.scala
> +    transactionalContext.statement.asInstanceOf[KernelStatement].getPageCursorTracer
Shouldn't `getPageCursorTracer` be in the `Statement` interface?

2017-03-13 16:55 UTC, MishaDemianenko commented
@systay updated!

2017-03-14 08:37 UTC, thobe commented
In `CompositeIndexAcceptanceTest`: _Cannot get single property of multi-property index_.

Based on a bad base revision?

2017-03-14 09:09 UTC, systay approved these changes

2017-03-14 09:15 UTC, MishaDemianenko commented
@thobe yep, since i will need to rebase anyway will wait for green build to do that :)

2017-03-15 07:40 UTC, MishaDemianenko commented
@thobe rebased

2017-03-15 12:54 UTC, merged