3.2 remove node property descriptor
neo4j/neo4j pull request #8991
Opened 2017-03-09 20:18 UTC by ragadeeshu

Depends on https://github.com/neo4j/neo4j/pull/8988

2017-03-14 10:59 UTC, fickludd requested changes
This is not really clean yet. Needs another iteration.

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/api/schema/EntityPropertyDescriptor.java
> +    public int getPropertyId()
This class (`EntityPropertyDescriptor`) is going away soon too, right?

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/api/schema_new/LabelSchemaDescriptor.java
> +    public LabelSchemaDescriptor( int labelId, int... propertyIds )
This should not be public, we only construct via the factory.

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/api/schema_new/constaints/ConstraintBoundary.java
> +                final int[] propertyKeyIds = new int[]{schema.getPropertyId()};
You can just do `schema.getPropertyIds()` to get the real array.

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/IndexProcedures.java
>          //TODO: Support composite indexes
Made card for fixing these TODOs

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/IndexProcedures.java
> +            final int[] propertyKeyIds = new int[]{propertyKeyId};
`getPropertyIds()` as above

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/StateHandlingStatementOperations.java
> -    private NewIndexDescriptor indexGetForLabelAndPropertyKey( KernelStatement state, LabelSchemaDescriptor descriptor )
Nice =)

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/coreapi/schema/PropertyNameUtils.java
> +                false ? descriptor.getPropertyIds() : new int[]{descriptor.getPropertyId()};
Whaat?

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/coreapi/schema/PropertyNameUtils.java
> +                false ? descriptor.getPropertyIds() : new int[]{descriptor.getPropertyId()};
Whaat 2

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/factory/GraphDatabaseFacade.java
> +            final int[] propertyKeyIds = new int[]{propertyId};
`getPropertyIds`

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/util/dbstructure/DbStructureArgumentFormatter.java
>                      format( "new NodePropertyExistenceConstraint( new NodePropertyDescriptor( %s, %s ) )", labelId,
Missed `NodePropertyDescriptor`

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/main/java/org/neo4j/kernel/impl/util/dbstructure/DbStructureArgumentFormatter.java
>                      format( "new RelationshipPropertyExistenceConstraint( new NodePropertyDescriptor( %s, %s ) )",
Missed `NodePropertyDescriptor`

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/test/java/org/neo4j/kernel/builtinprocs/ResampleIndexProcedureTest.java
> +        final int[] propertyKeyIds = new int[]{456};
`getPropertyIds`

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/test/java/org/neo4j/kernel/impl/api/state/SchemaTransactionStateTest.java
> +        final int[] propertyKeyIds = new int[]{propertyKey};
ping

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/command/Commands.java
> +                NewIndexDescriptorFactory.forLabel( descriptor.getLabelId(), descriptor.getPropertyId() ),
Can still be `forSchema`

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/test/java/org/neo4j/kernel/impl/transaction/command/HighIdTransactionApplierTest.java
> +                NO_INDEX_PROVIDER.getProviderDescriptor(), 20, SchemaDescriptorFactory.forLabel( 1, propertyKeyIds1 ) ) );
`getPropertyIds`

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/test/java/org/neo4j/kernel/impl/util/dbstructure/DbStructureArgumentFormatterTest.java
> +        final int[] propertyKeyIds = new int[]{42};
not needed

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/test/java/org/neo4j/kernel/impl/util/dbstructure/DbStructureCollectorTest.java
> +        final int[] propertyKeyIds = new int[]{1};
ping

2017-03-14 10:59 UTC, fickludd commented on community/kernel/src/test/java/org/neo4j/kernel/impl/util/dbstructure/DbStructureInvocationTracingAcceptanceTest.java
> +        final int[] propertyKeyIds = new int[]{0};
ping

2017-03-14 12:31 UTC, ragadeeshu commented on community/kernel/src/main/java/org/neo4j/kernel/api/schema/EntityPropertyDescriptor.java
> +    public int getPropertyId()
As soon as we remove the RelationshipPropertyDescriptor!

2017-03-14 12:35 UTC, ragadeeshu commented on community/kernel/src/main/java/org/neo4j/kernel/api/schema_new/constaints/ConstraintBoundary.java
> +                final int[] propertyKeyIds = new int[]{schema.getPropertyId()};
If you look closely this is even more stupid, I can simply pass the schema on.

2017-03-14 12:36 UTC, ragadeeshu commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/IndexProcedures.java
>          //TODO: Support composite indexes
:+1:

2017-03-14 13:40 UTC, fickludd requested changes
4 more

2017-03-14 13:40 UTC, fickludd commented on community/kernel/src/test/java/org/neo4j/kernel/impl/api/index/IndexIT.java
> +        descriptor = SchemaDescriptorFactory.forLabel( labelId1, propertyKeyIds );
Another one

2017-03-14 13:40 UTC, fickludd commented on community/kernel/src/test/java/org/neo4j/kernel/impl/api/integrationtest/UniquenessConstraintValidationIT.java
> +                .uniqueIndexGetForLabelAndPropertyKey( SchemaDescriptorFactory.forLabel( labelId, propertyKeyIds ) );
ping

2017-03-14 13:40 UTC, fickludd commented on community/kernel/src/test/java/org/neo4j/kernel/impl/api/integrationtest/UniquenessConstraintValidationIT.java
> +                .uniqueIndexGetForLabelAndPropertyKey( SchemaDescriptorFactory.forLabel( labelId, propertyKeyIds ) );
ping

2017-03-14 13:40 UTC, fickludd commented on community/kernel/src/test/java/org/neo4j/kernel/impl/util/dbstructure/CineastsDbStructure.java
> +        visitor.visitUniqueConstraint( new UniquenessConstraint( SchemaDescriptorFactory.forLabel( 2, propertyKeyIds ) ), "CONSTRAINT ON ( user:User ) ASSERT user.login IS UNIQUE" );
pingeling

2017-03-14 14:34 UTC, fickludd approved these changes

2017-03-16 09:11 UTC, ragadeeshu commented
@fickludd those HA test pass locally, flaky?

2017-03-16 22:08 UTC, fickludd commented
@ragadeeshu yeah, maybe they are ok. Now needs rebase anyway though.

2017-03-19 22:27 UTC, merged