Tell user that consistency check is running
neo4j/neo4j pull request #9023
Opened 2017-03-14 10:40 UTC by spacecowboy

2017-03-16 16:48 UTC, praveenag requested changes

2017-03-16 16:48 UTC, praveenag commented on community/command-line/src/main/java/org/neo4j/commandline/admin/AdminTool.java
> +        failure( message, e, 1 );
It might be useful to extract `1, 2,3` as useful constants or enums to indicate what the code means.

2017-03-16 16:48 UTC, praveenag commented on enterprise/backup/src/main/java/org/neo4j/backup/OnlineBackupCommand.java
> +                outsideWorld.stdOutLine( "Doing consistency check..." );
"Performing consistency check" seems like a better fit (I am not a native speaker though :/)

2017-03-17 09:39 UTC, spacecowboy commented on enterprise/backup/src/main/java/org/neo4j/backup/OnlineBackupCommand.java
> +                outsideWorld.stdOutLine( "Doing consistency check..." );
I think they are both fine. I did `Doing` because it matches what we say for the import above:

> Doing full backup...

2017-03-17 09:50 UTC, spacecowboy commented on community/command-line/src/main/java/org/neo4j/commandline/admin/AdminTool.java
> +        failure( message, e, 1 );
extracted as constants

2017-03-17 14:28 UTC, praveenag approved these changes

2017-03-17 14:48 UTC, merged