Close index resources properly.
neo4j/neo4j pull request #9029
Opened 2017-03-14 16:00 UTC by MishaDemianenko

2017-03-14 16:02 UTC, MishaDemianenko commented
🔴  **N.B!** PR should be null merged since 3.1 and above are fixed by separate PR.

2017-03-16 08:25 UTC, burqen requested changes
There are quite a few calls to `index.query` in this test. Do we not need to close all of them?

2017-03-16 09:19 UTC, MishaDemianenko commented
@burqen change is exact copy of changes done to 3.1-3.x branches current solution works for them ..

2017-03-16 09:26 UTC, burqen approved these changes

2017-03-16 12:13 UTC, merged