throw exception if policy does not exist
neo4j/neo4j pull request #9076
Opened 2017-03-22 12:33 UTC by martinfurmanski

The plugins can now throw procedure exceptions and the server policies
plugin will throw a ProcedureCallFailed if the supplied policy name
does not exist.

2017-03-22 13:04 UTC, zhenlineo requested changes

2017-03-22 13:04 UTC, zhenlineo commented on enterprise/causal-clustering/src/main/java/org/neo4j/causalclustering/load_balancing/plugins/server_policies/Policies.java
>      public static final String POLICY_KEY = "load_balancing.policy"; // TODO: move somewhere (driver support package?)
Can we change this key to something else?
One plan is to pass routing context via bolt url, in we go down that road, then it is really a bad idea to have a `.` in the parameters as it requires a skip in url.

I would vote for `policy` or `load_balancing_policy`.

2017-03-23 09:41 UTC, digitalstain commented
Just a note that this also allows for overriding the default default policy, which is a change in behaviour in addition to the exception being thrown.
Looks good to me.

2017-03-23 10:07 UTC, martinfurmanski commented
@digitalstain That is not accurate I think! What you describe is captured by shouldAllowOverridingDefaultPolicy and that has not changed. There is a change in behaviour here however, expressed in the change of other tests!

2017-03-23 10:39 UTC, digitalstain commented
@martinfurmanski Correct, my bad. Still looks good to me.

2017-03-23 15:19 UTC, merged