3.2 remove neo4j shared
neo4j/neo4j pull request #9083
Opened 2017-03-23 11:34 UTC by praveenag

- Standardised the way `neo4j-backup`, `neo4j-shell`, `neo4j-import`, `neo4j-admin` works
- Remove `neo4j_shared.sh` being sourced into the scripts and instead use in place replacement.

2017-03-23 14:35 UTC, spacecowboy requested changes
In addition to the failure in ant, we should also stop copying `neo4j-shared.sh` to the tarball. It will need to be excluded in

* https://github.com/neo4j/neo4j/blob/3.2/packaging/standalone/standalone-community/src/main/assemblies/community-unix-dist.xml

and 

* https://github.com/neo4j/neo4j/blob/3.2/packaging/standalone/standalone-enterprise/src/main/assemblies/enterprise-unix-dist.xml

2017-03-23 14:35 UTC, spacecowboy commented on packaging/standalone/build.xml
> +      <arg value="/placeholder_for_neo4j_shared/r src/main/distribution/shell-scripts/bin/neo4j-shared.sh"/>
This doesn't work. Maven output on my machine:

```
[INFO] Executing tasks

main:

find-shell-zip:
     [echo] Checking if /home/jonas/work/neo4j/cypher-shell.zip exists: true

extract-shell-zip:
     [echo] Unzipping...
    [unzip] Expanding: /home/jonas/work/neo4j/cypher-shell.zip into /home/jonas/work/neo4j/packaging/standalone/src/main/distribution
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-antrun-plugin:1.6:run (copy-neo4j-shared-script) @ neo4j-standalone ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ packaging-build ---
[INFO] Executing tasks

main:

copy-neo4j-shared:

copy-neo4j-shared-for:
     [echo] Copying neo4j_shared to neo4j
[INFO] 
[INFO] --- maven-jar-plugin:2.4:test-jar (attach-test-jar) @ packaging-build ---
     [exec] sed: can't read /placeholder_for_neo4j_shared/r src/main/distribution/shell-scripts/bin/neo4j-shared.sh: No such file or directory
[INFO] Building jar: /home/jonas/work/neo4j/packaging/target/packaging-build-3.2.0-SNAPSHOT-tests.jar
     [exec] Result: 2
     [echo] Replacing placeholder text in neo4j
     [exec] sed: can't read s/placeholder_for_neo4j_shared//g: No such file or directory
     [exec] Result: 2

copy-neo4j-shared-for:
     [echo] Copying neo4j_shared to neo4j-admin
     [exec] sed: can't read /placeholder_for_neo4j_shared/r src/main/distribution/shell-scripts/bin/neo4j-shared.sh: No such file or directory
     [exec] Result: 2
     [echo] Replacing placeholder text in neo4j-admin
     [exec] sed: can't read s/placeholder_for_neo4j_shared//g: No such file or directory
     [exec] Result: 2

copy-neo4j-shared-for:
     [echo] Copying neo4j_shared to neo4j-backup
     [exec] sed: can't read /placeholder_for_neo4j_shared/r src/main/distribution/shell-scripts/bin/neo4j-shared.sh: No such file or directory
     [exec] Result: 2
     [echo] Replacing placeholder text in neo4j-backup
     [exec] sed: can't read s/placeholder_for_neo4j_shared//g: No such file or directory
     [exec] Result: 2

copy-neo4j-shared-for:
     [echo] Copying neo4j_shared to neo4j-import
     [exec] sed: can't read /placeholder_for_neo4j_shared/r src/main/distribution/shell-scripts/bin/neo4j-shared.sh: No such file or directory
     [exec] Result: 2
     [echo] Replacing placeholder text in neo4j-import
     [exec] sed: can't read s/placeholder_for_neo4j_shared//g: No such file or directory
     [exec] Result: 2

copy-neo4j-shared-for:
     [echo] Copying neo4j_shared to neo4j-shell
     [exec] sed: can't read /placeholder_for_neo4j_shared/r src/main/distribution/shell-scripts/bin/neo4j-shared.sh: No such file or directory
     [exec] Result: 2
     [echo] Replacing placeholder text in neo4j-shell
     [exec] sed: can't read s/placeholder_for_neo4j_shared//g: No such file or directory
     [exec] Result: 2
```

2017-03-28 08:27 UTC, spacecowboy commented
@praveenag 

The shell tests fail. Reason is that the scripts have incorrect permissions, as listed by github:

```
100755 → 100644
```

2017-03-28 11:49 UTC, srbaker requested changes
Once these things are moved to shared per the comments, the individual scripts become: _shared bits_ + `call_main_class` and nothing more.

2017-03-28 11:49 UTC, srbaker commented on packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-shell.m4
> +[[ "${TRACE:-}" ]] && set -o xtrace
These two lines can go in the shared file. They should be the same for every script.

2017-03-28 11:49 UTC, srbaker commented on packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-admin
> +setup_heap() {
This can also go in the shared file.

2017-03-28 11:49 UTC, srbaker commented on packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-admin
> +setup_heap
No reason why this can't go in `call_main_class` in the heap file.

2017-03-28 11:58 UTC, srbaker requested changes

2017-03-28 11:58 UTC, srbaker commented on packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-backup
>  #!/bin/bash
I realize this isn't a recent change, but the shebang lines should all be `#!/usr/bin/env bash`

2017-03-28 14:46 UTC, spacecowboy commented on packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-admin
> +setup_heap
only neo4j-admin should call this particular heap logic so it can't go in the general call_main_class function though.

2017-03-28 15:04 UTC, spacecowboy approved these changes
OK, let's get this in already

2017-03-28 16:31 UTC, merged