Allow skip bad entries logging during import
neo4j/neo4j pull request #9103
Opened 2017-03-28 09:55 UTC by MishaDemianenko

Introduce new import tool option: `skip-bad-entries-logging` that will allow to skip logging of all bad entries.
Default value of new option: false

2017-03-28 10:00 UTC, tinwelint approved these changes
Great that you also deferred the message string creation, which could be expensive.

2017-03-28 10:00 UTC, tinwelint commented on community/import-tool/src/main/java/org/neo4j/tooling/ImportTool.java
> +                "<true/false>", "Whether or not log bad entries detected during import."),
Whether or not `to skip` log`ging` bad entries detected during import

2017-03-28 10:00 UTC, tinwelint requested changes
Oh, the little change in the option description

2017-03-28 10:15 UTC, MishaDemianenko commented
@tinwelint updated :)

2017-03-31 07:10 UTC, tinwelint approved these changes

2017-03-31 07:11 UTC, merged