Only check uniqueness constraints on actual changes
neo4j/neo4j pull request #9157
Opened 2017-04-05 13:35 UTC by thobe

Skip checking if a property is re-assigned to the same value.
Skip checking if a label is added that already was assigned.

This avoids a deadlock scenario between concurrent MERGE queries, where the MERGE was followed by re-assignment of the same property. This is quite a common pattern, especially to bulk-re-assign all expected properties of the node.

Example query: `MERGE (user:User{id:$user.id}) SET user = $user` (where there is a uniqueness constraint on `(user:User) / user.id`

2017-04-05 13:36 UTC, thobe commented
The code where the fix is implemented has changed greatly in `3.2`, so this needs quite a bit of care when forward-merging. @pontusmelke and me know what is needed, but it isn't hard to figure out.

2017-04-10 11:05 UTC, burqen requested changes
Changes look good. Just have some small comments.

2017-04-10 11:05 UTC, burqen commented on community/kernel/src/test/java/org/neo4j/test/ConfigBuilder.java
> +    public ConfigBuilder and( Setting<?> key, String value )
May I suggest some javadoc here that points out that this will throw `NullPointerException` if called before `configure( ... )`.

2017-04-10 11:05 UTC, burqen commented on community/kernel/src/test/java/org/neo4j/test/rule/concurrent/ThreadingRule.java
> +            final Barrier barrier, final ThrowingFunction<FROM,TO,EX> function, final String name, final FROM parameter,
From what I can see, `barrier` is always `Barrier.NONE` and can be removed. I'll leave it up to you if you want to include that cleanup as part of this PR.

2017-04-10 11:05 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/ConstraintEnforcingEntityOperations.java
> +            if (!property.valueEquals( previousValue ))
Code style

2017-04-11 07:42 UTC, thobe commented on community/kernel/src/test/java/org/neo4j/test/ConfigBuilder.java
> +    public ConfigBuilder and( Setting<?> key, String value )
Given that the `configure(...)` method is a static factory method, and the constructor is private, invoking this method will never lead to a `NullPointerException`.

2017-04-11 07:43 UTC, burqen commented on community/kernel/src/test/java/org/neo4j/test/ConfigBuilder.java
> +    public ConfigBuilder and( Setting<?> key, String value )
Doh! Missed the fact that `and(...)` was _not_ static

2017-04-11 09:52 UTC, burqen approved these changes

2017-04-13 06:34 UTC, merged