Fixes race between starting transaction and shutdown
neo4j/neo4j pull request #9227
Opened 2017-04-20 10:52 UTC by tinwelint

This was designed to work already, but there was a slight gap in that
armor. DatabaseAvailability is the among last components to register in
the database lifecycle and therefore one of the first to be stopped.
Stopping DatabaseAvailability will raise the availability guard and then
await all active transactions to be finished (with some configurable
timeout). Starting transactions also checked the availability guard
state and registered themselves as active.

The problem was that the active state wasn't registered until after the
availability guard had been checked and so this little window between
those calls was racing with that same window in DatabaseAvailability
potentially allowing a transaction to start without being aware that
database was shutting down and shutdown process being unaware of an
active transaction running concurrently. This could result in
unspecified exceptions being thrown due to transaction running inside
components which were shutting down or even had been shut down.

This commit tightens this gap by letting transaction starting register
itself as active before checking availability guard. This way
transactions starting concurrently with shutdown will deterministically
succeed or fail, all depending on whether they made it in before the
availability guard was raised for shutdown.

This still leaves the max timeout that DatabaseAvailability waits before
going ahead with the shut down anyway. But that is by default a timeout
reasonable for most setups and it's configurable.

2017-04-21 09:00 UTC, chrisvest commented on community/io/src/test/java/org/neo4j/test/rule/PageCacheAndDependenciesRule.java
> +public class PageCacheAndDependenciesRule implements TestRule
👏 👏 👏

2017-04-21 09:03 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/Kernel.java
> +        return transactions.newInstance( type, securityContext, timeout );
👍 Good comment, too.

2017-04-21 09:08 UTC, chrisvest commented on community/kernel/src/test/java/org/neo4j/kernel/impl/api/KernelTest.java
> +            order.verify( transactionMonitor, times( 1 ) ).transactionStarted();
You forgot to verify the call to the availability guard.

2017-04-21 09:16 UTC, chrisvest requested changes
Looks good, I just want that test to be fixed.

2017-04-21 11:01 UTC, tinwelint commented on community/kernel/src/test/java/org/neo4j/kernel/impl/api/KernelTest.java
> +            order.verify( transactionMonitor, times( 1 ) ).transactionStarted();
Oh indeed

2017-04-21 11:06 UTC, tinwelint commented on community/kernel/src/test/java/org/neo4j/kernel/impl/api/KernelTest.java
> +            order.verify( transactionMonitor, times( 1 ) ).transactionStarted();
Now it's added

2017-04-21 11:28 UTC, chrisvest approved these changes

2017-04-21 12:56 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/impl/coreapi/CoreAPIAvailabilityGuard.java
> +            return new DatabaseShutdownException();
Should we not add initial exception as suppressed?

2017-04-26 13:35 UTC, chrisvest commented
@tinwelint There's a weird test failure.

2017-05-09 12:18 UTC, tinwelint commented
Looks related actually

2017-05-17 14:06 UTC, tinwelint commented
@chrisvest this has now been fixed... should go green

2017-05-29 08:27 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/KernelTransactions.java
> -        }
I think `KernelTransactionsTest.exceptionWhenStartingNewTransactionOnShutdownInstance` is failing because of this change.

2017-06-01 11:48 UTC, MishaDemianenko requested changes

2017-06-01 11:48 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/KernelTransactions.java
> -        if ( availabilityGuard.isShutdown() )
this check was done on this layer before to ensure that we hold newTransactionsLock when we doing so, now in cases when we block for various reasons on this lock for example and wake up, later on, we will allow the transaction to be started even db is already off do not think that is desired behaviour

2017-06-07 11:59 UTC, jansta commented
Will this fix (some of) [9121](https://github.com/neo4j/neo4j/issues/9121)? 

I know you guys are incredibly busy and doing great work, but I need at least some kind of comment on the issue (as in: we have noticed, will look into it)

I'm running a system with a few thousand daily users and have to make a decision on how to go forward as the production database keeps getting killed every few weeks and won't recover without a full restart (and even that is not enough sometimes).

2017-06-13 06:58 UTC, systay commented
@tinwelint Any updates to this PR?

2017-06-14 12:26 UTC, ragadeeshu commented
@systay This will be updated shortly

2017-06-14 15:38 UTC, ragadeeshu commented
@MishaDemianenko updated :)

2017-06-14 15:59 UTC, MishaDemianenko approved these changes
@ragadeeshu do not have questions anymore, thx :)

2017-06-16 08:47 UTC, merged