Parallel I/O in importer
neo4j/neo4j pull request #9273
Opened 2017-04-27 12:43 UTC by tinwelint

Previously focus has been on making all I/O single threaded and sequential in the importer. However with more modern hardware it's more and more beneficial to read, and sometimes even write, in parallel. Also work load have been redistributed so that writers do a little less, so basically only writes records to stores.

This series of commits opens up possibility for doing that and adding some, for the time internal, configuration options for enabling/disabling this parallelism.

Queueing and task execution has seen some simplifications and less overhead too so now it's only the first step in a stage of processing which will apply back pressure if the downstream step can't catch up, otherwise all the other step never waits for downstream steps to catch up.

2017-04-28 06:27 UTC, burqen commented
@tinwelint should the config options be listed in the changelog?

2017-05-04 11:42 UTC, tinwelint commented
@burqen the thing is that those configuration options aren't actually available to configure. Something we'll have to think about.

2017-05-08 09:29 UTC, burqen requested changes
Overall changes look good. I have some comments, mostly about readability and explanation about thing I did not fullt understand. 🎉

2017-05-08 09:29 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/HighestId.java
> +            if ( candidate < currentHighest )
Could use `<=` here

2017-05-08 09:29 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/PropertyEncoderStep.java
> + * ids will have to be done later.
Is this true? I thought the reassigning of ids happened in the loop starting at line `126`. And I don't see any other later step doing the reassignment. What is it that I'm missing?

2017-05-08 09:29 UTC, burqen commented on community/kernel/src/test/java/org/neo4j/test/rule/NeoStoresRule.java
> +            Function<FileSystemAbstraction,IdGeneratorFactory> idGeneratorFactory, String... config )
Class level javadoc reference this method. Please update signature there as well.

2017-05-08 09:29 UTC, burqen commented on community/kernel/src/test/java/org/neo4j/test/rule/NeoStoresRule.java
> +    public class Builder
Right now we use both builder and multiple constructors to create `NeoStores`.
I would like it if we could:
1. use this pattern everywhere and remove the multiple `open(...)`
2. document the "default" behaviour of the builder if the fields are not set explicitly.

Did not look lite _too_ much work to move from `neoStoresRule.open()` -> `neoStoreRules.builder().build()` for the majority of the cases we have.

2017-05-08 09:29 UTC, burqen commented on community/kernel/src/test/java/org/neo4j/test/rule/NeoStoresRule.java
> +        if ( fs == null )
Can we move this "default" behaviour to the builder instead and also have it documented there. This ties together with comment about removing multiple constructor pattern and completely replace with builder.

2017-05-08 09:29 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/impl/store/id/validation/IdValidator.java
> +    public static boolean hasReservedIdInRange( long startIdInclusive, long endIdExclusive )
From what I understand, this means there will be a batch sized gap of ids around `INTEGER_MINUS_ONE` that is not used by importer. Right? But id generator will know this and fill this gap up during normal operations after import is done?

2017-05-08 09:29 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/staging/ReadRecordsStep.java
> +        sender.send( i == batchSize ? batch : Arrays.copyOf( batch, i ) );
The reason we do this is because we need the sent array to be completely full, right?

2017-05-08 09:29 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/Configuration.java
> +    long MAX_PAGE_CACHE_MEMORY = mebiBytes( 480 );
This number seem to be fairly low, even for systems with memory size only in the tens of GB. Why is it so low and not adaptive to the environment like the page cache normally is?

2017-05-08 09:29 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/NodeFirstRelationshipStage.java
> +                new NodeFirstRelationshipProcessor( cache ), false ) );
`NodeFirstRelationshipProcessor` does not create group records for dense nodes any more. Update this in javadoc please.

(On that note. The javadocs for the different stages has helped me a lot. Good stuff!)

2017-05-08 09:29 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/NodeFirstRelationshipProcessor.java
> +public class NodeFirstRelationshipProcessor implements RecordProcessor<NodeRecord>
Please update javadoc. This guy does nothing with dense nodes anymore.

2017-05-08 09:29 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/RelationshipGroupStage.java
> +public class RelationshipGroupStage extends Stage
Can we have some awesome javadoc for this guy?

2017-05-08 09:29 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/staging/Step.java
> +    long doneBatches();
This method is not called anywhere. Can we get rid of it?
And if I'm wrong, can we haz javadoc?

2017-05-08 09:29 UTC, burqen commented on community/kernel/src/test/java/org/neo4j/unsafe/impl/batchimport/staging/ProcessorStepTest.java
> +            System.out.println( Thread.currentThread().getName() + " process" );
Oops.

2017-05-08 10:36 UTC, ragadeeshu commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/staging/ReadRecordsStep.java
> +        super( control, ">", config, 0 );
These names (">") are really non-descriptive.

2017-05-08 10:36 UTC, ragadeeshu commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/Configuration.java
> +    long MAX_PAGE_CACHE_MEMORY = mebiBytes( 480 );
IIRC this is because the cache is only used for writes, and thus there is no benefit of keeping the data in memory.

2017-05-08 10:36 UTC, ragadeeshu commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/staging/DynamicProcessorAssigner.java
>              if ( permits > 0 )
Where is permits changed now?

2017-05-09 06:45 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/Configuration.java
> +    long MAX_PAGE_CACHE_MEMORY = mebiBytes( 480 );
But we do read from store in quite a lot of our `Stages`, every time we use `ReadRecordsStep`.Would it not be beneficial to not have those reads result in I/O?

2017-05-09 06:50 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/staging/DynamicProcessorAssigner.java
>              if ( permits > 0 )
Seems like it's not changed, but recalculated every time we call `DynamicProcessorAssigner.check( StageExecution execution )`

2017-05-09 12:22 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/PropertyEncoderStep.java
> + * ids will have to be done later.
You're right, this was changed back and forth and ended up back in here :)

2017-05-09 13:00 UTC, tinwelint commented on community/kernel/src/test/java/org/neo4j/test/rule/NeoStoresRule.java
> +    public class Builder
Sure, there are so few places so this can be done I think

2017-05-09 13:08 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/kernel/impl/store/id/validation/IdValidator.java
> +    public static boolean hasReservedIdInRange( long startIdInclusive, long endIdExclusive )
No, these gaps will not be in the freelist. Doesn't matter much though as it's in the size of thousands of ids.

2017-05-09 13:08 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/staging/ReadRecordsStep.java
> +        sender.send( i == batchSize ? batch : Arrays.copyOf( batch, i ) );
Yeah, and only the last batch will do this copy

2017-05-09 13:10 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/Configuration.java
> +    long MAX_PAGE_CACHE_MEMORY = mebiBytes( 480 );
What we generally see is that the smaller the page cache is the faster the importer goes, down to a certain point of course. The smaller it is the higher the chance the background flushing will hit a nice wave of sequential I/O.

2017-05-09 13:18 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/staging/Step.java
> +    long doneBatches();
Accidentally left it there

2017-05-09 13:21 UTC, tinwelint commented
@burqen comments addressed

2017-05-16 12:22 UTC, burqen approved these changes

2017-05-16 17:25 UTC, merged