Removes import stage calculating dense nodes
neo4j/neo4j pull request #9274
Opened 2017-04-27 13:04 UTC by tinwelint

And instead only has one step reading relationship input. Introduced another step which links relationship chains together (link forward) before linking backwards. This approach seems faster than the previous approach.

The forked processor has seen a rewrite for better throughput. Forked processor is a step which processes batches sequentially, although it has potentially multiple internal processors, each processing only its own part of a batch e.g. based on node id. This is very useful for parallelizing processing of batches that uses unsynchronized, or non-trivially-synchronizable data structures.

2017-04-27 13:04 UTC, tinwelint commented
Builds on #9273

2017-05-08 06:30 UTC, burqen commented
@tinwelint You got yourself some checkstyle errors.
`ForkedProcessorStepTest.java:29:1: Redundant import from the same package`

2017-05-17 09:07 UTC, tinwelint commented
@burqen looks like green with an unrelated flaky test

2017-05-17 14:16 UTC, burqen requested changes
Got some comments, mostly about javadoc

2017-05-17 14:16 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/RelationshipLinkforwardStage.java
> +public class RelationshipLinkforwardStage extends Stage
Please add javadoc similar to the other stages, they help a lot.

2017-05-17 14:16 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/RelationshipStage.java
>  public class RelationshipStage extends Stage
Please add javadoc similar to the other stages, they are great.

2017-05-17 14:16 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/ParallelBatchImporter.java
> +            RelationshipStage unlinkedRelationshipStage =
Please add `// Step ... ` comment for consistency with rest of comments. (Also, I think they are useful when navigating the code)

2017-05-17 14:16 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/RelationshipStage.java
> -        add( new RelationshipEncoderStep( control(), config, cache ) );
`RelationshipEncoderStep` is not used anymore, it can be removed.

2017-05-17 14:16 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/ParallelBatchImporter.java
>          // all sparse relationship chains together.
This comment seems a bit outdated, can we update it?

2017-05-17 16:07 UTC, tinwelint commented
@burqen updated

2017-05-18 06:52 UTC, burqen approved these changes

2017-05-18 07:01 UTC, merged