Legacy code cleanup 2.0, 2.1, 2.2
neo4j/neo4j pull request #9307
Opened 2017-05-05 09:10 UTC by burqen

We do not support upgrade directly from 2.0, 2.1 or 2.2 to 3.2.
This PR remove legacy code for those migrations.

co-author: @MishaDemianenko

2017-05-08 09:11 UTC, ragadeeshu reviewed
Some questions, mostly around old tests. Looks good otherwise, nice to get this out of the way :)

2017-05-08 09:11 UTC, ragadeeshu commented on community/kernel/src/main/java/org/neo4j/kernel/impl/storemigration/UpgradableDatabase.java
> -    private Result checkCleanShutDownByVersionTrailer( File storeDirectory, RecordFormats fromFormat )
Nice to see this die for real!

2017-05-08 09:11 UTC, ragadeeshu commented on community/kernel/src/main/java/org/neo4j/kernel/impl/storemigration/participant/StoreMigrator.java
> +        if ( versionToMigrateFrom.equals( StandardV2_3.STORE_VERSION ) )
We didn't check for 2.3 before, was that a bug?

2017-05-08 09:11 UTC, ragadeeshu commented on community/neo4j/src/test/java/upgrade/StoreUpgraderTest.java
> -                StandardV2_0.STORE_VERSION,
In a lot of tests the old formats are removed, but should newer formats be added as well?

2017-05-08 09:11 UTC, ragadeeshu commented on community/neo4j/src/test/java/upgrade/StoreUpgraderTest.java
> -                StandardV2_0.STORE_VERSION,
If not, should a lot of these tests disappear completely?

2017-05-08 09:11 UTC, ragadeeshu commented on community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/state/NeoStoreFileListing.java
> +    private void placeMetaDataStoreLast( List<StoreFileMetadata> files )
It is a bit unclear to me why we are doing this :)

2017-05-08 09:11 UTC, ragadeeshu commented on integrationtests/src/test/java/org/neo4j/storeupgrade/StoreUpgradeIntegrationTest.java
> +            return Arrays.asList(
Hmm, these look very old, why are they still here?

2017-05-08 09:12 UTC, ragadeeshu commented
@burqen reviewed

2017-05-09 07:04 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/impl/storemigration/participant/StoreMigrator.java
> +        if ( versionToMigrateFrom.equals( StandardV2_3.STORE_VERSION ) )
Yes I think so. But I'd have to bring in @chrisvest to confirm.

2017-05-09 07:23 UTC, burqen commented on community/neo4j/src/test/java/upgrade/StoreUpgraderTest.java
> -                StandardV2_0.STORE_VERSION,
Good point! I think there is value in keeping those tests and extend them to all relevant formats. Let't keep that outside of this PR though.

2017-05-09 07:31 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/state/NeoStoreFileListing.java
> +    private void placeMetaDataStoreLast( List<StoreFileMetadata> files )
It's used by `NeoStores.isStorePresent` to indicate that the store is present. Agreeably not very reliable.

2017-05-09 07:33 UTC, burqen commented on integrationtests/src/test/java/org/neo4j/storeupgrade/StoreUpgradeIntegrationTest.java
> +            return Arrays.asList(
You mean the `.tar`s with the stores? They are still there.

2017-05-09 07:41 UTC, burqen commented
@ragadeeshu Rebased and ready

2017-05-09 08:46 UTC, ragadeeshu commented on integrationtests/src/test/java/org/neo4j/storeupgrade/StoreUpgradeIntegrationTest.java
> +            return Arrays.asList(
Yes, but why? Didn't we just remove support for migrating them? So why are they still a part of this test? :)

2017-05-09 08:47 UTC, burqen commented on integrationtests/src/test/java/org/neo4j/storeupgrade/StoreUpgradeIntegrationTest.java
> +            return Arrays.asList(
Aah, this test makes sure that we fail if we try to migrate any of those stores.

2017-05-12 15:20 UTC, ragadeeshu commented
@burqen I think that this one needs another rebase.

2017-05-15 13:49 UTC, ragadeeshu commented
@burqen And even more rebase

2017-05-16 08:38 UTC, tinwelint requested changes
Nice to see so much legacy code deleted.

2017-05-16 08:38 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/labelscan/NativeLabelScanStore.java
> +        if ( fileHandle.isPresent() )
Sounds like `dropStrict` should delete or throw, not be OK with file not being there.

2017-05-16 08:38 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/kernel/impl/store/StoreType.java
> +    protected boolean matchStoreName( String fileName, String storeName )
Javadoc on what the arguments are would be welcome

2017-05-16 08:38 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/state/NeoStoreFileListing.java
> +    private void placeMetaDataStoreLast( List<StoreFileMetadata> files )
Yup I think that's for another piece of investigation, not cleanup

2017-05-17 08:17 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/labelscan/NativeLabelScanStore.java
> +        if ( fileHandle.isPresent() )
It will throw `NoSuchFileException` if file does not exist, this will be caught in `drop`.

2017-05-17 08:57 UTC, burqen commented
@ragadeeshu @tinwelint I think I've addressed all your comments now.

2017-05-19 08:56 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/labelscan/NativeLabelScanStore.java
> +        if ( fileHandle.isPresent() )
Won't it just return silently if `!fileHandle.isPresent()`?

2017-05-19 09:11 UTC, tinwelint approved these changes

2017-05-19 12:56 UTC, merged