Avoid accumulation of index updates during recovery
neo4j/neo4j pull request #9317
Opened 2017-05-08 11:08 UTC by MishaDemianenko

Do not collect index updates during recovery since that can cause OOM.
Use iterators instead to iterate over required updates.

2017-05-09 09:28 UTC, burqen requested changes
Behaviour changes look good! 🎉  
Got some small comments about readability.

2017-05-09 09:28 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/index/IndexingService.java
> +                    }
This code is also used in `apply( Iterable<IndexEntryUpdate<LabelSchemaDescriptor>> updates, IndexUpdateMode updateMode )`. Can we extract it?
```
IndexUpdater updater = updaterMap.getUpdater( indexUpdate.indexKey().schema() );
if ( updater != null )
{
    updater.process( indexUpdate );
}
```

2017-05-09 09:28 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/index/IndexStoreView.java
> +    NodeUpdates nodeAsUpdates( long nodeId );
Can we also update rest of javadoc to reflect this change?

2017-05-09 09:28 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/index/IndexingService.java
>                      updater.remove( recoveredNodeIds );
I don't understand why we need to do this. Seems like when we are in `IndexUpdateMode.RECOVERY` we will use `SwallowingIndexUpdater` which is just no-ops.

2017-05-09 14:07 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/api/index/IndexingService.java
>                      updater.remove( recoveredNodeIds );
no, not always; for example, we can use LuceneIndexUpdater. Also, this is not related to PR.

2017-05-09 14:15 UTC, MishaDemianenko commented
@burqen I believe I have cover all your comments

2017-05-15 14:59 UTC, MishaDemianenko commented
@burqen updated

2017-05-17 06:35 UTC, burqen approved these changes

2017-05-17 06:35 UTC, merged