Avoid duplicated monitors for label scan store
neo4j/neo4j pull request #9320
Opened 2017-05-08 16:32 UTC by MishaDemianenko

Use label scan store tags to separate monitors for native and lucene label scan indexes.

2017-05-09 09:57 UTC, burqen requested changes
Changes look good for the most part, but I would like it if we could use the same static variable for tagging monitors as we do to give the providers name.
My suggestion is to move `NAME` from extension class (both Lucene and Native) to their respective `LabelScanStore` implementation and then always use that one.
Makes sense?

2017-05-09 09:57 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/labelscan/NativeLabelScanStore.java
> +    public static final String NATIVE_INDEX_TAG = GraphDatabaseSettings.LabelIndex.NATIVE.name();
Can we be a little bit more explicit about what we call this tag to not confuse it with "native schema index"? My suggestion is something like: `NATIVE_LABEL_INDEX_TAG`.
Let this also be reflected in javadoc:
- "Native index monitor tag" -> "Native label index monitor tag"
- "monitors for native index store" -> "monitors for native label index"

2017-05-09 09:57 UTC, burqen commented on community/neo4j/src/test/java/org/neo4j/index/LabelScanStoreLogging.java
> +public class LabelScanStoreLogging
Do we not need the class name to include "Test" to make maven run it?

2017-05-09 11:23 UTC, MishaDemianenko commented
@burqen I was thinking about this PR being more example and showcase but if you think it's fine and it can be merged in - will brush it up!

2017-05-09 20:23 UTC, MishaDemianenko commented
@burqen updated!

2017-05-15 15:07 UTC, MishaDemianenko commented
@burqen updated just in case as well

2017-05-17 14:18 UTC, burqen approved these changes

2017-05-17 14:19 UTC, merged