Properly set owningPipe on CoerceTo
neo4j/neo4j pull request #9379
Opened 2017-05-18 15:07 UTC by OliviaYtterbrink

The rewriter of CoerceTo didn't rewrite the inner expression.

2017-05-19 07:15 UTC, pontusmelke requested changes
Nice catch! Just two minor things in the tests.

2017-05-19 07:15 UTC, pontusmelke commented on community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/PatternComprehensionAcceptanceTest.scala
> +    println(result.toList)
remove the `println` and do some actual assertion on `result`

2017-05-19 07:15 UTC, pontusmelke commented on community/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/PatternComprehensionAcceptanceTest.scala
> +    println(result.toList)
remove the println and do some actual assertion on result

2017-05-24 07:46 UTC, craigtaverner commented
Replaced by https://github.com/neo4j/neo4j/pull/9389

2017-05-24 07:46 UTC, closed without merging