Replace multiple locks in GBPTree with single simple lock
neo4j/neo4j pull request #9388
Opened 2017-05-19 12:55 UTC by burqen

2017-05-23 12:42 UTC, tinwelint requested changes

2017-05-23 12:42 UTC, tinwelint commented on community/index/src/main/java/org/neo4j/index/internal/gbptree/GBPTreeLock.java
> +        while ( !UnsafeUtil.compareAndSwapLong( this, stateOffset, currentState, newState ) );
I'd guess there _could_ be an `unpark` somewhere, but since this isn't a highly contented lock at all perhaps there's no need to bother, is there?

2017-05-23 12:42 UTC, tinwelint commented on community/index/src/test/java/org/neo4j/index/internal/gbptree/GBPTreeLockTest.java
> +            future.get( 200, TimeUnit.MILLISECONDS );
I'd prefer `OtherThreadRule` instead. With it you can wait for the code to get into wait or block in specific part of code. Regardless of how long this timeout is there's a chance of flakyness and best case it waits 200ms which is unnecessary and accumulates to a non-neglectible time if there are multiple tests.

2017-05-23 12:47 UTC, burqen commented
... and also need testing for two threads racing for same lock / overlapping lock.

2017-05-24 07:19 UTC, tinwelint commented on community/index/src/test/java/org/neo4j/index/internal/gbptree/GBPTreeLockTest.java
> +            future.get( 200, TimeUnit.MILLISECONDS );
Hmm, that rule exists in neo4j-kernel. Could be a separate PR for moving it to something like neo4j-common and making use of it.

2017-05-26 09:41 UTC, burqen commented on community/index/src/main/java/org/neo4j/index/internal/gbptree/GBPTreeLock.java
> +        while ( !UnsafeUtil.compareAndSwapLong( this, stateOffset, currentState, newState ) );
I agree that we don't need to bother with that, since the cost of making the code more complex is higher.

2017-05-31 11:09 UTC, tinwelint approved these changes

2017-05-31 11:15 UTC, merged