fixes #9390 apply nodefilter only on endNode
neo4j/neo4j pull request #9393
Opened 2017-05-20 09:08 UTC by sarmbruster

2017-05-24 12:34 UTC, tinwelint commented on community/graph-algo/src/test/java/org/neo4j/graphalgo/impl/path/TestShortestPath.java
> +import java.util.*;
No star imports, please

2017-05-24 12:39 UTC, tinwelint commented
I may be wrong, but this doesn't strike me as a correct fix, as it looks like it's changing other behaviour too. Is this a bi-directional traversal issue? If so perhaps the fix should be in the bi-directional part of the code.

Your commit doesn't explain the reasoning behind the change.

2017-05-26 09:30 UTC, burqen requested changes

2017-05-26 09:30 UTC, burqen commented on community/graph-algo/src/test/java/org/neo4j/graphalgo/impl/path/TestShortestPath.java
> +    public void filtersTouchesAllIntermediateNodes() throws Exception
This code is breaking some code style rules. Are you using the Neo4j formatting? If you do, try to auto-format this part. If you are not, I'll be happy to help you out.

(This is not a problem for 3.1 because checkstyle rules are not as mature there but it will be when forward merging so might as well fix it before)

2017-05-26 11:39 UTC, sarmbruster commented on community/graph-algo/src/test/java/org/neo4j/graphalgo/impl/path/TestShortestPath.java
> +    public void filtersTouchesAllIntermediateNodes() throws Exception
where can I find the current code style data?

2017-06-12 08:16 UTC, systay commented
@sarmbruster @tinwelint Any progress on this PR? Is it being worked on, or should we close it for now?

2017-06-12 08:19 UTC, sarmbruster commented
I've addressed the code style changes requested above.

2017-06-12 08:23 UTC, sarmbruster commented
The PR basically solves the issue referred to (#9390). When doing shortestPath (or other) algos, the nodefilter is not applied on the node joing left and right traversal. This is fixed here.

2017-06-12 10:23 UTC, systay commented
Do you have an answer to @tinwelint's comments above? (https://github.com/neo4j/neo4j/pull/9393#issuecomment-303711409)

2017-06-14 06:46 UTC, burqen commented
@tinwelint I added an explanation of the PR. What do you think about this change?

2017-06-14 09:09 UTC, tinwelint commented
I read the changes wrong previously, I do think the fix is correct!

2017-06-14 09:36 UTC, burqen approved these changes

2017-06-14 09:36 UTC, burqen commented
Talked with @tinwelint and we both agree that this is the correct thing to do.

2017-06-14 09:37 UTC, merged