Wait for recovery cleaner to complete in LabelScanStoreLoggingTest
neo4j/neo4j pull request #9401
Opened 2017-05-22 15:55 UTC by MishaDemianenko

Fix recently introduced component start race by waiting for cleanup job
to be always completed before checking recovery log messages.

2017-05-22 15:55 UTC, MishaDemianenko commented
piu piu @burqen  :)

2017-05-23 10:06 UTC, burqen requested changes
Small possibility for improvement, otherwise changes look awesome.

2017-05-23 10:06 UTC, burqen commented on community/common/src/main/java/org/neo4j/kernel/lifecycle/Lifecycles.java
> +        return new CombinedLifecycle( Arrays.asList( lifecycles ) );
We can reuse `multiple( Iterable lifecycles )` here.

2017-05-23 11:43 UTC, MishaDemianenko commented
@burqen updated, thx!

2017-05-23 13:42 UTC, burqen approved these changes

2017-05-23 13:43 UTC, burqen commented
@MishaDemianenko PR approved. Build does not look very happy though.

2017-05-23 20:37 UTC, merged