Replace and deprecate START
neo4j/neo4j pull request #9501
Opened 2017-06-11 17:52 UTC by pontusmelke

Add built-in procedures `db.nodeLegacyIndexSeek`, `db.nodeLegacyIndexSearch`, `db.relationshipLegacyIndexSeek`, and `db.relationshipLegacyIndexSearch` replacing `START` for reading from legacy index. Also deprecate `START` and add a notification that tell the user how to rewrite the query to use a procedure or `MATCH`.

2017-06-12 08:37 UTC, chrisvest commented
They're called _manual indexes_ now: https://neo4j.com/docs/java-reference/3.2/#tutorials-java-embedded-index

2017-06-13 11:27 UTC, pontusmelke commented
@chrisvest We updated the name of the procedures. We also renamed the exception and the status code, however I am unsure if we can do this renaming in 3.3?

2017-06-14 04:21 UTC, systay requested changes

2017-06-14 04:21 UTC, systay commented on community/cypher/frontend-3.3/src/main/scala/org/neo4j/cypher/internal/frontend/v3_3/ast/Clause.scala
> +        s"CALL db.nodeLegacyIndexSeek('$index', '$key', '${expression.asCanonicalStringVal}') YIELD node AS ${variable.asCanonicalStringVal}"
This should talk about manual indexes and not legacy stuff, right? Other examples in the next couple of lines

2017-06-14 04:21 UTC, systay commented on community/kernel/src/main/java/org/neo4j/graphdb/impl/notification/NotificationCode.java
> +            "START is not supported for current CYPHER version, the query has been executed by an older CYPHER version"
Is this still used or lying around for compatibility reasons? I thought this PR removed the fallback.

2017-06-14 07:44 UTC, pontusmelke commented on community/kernel/src/main/java/org/neo4j/graphdb/impl/notification/NotificationCode.java
> +            "START is not supported for current CYPHER version, the query has been executed by an older CYPHER version"
It is still around, just changed the wording. So my thinking was that it is two different notifications, one is saying: _this query could not be run on this version of cypher_ and the other one is saying: _`START` is deprecated`.  It is really two different things, or is my thinking wrong?

2017-06-14 09:01 UTC, systay commented on community/kernel/src/main/java/org/neo4j/graphdb/impl/notification/NotificationCode.java
> +            "START is not supported for current CYPHER version, the query has been executed by an older CYPHER version"
Makes sense. 👍

2017-06-19 07:41 UTC, systay approved these changes

2017-06-19 07:41 UTC, merged