Optional match in compiled runtime now check that nodes exists.
neo4j/neo4j pull request #9507
Opened 2017-06-12 14:32 UTC by eebus

[changelog] Optional match in compiled runtime now checks that nodes exist before checking the label.

2017-06-13 09:08 UTC, pontusmelke requested changes

2017-06-13 09:08 UTC, pontusmelke commented on enterprise/cypher/cypher-compiled-runtime-3.2/src/main/scala/org/neo4j/cypher/internal/compiled_runtime/v3_2/codegen/ir/expressions/HasLabel.scala
>      structure.declarePredicate(localName)
I think this will get rid of most of the compilation errors 
`structure.declareAndInitialize(localName, CodeGenType.primitiveBool)`

2017-06-13 09:08 UTC, pontusmelke commented on enterprise/cypher/cypher-compiled-runtime-3.2/src/main/scala/org/neo4j/cypher/internal/compiled_runtime/v3_2/codegen/ir/expressions/HasLabel.scala
> +    if (nodeVariable.nullable) {
I think it should be something like this
```
structure.incrementDbHits()
    if (nodeVariable.nullable) {
      structure.ifNotStatement(structure.equalityExpression(structure.loadVariable(nodeVariable.name),
                                                            structure.constantExpression(Long.box(-1L)),
                                                            CodeGenType.primitiveInt)) { inner =>
        inner.hasLabel(nodeVariable.name, labelVariable, localName)
      }
      structure.nullableReference(nodeVariable.name, CodeGenType.primitiveNode,
                                  structure.box(
                                    structure.loadVariable(localName), CodeGenType.primitiveBool))

    }
    else {
      structure.hasLabel(nodeVariable.name, labelVariable, localName)
      structure.loadVariable(localName)
    }
```

The important thing is that: if the node id is `-1` the end-result should not be `false` but `null`. A test doing something like `MATCH (n) OPTIONAL MATCH (o: DOESNT_EXIST) RETURN o:L` is going to fail in the current implementation I think, so adding that test case might be a good idea.

2017-06-14 09:25 UTC, eebus commented
This is replaced with #9524

2017-06-14 09:25 UTC, closed without merging