Virtual values
neo4j/neo4j pull request #9509
Opened 2017-06-12 21:30 UTC by fickludd

Adds virtual values to the values module. These are

 * NodeReference
 * EdgeReference
 * LabelSet
 * Path
 * Point (cartesian and geographic)
 * List
 * Map

LabelSet is included so that full nodes can be handled (as the combination of 1 NodeReference, 1 LabelSet, and 1 Map). 

These virtual values support `equality`, `hashcode`, `comparison` and `writeTo`. Two known changes are not performed here. We have created card for completing these work units at some later point. The left out changes are

 1) to flip the packages to the storable values are in a self contained subpackage, while the virtual/AnyValues are in the top values package.
 2) implement list-array equality

2017-06-13 11:57 UTC, pontusmelke commented on community/values/src/main/java/org/neo4j/values/virtual/ArrayHelpers.java
> +class ArrayHelpers
we usually have static helpers being final with a `private` constructor so that they cannot be instantiated

2017-06-13 11:58 UTC, pontusmelke commented on community/values/src/main/java/org/neo4j/values/virtual/EdgeReference.java
> +        if ( other == null || !(other instanceof EdgeReference) )
isn't this null check redundant?

2017-06-13 12:00 UTC, pontusmelke commented on community/values/src/main/java/org/neo4j/values/virtual/MapValue.java
> +        if ( other == null || !(other instanceof MapValue) )
same here, redundant?

2017-06-13 12:01 UTC, pontusmelke commented on community/values/src/main/java/org/neo4j/values/virtual/NodeReference.java
> +        if ( other == null || !(other instanceof NodeReference) )
Same here, redundant?

2017-06-13 12:01 UTC, pontusmelke commented on community/values/src/main/java/org/neo4j/values/virtual/PathValue.java
> +        if ( other == null || !(other instanceof PathValue) )
same here, redundant?

2017-06-14 13:06 UTC, fickludd reviewed
Looks good! I will be happy to use some benchmarks later to find a faster MapValue implementation =).

2017-06-14 13:06 UTC, fickludd commented on community/values/src/main/java/org/neo4j/values/virtual/VirtualValues.java
> +    public static MapValue emptyMap()
This can be a static field instead of a method.

2017-06-14 13:06 UTC, fickludd commented on community/values/src/main/java/org/neo4j/values/virtual/VirtualValues.java
> +    public static LabelSet labels( LabelValue... labelIds )
arguments name could be `labels`

2017-06-14 13:06 UTC, fickludd commented on community/values/src/test/java/org/neo4j/values/AnyValueComparatorTest.java
> +            node( 3L ),
WDYT about `node` -> `nodeRef`, and same for edge?

2017-06-14 13:06 UTC, fickludd commented on community/values/src/main/java/org/neo4j/values/virtual/NodeValue.java
> +        return format( "(%s)", id );
`"(%d)"`

2017-06-15 14:09 UTC, pontusmelke requested changes

2017-06-15 14:09 UTC, pontusmelke commented on community/values/src/main/java/org/neo4j/values/virtual/LabelValue.java
> +public class LabelValue extends VirtualValue
I have changed my mind, this was not a good idea

2017-06-16 09:15 UTC, pontusmelke approved these changes

2017-06-16 09:19 UTC, chrisvest commented on community/values/src/main/java/org/neo4j/values/Values.java
> +     * Converts an array of object values to the internal Value type. See @{Values.of}.
`{@link Values#of}`?

2017-06-20 10:33 UTC, merged