Align native index sorting with values module
neo4j/neo4j pull request #9543
Opened 2017-06-21 09:24 UTC by burqen

NOTE! Only last three commits are new. The rest come from #9480 

New RawBits class is responsible for comparison between values given represented
as raw bits and value type byte.

Another option would be to materialise raw bits and value type to NumberValue
objects but we want to avoid as much object creation as possible.

2017-06-21 11:45 UTC, fickludd approved these changes
Looks very good, just found a minor thing that you can fix if you want to.

2017-06-21 11:45 UTC, fickludd commented on community/kernel/src/test/java/org/neo4j/kernel/impl/index/schema/RawBitsTest.java
> +    final List<Object> objects = new ArrayList<>( Arrays.asList(
´new ArrayList<>( Arrays.asList(´... en list för mycket?

2017-06-21 11:45 UTC, fickludd commented on community/kernel/src/test/java/org/neo4j/kernel/impl/index/schema/RawBitsTest.java
> +    public NumberLayout layout;
Nice to parametrize on the NumberLayout!

2017-06-27 11:30 UTC, chrisvest requested changes
The changes themselves are pretty straight forward, but I'd like to see more thorough testing. It would be annoying to get this wrong.

2017-06-27 11:30 UTC, chrisvest commented on community/kernel/src/test/java/org/neo4j/kernel/impl/index/schema/RawBitsTest.java
> +        assertSameOrder( actual, values );
I think we want to test the comparison of all the values to all the values, so N² comparisons. Shuffling and sorting the elements will only give us N·log(N) comparisons. I'd also add in a handful of floats and doubles that only differ by one ulp, e.g. Math.PI vs Math.nextUp/nextDown(Math.PI), and similarly for floats. I'd also add some int/long values that floats/doubles can almost-but-not-quite represent accurately.

2017-06-27 11:30 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/schema/SchemaNumberKey.java
> +        // TODO: support multiple values, right?
Is this coming later?

2017-06-27 11:33 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/schema/SchemaNumberKey.java
> +        // TODO: support multiple values, right?
It may do, if time permits. In any way a separate story from this PR.

2017-06-27 13:26 UTC, tinwelint commented on community/kernel/src/test/java/org/neo4j/kernel/impl/index/schema/RawBitsTest.java
> +        assertSameOrder( actual, values );
Added some more testing, have a look if you think that's OK

2017-06-27 13:54 UTC, chrisvest commented on community/kernel/src/test/java/org/neo4j/kernel/impl/index/schema/RawBitsTest.java
> +    }
I was more thinking of a nested loop where you check that for all combinations `layout.compare` return the same as `Values.COMPARATOR.compare`.

2017-06-27 14:12 UTC, tinwelint commented on community/kernel/src/test/java/org/neo4j/kernel/impl/index/schema/RawBitsTest.java
> +    }
Alright, added that too now.

2017-06-27 15:10 UTC, chrisvest approved these changes

2017-06-27 15:16 UTC, merged