Cypher refactoring
neo4j/neo4j pull request #9546
Opened 2017-06-21 13:30 UTC by SaschaPeukert

2017-06-28 09:02 UTC, fickludd requested changes
I think this PR i a little bit weird, in that is contains some variable offset allocation code in addition to the "Various Cypher refactorings". Would it be possible to break out the offset allocation code into a separate PR? Possibly that part want's some more intergration tests too.

The refactorings all seem fine and reasonable!

I did make some comments on the offset code (and suggest that we settle for Slot as the gathering term), but don't know how things will be grouped in the end.

2017-06-28 09:02 UTC, fickludd commented on community/cypher/cypher-compiler-3.3/src/main/scala/org/neo4j/cypher/internal/compiler/v3_3/planner/logical/plans/rewriter/simplifyPredicates.scala
> +    // This form is used to make finding composite index seeks and scans
There is something strange in this sentence...

2017-06-28 09:02 UTC, fickludd commented on community/cypher/cypher-compiler-3.3/src/test/scala/org/neo4j/cypher/internal/compiler/v3_3/planner/logical/plans/rewriter/SimplifyPredicatesTest.scala
> +    val variable = Variable("a")(pos)
I'm still so bad at reading these manually built logical plans... I guess `"a"` here really is what is called `x` in the test description?

2017-06-28 09:02 UTC, fickludd commented on community/cypher/cypher-compiler-3.3/src/test/scala/org/neo4j/cypher/internal/compiler/v3_3/planner/logical/plans/rewriter/SimplifyPredicatesTest.scala
> +    val greaterThan = GreaterThan(property, SignedDecimalIntegerLiteral("42")(pos))(pos)
... and `greaterThan` is `<>`, and `42` is `1`?

2017-06-28 09:02 UTC, fickludd commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/ActualPipeBuilder.scala
> +case class ActualPipeBuilder(monitors: Monitors, recurse: LogicalPlan => Pipe, readOnly: Boolean, idMap: Map[LogicalPlan, Id], expressionConverters: ExpressionConverters)
This class is a great idea. It summarizes the whole `Logical Plan -> Physical/Executable Plan` transformation very nicely.

2017-06-28 09:02 UTC, fickludd commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/PipelineInformation.scala
> +class PipelineInformation(var slots: Map[String, Slot], var numberOfLongs: Int, var numberOfReferences: Int) {
How about calling it `PipelineSlots`?

2017-06-28 09:02 UTC, fickludd commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/RegisterAllocation.scala
> +object RegisterAllocation {
And `SlotAllocation`? Then we get rid of register allocation overloaded meaning, and homogenize with `Slot`.

2017-06-28 09:02 UTC, fickludd commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/RegisterAllocation.scala
> +  def allocateRegisters(lp: LogicalPlan): Map[LogicalPlan, PipelineInformation] = {
`allocateSlots` etc...

2017-06-28 09:02 UTC, fickludd commented on enterprise/cypher/cypher/src/test/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/RegisterAllocationTest.scala
> +//    val e2 = Expand(e1, IdName("z"), SemanticDirection.INCOMING, Seq.empty, IdName("y"), IdName("r2"), ExpandAll)(solved)
Ghost code! Expel it with water, rinse and repeat.

2017-06-30 07:54 UTC, SaschaPeukert commented
I removed the two last register allocation commits because they were not meant to be included in this PR

2017-06-30 11:29 UTC, fickludd approved these changes

2017-06-30 18:03 UTC, merged