Uniqueness check with different duplicate check strategies.
neo4j/neo4j pull request #9722
Opened 2017-07-27 09:31 UTC by MishaDemianenko

Introduce duplicate checking strategies:
use simple map strategy for cases when expected number of elements is
small enough, use dynamic bucket based array strategy in case if expected
number of elements is quite high.
Proposed changes speedups things significantly and for quite big numbers of
duplicates allow create unique indexes in seconds instead of minutes.

2017-07-27 09:33 UTC, MishaDemianenko commented
<b>N.B.: should be null merged to 3.3 because of values refactoring, some changes will be required.</b

2017-08-02 13:17 UTC, burqen requested changes
The map approach has O(1) in time complexity for `checkForDuplicate`.
Bucket approach has O(n).
This makes a little bit worried. Do we have any benchmarks that verifies that this is not a significant regression?

2017-08-02 13:17 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/api/exceptions/index/IndexEntryConflictException.java
> +    public IndexEntryConflictException( long existingNodeId, long addedNodeId, Object... propertyValue )
Could use `propertyValues` to reflect var args in parameter name.

2017-08-02 13:17 UTC, burqen commented on community/lucene-index/src/main/java/org/neo4j/kernel/api/impl/schema/verification/DuplicateCheckStrategy.java
> +                return propertyValuesEqual( properties, that.values );
`equals` and `hashCode` does not align. Both property key and value is used to calculate `hashCode` but equals only check property value, which means two `PropertyValues` object can be equal but have different hash code. For the use case that we have this is fine, but confusing. 

Suggestion: Change the hash code function to only check values array instead to make it less confusing.

2017-08-02 13:17 UTC, burqen commented on community/lucene-index/src/main/java/org/neo4j/kernel/api/impl/schema/verification/DuplicateCheckStrategy.java
> +        private EntrySet[] actualValues;
I was a bit confused about what was the "buckets". Can we improve naming to make this more clear?

Something like (but probably not):
`actualValues` -> `buckets`
`EntrySet` -> `BucketNode`
`entrySetSize` -> `bucketNodeSize`

2017-08-02 13:17 UTC, burqen commented on community/lucene-index/src/main/java/org/neo4j/kernel/api/impl/schema/verification/DuplicateCheckStrategy.java
> +        private static class EntrySet
A small javadoc about this guy being a linked list where each entry contain `nodeId`:`propertyValue` pairs would be nice.

2017-08-02 13:17 UTC, burqen commented on community/lucene-index/src/main/java/org/neo4j/kernel/api/impl/schema/verification/PartitionedUniquenessVerifier.java
> +                 */
Nice clarification!

2017-08-03 08:26 UTC, MishaDemianenko commented
@burqen updated

2017-08-09 14:15 UTC, burqen approved these changes

2017-08-13 13:49 UTC, merged