Unify numeric types conversion utilities. Introduce Numbers.
neo4j/neo4j pull request #9725
Opened 2017-07-27 13:55 UTC by MishaDemianenko

Remove duplicated conversions across code base that perform
safe conversion from one numeric type to another. Unify them and cleanup.

2017-07-30 18:39 UTC, tinwelint commented on community/common/src/main/java/org/neo4j/helpers/Numbers.java
> +    public static int safeCastLongToInt( long value )
Isn't this `Math.toIntExact` btw?

2017-08-01 07:27 UTC, MishaDemianenko commented on community/common/src/main/java/org/neo4j/helpers/Numbers.java
> +    public static int safeCastLongToInt( long value )
Almost, except error message that aligns with other safe casts error messages

2017-08-02 13:44 UTC, burqen requested changes
Found a missing test case, otherwise this looks fine 🎉 
Nice cleanup!

2017-08-02 13:44 UTC, burqen commented on community/common/src/test/java/org/neo4j/helpers/NumbersTest.java
> +        assertEquals(Short.MAX_VALUE, safeCastIntToUnsignedShort( Short.MAX_VALUE ));
We are not testing the largest value for an unsigned short here.

2017-08-02 15:48 UTC, MishaDemianenko commented
@burqen updated

2017-08-03 06:57 UTC, burqen approved these changes

2017-08-03 06:58 UTC, merged