Migrate to native label index during store upgrade
neo4j/neo4j pull request #9746
Opened 2017-07-31 17:18 UTC by MishaDemianenko

Add additional migrator participant that will create and populate
native label index as part of store upgrade if it does not exist yet.
Migrator is fully integrated into upgrade procedure: it's separate migration step
and support population progress reporting.

2017-07-31 17:19 UTC, MishaDemianenko commented
<b>This PR does not force migration from 3.2 to 3.3 as it is now</b>

2017-08-01 08:57 UTC, chrisvest requested changes
This would break store migration on blockdevice, and also a relevant integration test is failing.

2017-08-01 08:57 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/kernel/impl/storemigration/participant/NativeLabelScanStoreMigrator.java
> +            fileSystem.moveToDirectory( nativeLabelIndex, storeDir );
This won't work on blockdevice. Take a look at how the `StoreMigrator` does it.

2017-08-01 08:57 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/kernel/impl/storemigration/participant/NativeLabelScanStoreMigrator.java
> +        return !fileSystem.fileExists( new File( storeDir, NativeLabelScanStore.FILE_NAME ) );
This one is also problematic on blockdevice.

2017-08-02 11:10 UTC, MishaDemianenko commented
@chrisvest updated

2017-08-07 13:44 UTC, chrisvest approved these changes

2017-08-10 04:31 UTC, merged