Added support for UniqueIndexSeek in the register interpreted runtime
neo4j/neo4j pull request #9763
Opened 2017-08-02 08:52 UTC by eebus

2017-08-02 10:05 UTC, craigtaverner requested changes

2017-08-02 10:05 UTC, craigtaverner commented on enterprise/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/UniqueIndexAcceptanceTest.scala
> +      val result = testWith(Configs.All, "MATCH (n:Person)-->() USING INDEX n:Person(name) WHERE n.name IN ['Jacob'] RETURN n")
Looks like we have removed the test on plans being similar. This seems wrong.

2017-08-02 10:05 UTC, craigtaverner commented on enterprise/cypher/cypher/src/test/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/interpreted/RegisteredPipeBuilderTest.scala
> +    val apply = Apply(lhs, rhs)(solved)
Do we really need to test unique index and 'index nested loop join' (ie. Apply with both lhs and rhs)? We could test the index alone.

2017-08-08 15:38 UTC, craigtaverner requested changes

2017-08-08 15:38 UTC, craigtaverner commented on enterprise/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/UniqueIndexAcceptanceTest.scala
> +      val result = succeedWith(Configs.All, "MATCH (n:Person)-->() USING INDEX n:Person(name) WHERE n.name IN ['Jacob'] RETURN n")
The test previously checked that all planners and runtimes used the same plan, and therefor obeyed the hint in the same way. This new version seems to have skipped that check.

2017-08-11 07:50 UTC, craigtaverner approved these changes

2017-08-14 09:02 UTC, SaschaPeukert approved these changes

2017-08-14 11:27 UTC, merged