Procedures now close acquired KernelStatements
neo4j/neo4j pull request #9764
Opened 2017-08-02 09:30 UTC by burqen

Verified in test by performing two index reads with
intermediate create. Second read should see result
of create but will not if KernelStatement has leaked,
because Lucene reader from first match will be reused
for second read.

2017-08-02 09:42 UTC, burqen commented
Merge commit to 3.2 here https://github.com/burqen/neo4j/tree/3.2-procedures-close-kernel-statement-merge-from-3.1

2017-08-02 10:46 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/SchemaProcedure.java
> +            try ( Transaction transaction = graphDatabaseAPI.beginTx(); )
Do we need this inner transaction? We are already in a transaction, so this will be a dummy.

2017-08-02 14:13 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/SchemaProcedure.java
> +            try ( Transaction transaction = graphDatabaseAPI.beginTx(); )
I would guess not, but cleaning this up is outside the scope of this PR.

2017-08-03 09:08 UTC, MishaDemianenko requested changes
Looks good, a couple of small comments. While this change cleaned up a lot of incorrect statements usages here and there I think we need more strict eyes on those. We need *the tracker* that will track open statements in the transaction and will fail it in the case when it will be closed without statements being closed across all our tests at least, sounds like a good idea?

2017-08-03 09:08 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/SchemaProcedure.java
> +                        ResourceIterator<Label> labelsInUse = graphDatabaseAPI.getAllLabelsInUse().iterator();
this resource iterator should be closed as well

2017-08-03 09:08 UTC, MishaDemianenko commented on enterprise/neo4j-enterprise/src/test/java/org/neo4j/kernel/builtinprocs/ProcedureResourcesIT.java
> +            db.schema().awaitIndexesOnline( 1, TimeUnit.SECONDS );
this can be not enough on latest 3.3 version

2017-08-03 09:08 UTC, MishaDemianenko commented on enterprise/neo4j-enterprise/src/test/java/org/neo4j/kernel/builtinprocs/ProcedureResourcesIT.java
> +        StringBuilder sb = new StringBuilder();
String joiner can be used here to simplify looping and checks, not that important in the same time

2017-08-03 09:08 UTC, MishaDemianenko commented on enterprise/neo4j-enterprise/src/test/java/org/neo4j/kernel/builtinprocs/ProcedureResourcesIT.java
> +public class ProcedureResourcesIT
different versions will contain different procedures so this test will need some adaptations during merges be careful there 👀

2017-08-03 09:08 UTC, MishaDemianenko commented on enterprise/neo4j-enterprise/src/test/java/org/neo4j/kernel/builtinprocs/ProcedureResourcesIT.java
> +public class ProcedureResourcesIT
its' also strange that this test does not catch a case where we still have one statement that is not closed because of not closed resource iterable

2017-08-10 13:34 UTC, burqen commented
For completeness. Here is an attempt at tracking open statements: https://github.com/neo4j/neo4j/pull/9794

2017-08-10 13:58 UTC, burqen commented on enterprise/neo4j-enterprise/src/test/java/org/neo4j/kernel/builtinprocs/ProcedureResourcesIT.java
> +public class ProcedureResourcesIT
Problem was there was no relationships in the dataset which meant that code path was never hit. Fixed now.

2017-08-10 13:59 UTC, burqen commented on enterprise/neo4j-enterprise/src/test/java/org/neo4j/kernel/builtinprocs/ProcedureResourcesIT.java
> +            db.schema().awaitIndexesOnline( 1, TimeUnit.SECONDS );
Hmm... set to 5 just in case then.

2017-08-10 14:04 UTC, burqen commented
@MishaDemianenko Comments addressed. Will take care to adapt test during forward merge!

2017-08-15 09:48 UTC, MishaDemianenko commented on enterprise/neo4j-enterprise/src/test/java/org/neo4j/kernel/builtinprocs/ProcedureResourcesIT.java
> +        StringBuilder sb = new StringBuilder();
that is what i thinking about:
```
        StringJoiner stringJoiner = new StringJoiner( ",", "CALL " + procedureName + "(", ")" );
        for ( Object parameter : parameters )
        {
            stringJoiner.add( parameter.toString() );
        }
        return stringJoiner.toString();
```

2017-08-15 09:49 UTC, MishaDemianenko commented on enterprise/neo4j-enterprise/src/test/java/org/neo4j/kernel/builtinprocs/ProcedureResourcesIT.java
> +        System.out.println( sb.toString() );
in any case you do not need to print this string

2017-08-15 10:07 UTC, MishaDemianenko approved these changes
@burqen 2 small comments otherwise looks good will approve now but please take a look on them

2017-08-15 12:41 UTC, burqen commented
@MishaDemianenko Ping 👍

2017-08-15 13:34 UTC, MishaDemianenko commented
@burqen Pong, whats up?)

2017-08-15 14:56 UTC, burqen commented on enterprise/neo4j-enterprise/src/test/java/org/neo4j/kernel/builtinprocs/ProcedureResourcesIT.java
> +        StringBuilder sb = new StringBuilder();
Aaah, cool!

2017-08-15 14:57 UTC, burqen commented on enterprise/neo4j-enterprise/src/test/java/org/neo4j/kernel/builtinprocs/ProcedureResourcesIT.java
> +        System.out.println( sb.toString() );
\*facepalm\*

2017-08-15 15:27 UTC, MishaDemianenko commented
👍

2017-08-16 14:15 UTC, merged