CompositeNodeKeyConstraintAcceptanceTest updated to LernaeanTestSupport
neo4j/neo4j pull request #9778
Opened 2017-08-04 15:06 UTC by SaschaPeukert

Also added a failWithError method to LernaeanTestSupport

2017-08-05 13:39 UTC, craigtaverner commented on enterprise/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/CompositeNodeKeyConstraintAcceptanceTest.scala
> +    testWith(Configs.Procs,
Should the test setup also be part of what is being tested? I think parts in 'given' should be run simply, and then the 'when/then' parts are actually tested.

2017-08-06 10:50 UTC, SaschaPeukert commented on enterprise/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/CompositeNodeKeyConstraintAcceptanceTest.scala
> +    testWith(Configs.Procs,
I would agree, but the 'given' parts were tested previously as well. Thus I thought there is some reason behind it. But if there is not, I happily change it

2017-08-08 12:17 UTC, craigtaverner requested changes
It feels like we might be testing a bunch of Cypher stuff for tests that are not at all about Cypher. Should we be using the new support here at all?

2017-08-08 12:17 UTC, craigtaverner commented on enterprise/cypher/acceptance-spec-suite/src/test/scala/org/neo4j/internal/cypher/acceptance/CompositeNodeKeyConstraintAcceptanceTest.scala
> +    succeedWith(Configs.Procs,
This line is really just a test setup command, not a test itself. However, written like this it is currently only testing that `CREATE CONSTRAINT` commands are disallowed with any runtime or planner or version prefixes, which is certainly out of scope for this test. So we end up running this schema command on all scenarios where all scehma commands will fail, and expect failure. This is very redundant. Let's rather have this test only test what it was meant to test.

2017-08-11 15:20 UTC, craigtaverner approved these changes

2017-08-17 07:05 UTC, merged