Unflake Neo4jJobSchedulerTest
neo4j/neo4j pull request #9819
Opened 2017-08-16 09:44 UTC by tinwelint

2017-08-17 10:35 UTC, burqen requested changes

2017-08-17 10:35 UTC, burqen commented on community/kernel/src/test/java/org/neo4j/kernel/impl/util/Neo4jJobSchedulerTest.java
> +        awaitInvocationCount( 0 );
Should be 1

2017-08-17 10:35 UTC, burqen commented on community/kernel/src/test/java/org/neo4j/kernel/impl/util/Neo4jJobSchedulerTest.java
>          awaitFirstInvocation();
Can remove this call because of `awaitInvocationCount( count )` below.

2017-08-21 10:15 UTC, tinwelint commented
@burqen fixed now (squashed due to a trivial test change)

2017-08-22 07:55 UTC, burqen approved these changes

2017-08-22 08:49 UTC, merged