Renamed dbms.allow_format_migration to dbms.allow_upgrade for clarification
neo4j/neo4j pull request #9853
Opened 2017-08-18 13:18 UTC by klaren

Configuration option `dbms.allow_format_migration` has been renamed to `dbms.allow_upgrade` since it applies to more than format migration. 

The expected behaviour is that the database should refuse to start if any changes will be made to the store that will prevent the database from starting on a previous version of neo4j.

2017-08-22 08:38 UTC, burqen requested changes

2017-08-22 08:38 UTC, burqen commented on community/neo4j/src/test/java/db/DatabaseStartupTest.java
> -                          "please set configuration parameter \"dbms.allow_format_migration=true\"",
Nice catch!

2017-08-22 08:38 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/configuration/GraphDatabaseConfigurationMigrator.java
> +                "dbms.allow_format_migration has been replaced with dbms.allow_upgrade." )
Nice! Can we also add a test for this?

2017-08-22 08:38 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/graphdb/factory/GraphDatabaseSettings.java
> +    public static final Setting<Boolean> allow_upgrade = setting( "dbms.allow_upgrade", BOOLEAN, FALSE );
Have you looked into what implications this change has for docs? Let's make sure that is handled before merging.

2017-08-22 14:40 UTC, klaren commented on community/kernel/src/main/java/org/neo4j/kernel/configuration/GraphDatabaseConfigurationMigrator.java
> +                "dbms.allow_format_migration has been replaced with dbms.allow_upgrade." )
@burqen We definitely should, new commit available!

2017-08-24 12:13 UTC, burqen approved these changes

2017-08-24 12:14 UTC, burqen commented
@klaren Approved! Don't know if the docs_compile error is related. It does not look like it, but worth checking with docs team before merging.

2017-08-24 12:17 UTC, merged