Add feature toggle for stronger index entry hashing
neo4j/neo4j pull request #9862
Opened 2017-08-21 11:03 UTC by chrisvest

2017-08-22 08:37 UTC, chrisvest commented
Build is green. Github just missed the signal from the Tools Compile build.

2017-08-22 14:53 UTC, MishaDemianenko requested changes
Couple of small comments otherwise looks good!

2017-08-22 14:53 UTC, MishaDemianenko commented on community/common/src/main/java/org/neo4j/hashing/IncrementalXXH64.java
> + * This hash function is roughly twice as fast as its predecessor, about 30% faster than optimised murmurhash3
not really clear which predecessor we are talking about here

2017-08-22 14:53 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/locking/ResourceTypes.java
> +     * The schema index entry hashing method used up until 2.2.0.
That's not that really so right since `LegacyIndexProxy` still use it now?

2017-08-22 14:53 UTC, MishaDemianenko commented on community/kernel/src/main/java/org/neo4j/kernel/impl/locking/ResourceTypes.java
> +        long hash = IncrementalXXH64.init( 0x0123456789abcdefL );
We already have HashFunction defined that is used in a HopScotch, i would say that IncrementalXXH64 should be changed to be out of the possible HashFunctions and they should be moved to commons module most probably, and that interface can be extended to include `update(hash, block)` and `finalise(hash)` so new hashing function will not gonna be glued that much to ResourceTypes

2017-08-22 18:15 UTC, chrisvest commented on community/kernel/src/main/java/org/neo4j/kernel/impl/locking/ResourceTypes.java
> +     * The schema index entry hashing method used up until 2.2.0.
Oh, I missed that.

2017-08-23 08:41 UTC, chrisvest commented
@MishaDemianenko I believe I've addressed your comments. Please have another look.

2017-08-23 08:50 UTC, MishaDemianenko approved these changes
Looks great now!

2017-08-23 09:49 UTC, merged