Functions on the registered runtime
neo4j/neo4j pull request #9884
Opened 2017-08-23 13:14 UTC by systay

2017-08-23 13:16 UTC, systay commented
Unit tests for the RegisterAllocation additions still missing

2017-08-23 13:28 UTC, craigtaverner requested changes
Surely some of the cucumber tests that previously failed for slotted runtime would start passing now? I did not see changes to the blacklisting here.

2017-08-23 13:28 UTC, craigtaverner commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/BuildEnterpriseInterpretedExecutionPlan.scala
> +      val converters = new ExpressionConverters(EnterpriseExpressionConverters, CommunityExpressionConverter)
Surprised this did not cause issues before.

2017-08-23 13:28 UTC, craigtaverner commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/RegisteredRewriter.scala
> +      case _ => throw new CantCompileQueryException(s"Expressions with on object other then nodes and relationships are not yet supported")
Perhaps remove 'with'

2017-08-23 13:28 UTC, craigtaverner commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/interpreted/EnterprisePipeBuilder.scala
> +        val fromSlot = pipeline.getLongOffsetFor(from)
Variables should be renamed back to 'offset' also then.

2017-08-23 13:28 UTC, craigtaverner commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/PipelineInformation.scala
> +  def toString(startFrom: LogicalPlan, m: Map[LogicalPlan, PipelineInformation]): String = {
I'm not seeing any calls to this new PipelineInformation.toString(....) method in the PR. Is this part of some other work?

2017-08-24 05:00 UTC, systay commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/PipelineInformation.scala
> +  def toString(startFrom: LogicalPlan, m: Map[LogicalPlan, PipelineInformation]): String = {
You are right. It helped me debug a problem, and I thought it was helpful enough to stick around, but I'm not sure how to expose it to the public yet.

2017-08-24 05:01 UTC, systay commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/BuildEnterpriseInterpretedExecutionPlan.scala
> +      val converters = new ExpressionConverters(EnterpriseExpressionConverters, CommunityExpressionConverter)
Before the two converters never took on the same expressions, so the order was not important. With these new specialisations, that is no longer true.

2017-08-24 21:55 UTC, craigtaverner approved these changes

2017-08-24 23:37 UTC, merged