Add procedures for manual indexes
neo4j/neo4j pull request #9909
Opened 2017-08-25 13:54 UTC by Lojjs

2017-08-25 20:57 UTC, lutovich commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/BuiltInProcedures.java
> +        ArrayList<BooleanResult> arrayResult = new ArrayList<>();
Better use `Stream#of()` everywhere to convert single element to stream.

2017-08-25 20:57 UTC, lutovich commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/BuiltInProcedures.java
> +        List<BooleanResult> results = new ArrayList<>( 2 );
`Stream#of()` can help here as well.

2017-08-28 20:38 UTC, craigtaverner requested changes

2017-08-28 20:38 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/BuiltInProcedures.java
> +                    result.add( new IndexResult( "INDEX ON " + index.schema().userDescription( tokens ), operations.indexGetState( index ).toString(), type ) );
Why this reformating?

2017-08-28 20:38 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/BuiltInProcedures.java
> +                    ConstraintResult::new );
Reformating seems to make this less readable.

2017-08-28 20:38 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/BuiltInProcedures.java
> +            results.add( new BooleanResult( true ) );
Would be nicer to see which indexes were deleted.

2017-08-28 20:38 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/BuiltInProcedures.java
> +            results.add( new BooleanResult( false ) );
Nothing removed should mean no rows returned.

2017-08-28 20:38 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/BuiltInProcedures.java
> +        return results.stream();
Stream.of

2017-08-30 07:38 UTC, pontusmelke commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/BuiltInProcedures.java
> +    public Stream<RelationshipResult> relationshipManualIndexSearch( @Name( "indexName" ) String manualIndexName, @Name( "query" ) Object query )
Shouldn't this be replaced by the other procedure? Or do we need two?

2017-09-01 15:32 UTC, craigtaverner approved these changes

2017-09-01 15:32 UTC, craigtaverner commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/BuiltInProcedures.java
> +    @Procedure( name = "db.index.manual.exists.forNodes", mode = READ )
It would seem easy enough to add a default parameter for index config, where the default is no config.

2017-09-04 08:00 UTC, pontusmelke commented on community/kernel/src/main/java/org/neo4j/kernel/builtinprocs/BuiltInProcedures.java
> +        public final double weight;
How should a user interact with the weight?

2017-09-04 08:38 UTC, merged

2017-09-05 13:54 UTC, jexp commented on community/cypher/cypher/src/test/java/org/neo4j/cypher/internal/javacompat/NotificationAcceptanceTest.java
> +                                        "`CALL db.index.manual.seek.nodes('index', 'key', 'value') YIELD node AS n` " +
nodes.seek ?

2017-09-05 13:54 UTC, jexp commented on community/cypher/cypher/src/test/java/org/neo4j/cypher/internal/javacompat/NotificationAcceptanceTest.java
> +                                        "`CALL db.index.manual.seek.relationships('index', 'key', 'value') YIELD " +
relationships.seek