3.3 slotted sort pipe
neo4j/neo4j pull request #9948
Opened 2017-08-30 15:07 UTC by sherfert

2017-08-31 14:34 UTC, systay requested changes
Nice stuff!

2017-08-31 14:34 UTC, systay commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/pipes/SortPipe.scala
> +    assert(orderBy.nonEmpty)
since `orderBy` is an instance field, can't we do this assertion outside the method?

2017-08-31 14:34 UTC, systay commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/pipes/SortPipe.scala
> +    val comparator = orderings.reduceLeft((a: Comparator[ExecutionContext], b) => a.thenComparing(b))
Really nice refactoring! 👍

2017-08-31 14:34 UTC, systay commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/interpreted/pipes/SortRegisterPipe.scala
> +    assert(orderBy.nonEmpty)
Same as for the community pipe - move outside of method?

2017-08-31 14:34 UTC, systay commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/pipes/SortPipe.scala
> +    val comparator = orderings.reduceLeft((a: Comparator[ExecutionContext], b) => a.thenComparing(b))
Tiny cosmetic opinion: 

I would write the above as:

```
        val comparator = orderings.reduceLeft[Comparator[ExecutionContext]] {
          case (a,b) => a thenComparing b
        }
```

2017-08-31 20:13 UTC, fickludd requested changes
In general I think the logic looks sound and nice. I have some comments on how we might increase readability, but they should be easy to address.

2017-08-31 20:13 UTC, fickludd commented on community/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/pipes/SortPipe.scala
> +case class Descending(id: String) extends SortDescription {
I'm thinking about names in this class... WDYT about changing 

`SortDescription` => `ColumnOrder`
`SortDescription.compareAny` => `ColumnOrder.compareValues`
`InnerOrdering` => `ExecutionContextOrdering` (or really `RowOrdering` once we change that)

2017-08-31 20:13 UTC, fickludd commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/interpreted/EnterprisePipeBuilder.scala
> +        case Some(slot) => interpretedPipes.Ascending(slot.offset)
I wanted to check this spot out in Intellij but can't atm. Let's have a quick look together tomorrow. I might have more naming suggestions.

2017-08-31 20:13 UTC, fickludd commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/interpreted/pipes/SortRegisterPipe.scala
> +    array.toIterator
I'm guessing explicitly using `Array.sort` is a wise choice for performance.

2017-08-31 20:13 UTC, fickludd commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/interpreted/pipes/SortRegisterPipe.scala
> +
Double white line... checkstyle, your honor!

2017-08-31 20:13 UTC, fickludd commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/interpreted/pipes/SortRegisterPipe.scala
> +private class InnerOrdering(order: SortDescription)(implicit qtx: QueryState) extends scala.Ordering[ExecutionContext] {
And otherwise my name-suggestions from community were intended for here too.

2017-08-31 20:13 UTC, fickludd commented on enterprise/cypher/cypher/src/main/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/interpreted/pipes/SortRegisterPipe.scala
> +  def offset: Int
Maybe `propertyOffset` or `propertySlot`

2017-08-31 20:13 UTC, fickludd commented on enterprise/cypher/cypher/src/test/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/RegisterAllocationTest.scala
> +    // given UNWIND [1,2,3] as x RETURN x
There is no sorting in this CYPHER query?

2017-08-31 20:13 UTC, fickludd commented on enterprise/cypher/cypher/src/test/scala/org/neo4j/cypher/internal/compatibility/v3_3/runtime/RegisterAllocationTest.scala
> +    allocations(produceResult) shouldBe theSameInstanceAs(allocations(unwind))
I like `... shouldBe theSameInstanceAs(...`. Makes it very explicit that they are in the same pipeline.

2017-09-02 05:57 UTC, systay approved these changes

2017-09-02 13:29 UTC, fickludd approved these changes

2017-09-03 18:05 UTC, merged