Improve error message for duration settings
neo4j/neo4j pull request #9974
Opened 2017-09-04 11:54 UTC by klaren

The error message for a duration now includes valid units.

2017-09-04 15:08 UTC, burqen requested changes
Nice changes! I don't think they work all the way though, since `Settings.apply` only pass along message from the "closest" cause.
```
catch ( IllegalArgumentException e )
{
    throw new InvalidSettingException( name(), value, e.getMessage() );
}
```
Verified with "test":
```
@Test
public void badDuration() throws Exception
{
    Setting<Duration> setting = buildSetting( "foo.bar", DURATION ).build();
    try
    {
        setting.apply( map( stringMap( "foo.bar", "hej" ) ) );
    }
    catch ( InvalidSettingException e )
    {
        e.printStackTrace();
    }
}
```
That prints stack trace:
```
org.neo4j.graphdb.config.InvalidSettingException: Bad value 'hej' for setting 'foo.bar': Error parsing duration setting

	at org.neo4j.kernel.configuration.Settings$DefaultSetting.apply(Settings.java:1299)
	at org.neo4j.kernel.configuration.Settings$DefaultSetting.apply(Settings.java:1202)
	at org.neo4j.kernel.configuration.SettingsTest.badDuration(SettingsTest.java:289)
```

2017-09-05 10:28 UTC, burqen approved these changes

2017-09-05 10:28 UTC, burqen commented
@klaren Looks super!

2017-09-06 08:24 UTC, jjaderberg approved these changes
:+1:

2017-09-06 08:25 UTC, merged