Changes schema index directory structure for fusion index
neo4j/neo4j pull request #9995
Opened 2017-09-06 08:34 UTC by tinwelint

The lucene schema index provider puts its indexes in:

  <db>/schema/index/lucene/<indexId>/...

this commit doesn't change this, but the fusion index provider,
i.e. the combination of lucene+native gets a new structure driven by the need
to one day be able to do efficient background migration of schema indexes
and for convenience in the wild. The new structure looks like this:

  <db>/schema/index/<providerKey>/<providerVersion>/<indexId>/...

This has two benefits:

- all index data related to one index lives in one directory
- indexes on disk are also versions, just like providers are

Since the fusion index also uses a lucene schema index provider internally,
this structure has been made pluggable and given to a SchemaIndexProvider
at construction time. See IndexDirectoryStructure. This class has all knowledge
about the base schema root directory and various directory structure implementations
collected in one place.

NOTE This change does not require any migration, except for databases recently
created, where the fusion index is enabled by default. Although no releases
has had the fusion index in them so that is not a problem.

2017-09-06 17:58 UTC, tinwelint commented
@burqen you had some comments, didn't you? Where are they?

2017-09-07 07:08 UTC, burqen requested changes
Looks sweet! Gonna be awesome with a more separated directory structure.
Got a few comments, most of which we have already talked about.

I would prefer if we could combine `provider_key` and `provider_version` into one directory name instead of separating them into two directories.
In that way we could treat sub-provider directories the same as "first" provider directory.

Instead of:
`<db>/schema/index/lucene_native/0.1/5/lucene/...`
`<db>/schema/index/lucene_native/0.1/5/native/...`
It would look like:
`<db>/schema/index/lucene_native_0.1/5/lucene_?/...`
`<db>/schema/index/lucene_native_0.1/5/native_0.3/...`

2017-09-07 07:08 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/api/index/IndexDirectoryStructure.java
> +package org.neo4j.kernel.api.index;
Am I mistaken or is this package not public API? If so, this class should be moved somewhere else.

2017-09-07 07:08 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/api/index/IndexDirectoryStructure.java
> +     * Returns root directory. Must be above all sub-directories returned from {@link #directoryForIndex(long)}.
"Must be above" could be changed to "Must be parent to"

2017-09-07 07:08 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/api/index/IndexDirectoryStructure.java
> + * which then a {@link IndexDirectoryStructure} given its {@link Descriptor}.
Bring this sentence back to a consistent state, please.

Nice javadoc otherwise 👍

2017-09-07 07:08 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/schema/fusion/FusionSchemaIndexProvider.java
> +    public FusionSchemaIndexProvider( IndexDirectoryStructure.Factory directoryStructure,
May I suggest putting `directoryStructure` as last parameter to align better with `super`

2017-09-07 07:08 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/schema/NativeSchemaNumberIndexProvider.java
> +    private static final String INDEX_FILE_NAME = "index";
Would be nice to also have index id as part of file name for easier readability by humans.

2017-09-07 07:08 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/schema/NativeSchemaNumberIndexProvider.java
>      public NativeSchemaNumberIndexProvider( PageCache pageCache, File storeDir, LogProvider logging,
Can be package-private

2017-09-07 07:08 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/impl/index/schema/NativeSchemaNumberIndexProvider.java
> +            RecoveryCleanupWorkCollector recoveryCleanupWorkCollector, boolean readOnly )
Quite a few double constructors and factory methods are added in this PR to accommodate for `IndexDirectoryStructure`. I think it would be cleaner to just inline the `directoriesByProvider( storeDir )` method instead.

2017-09-07 07:08 UTC, burqen commented on community/lucene-index/src/main/java/org/neo4j/kernel/api/impl/schema/NativeLuceneFusionSchemaIndexProviderFactory.java
> +        LuceneSchemaIndexProvider luceneProvider = LuceneSchemaIndexProviderFactory.create( fs, childDirectoryStructure, logProvider, config,
Long lines

2017-09-07 07:08 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/api/index/IndexDirectoryStructure.java
> +    static final File baseSchemaIndexFolder( File databaseStoreDir )
Does not need to be final.

2017-09-07 07:08 UTC, burqen commented on community/kernel/src/main/java/org/neo4j/kernel/api/index/IndexDirectoryStructure.java
> +        return new Factory()
Can be lambda

2017-09-07 08:46 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/kernel/api/index/IndexDirectoryStructure.java
> +package org.neo4j.kernel.api.index;
The kernel API isn't public, so that's fine

2017-09-07 08:46 UTC, tinwelint commented on community/kernel/src/main/java/org/neo4j/kernel/api/index/IndexDirectoryStructure.java
> + * which then a {@link IndexDirectoryStructure} given its {@link Descriptor}.
Missing a `creates` right?

2017-09-07 09:26 UTC, tinwelint commented
Updated

2017-09-07 13:53 UTC, tinwelint commented
Hmm recent rebase exposed an issue where the index directories under the fusion provider aren't deleted when dropping an index. This should be looked into first.

2017-09-07 14:27 UTC, burqen approved these changes

2017-09-07 14:35 UTC, burqen commented
@tinwelint Changes look good 👍  but build state looks a bit more 👎

2017-09-07 14:56 UTC, burqen requested changes
Second thought, let's not approve this until build failure is solved.

2017-09-08 09:12 UTC, tinwelint commented
@burqen updated and should fix the last test failure.

2017-09-12 06:17 UTC, burqen approved these changes

2017-09-12 06:21 UTC, merged